### ISSUE TITLE
You did it

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1000]
# Congratulations, you found the 1000th issue

![giphy](https://user-images.githubusercontent.com/1659006/214106670-d78ec53f-db16-4c8a-8b85-8a8b115c565a.gif)

**Comment by oliverschuerch** [comment]
![king-of-the-world-freedom](https://user-images.githubusercontent.com/9716662/237052373-c2ccc835-8209-4a2b-a3b0-50fe430e9920.gif)
