### ISSUE TITLE
Component: Multiselect | Positive

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1115]
![image](https://user-images.githubusercontent.com/1659006/218787574-7fa0f317-478e-4d31-a1a3-ab0a17ebb071.png)

We got a request for a multi select dropdown pattern.

**Comment by wueestd** [comment]
is also on our roadmap planned for next week: https://miro.com/app/board/uXjVOMlqJGg=/?moveToWidget=3458764541140447822&cot=14

**Comment by wueestd** [comment]
@Cian77 will start next week composing a multi select

**Comment by wueestd** [comment]
**Code**
https://next.design-system.post.ch/?path=/docs/components-select--docs
https://design-system.post.ch/#/bootstrap-samples/form-multiple-select

**Comment by gfellerph** [comment]
Closing in favour of v2 #3453
