### ISSUE TITLE
Header: Improve location search

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1148]
The location search in the header does not deliver the same suggestions as on the portal. Analyze differences in implementation and provide insights.

If actions can be taken, create sub-tickets.

![image](https://user-images.githubusercontent.com/1659006/220351294-e022b464-2587-4d0f-a0d3-d0a0b89c9f5f.png)

Use https://www.post.ch/api/Suggestions/Suggestions?sc_site=post-portal&sc_lang=de&query=bahnhof&numberOfSuggestions=7 for suggestions. Set the parameters for `sc_site` to `localizedConfig.onlineServiceId` and `sc_lang` to the current language.

**Comment by oliverschuerch** [comment]
I did a quick research by comparing the sent requests for each Header.

| | Design System Header | Portal Header |
| :- | :- | :- |
| User searches after "Bahnhofstrasse" | Creates 3 requests ![Image](https://user-images.githubusercontent.com/9716662/224729023-46549f4f-bb26-4b1b-a753-f55d20b0d575.png) | Creates 2 requests ![Image](https://user-images.githubusercontent.com/9716662/224729424-23e9c9db-f332-400b-b67d-6cc036a3341f.png) |
| 1. Request | https://www.post.ch/de/api/trackandtrace?id=bahnhofstrasse | https://www.post.ch/coveo/rest/search/v2/querySuggest?sitecoreItemUri=sitecore%3A%2F%2Fweb%2F%7B106EC9FC-128A-4AE2-A350-69021128A524%7D%3Flang%3Dde%26amp%3Bver%3D269&siteName=post-portal |
| 2. Request | https://platform-eu.cloud.coveo.com/rest/search/v2/querySuggest?q=bahnhofstrasse&... | https://www.post.ch/api/Suggestions/Suggestions?sc_site=post-portal&sc_lang=de&query=Bahnhofstrasse&numberOfSuggestions=7 |
| 3. Request | https://places.post.ch/StandortSuche/StaoCacheService/Geocode?query=bahnhofstrasse&lang=de&pois=T8%2CT5%2CT1%2CT6%2CT7%2CT2&limit=33 ||

Even if some urls look similiar, the requests and responses are not the same.

**Comment by oliverschuerch** [comment]
I figured out why we have different search results.
Whenever we send a request for places to the StaoCache API, we send not only the search query, the language and a limit. We also send some poi types and therefore we get other results from the api.

As soon as I remove the poi types from the request-url, we get a list of the exact same places like they get in the portal header.
