### ISSUE TITLE
Header: Navigation not completely hidden when scrolling down

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1156]
When scrolling down and stickyness is set to minimal, the header does not completely hide. The 1px border bottom is still visible at the top of the page.

<img width="1104" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/1659006/220832450-e00a7676-0877-42ad-80b6-fa6a138bf030.png">

Account for the border when transforming the header:
![image](https://user-images.githubusercontent.com/1659006/220833009-ee0f6c74-ecc8-4254-b95f-99221d442e36.png)

Reproduction: https://next.design-system.post.ch/iframe.html?args=&id=components-internet-header-header--default&viewMode=story

**Comment by cellcoresystems** [comment]
Can I help ?

**Comment by gfellerph** [comment]
Sure, thanks 💕
