### ISSUE TITLE
NgbButtons don't show active state

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1196]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1659006/221785693-aa838444-6a62-4eb9-b520-3dc4d927e20a.png">

The yellow active state is no longer visible for ngb-buttons.

https://design-system.post.ch/#/ng-bootstrap-samples/buttons

**Comment by alizedebray** [comment]
Checkbox and Radio buttons are no longer a part of ng-bootstrap since version [13.0.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#1300-2022-07-28).
