### ISSUE TITLE
How to keep old documentation alive

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1239]
Is there a way on netlify to keep old documentation pages alive?

## First findings

- Branch deploys (previews) are being deleted after 90 days (unless it's a GitHub branch deploy, which is not linked in our use case)
- Production deploys are kept forever and have a unique URL (e.g. https://6401b5c167e11f27f2f741f8--swisspost-design-system-next.netlify.app). At the moment it's not possible to automatically link a unique production deploy to a specific Design System version, but a list could be established manually, at least for major and minor releases
- If a public json containing a version : url mapping is published on https://design-system.post.ch, even old applications would always fetch the latest json and could link to newer versions

## Second findings
Automating the generation of the versions file is pretty hard. Steps would look like:
1. Deploy the production site in order to get the correct URL
2. Read URL from success message
3. Generate versions.json
4. Re-deploy the whole site with the new versions.json
5. Commit new versions.json to main

++ Always up to date
-- Two deploys necessary
-- Two commits to main on publish

Alternative approach, always lagging behind one version but would be ok because the current version is always on the same URL:
1. When generating the release preview PR, query netlify for the latest deployed target URL (is that possible?)
2. Generate versions.json
3. Commit and open PR with updated versions.json (will include currently deployed versions, but not the soon to be deployed next version)
4. The one-behind versions.json will get automatically deployed with the regular workflow

++ Can use existing workflows, no duplicate deploys or commits, is possible because link to latest deploy does not change
++ Can preview the versions.json before committing to main
+- versions.json is always one deploy behind
+- not sure if possible

Example script to update `versions.json`:
```js
const fs = require('fs');
const path = require('path');
const packageJSON = require('../package.json');
const versionsFile = require('../src/assets/versions.json');
const minimist = require('minimist');
const args = minimist(process.argv.slice(2));

const interestingPackages = [
  "@angular/core",
  "@swisspost/design-system-styles",
  "@swisspost/design-system-intranet-header",
  "bootstrap",
  "@ng-bootstrap/ng-bootstrap",
];

const getInterestingPackages = () => {
  return Object.entries({ ...packageJSON.dependencies, ...packageJSON.devDependencies}).reduce((acc, [key, value]) => {
    if (interestingPackages.includes(key)) {
      acc[key] = value;
    }

    return acc;
  }, {})
}

const writeVersions = () => {
  console.log(args);
  const newVersions = [{
    title: `v${packageJSON.version}`,
    version: packageJSON.version,
    description: packageJSON.description,
    url: args.url,
    dependencies: getInterestingPackages()
  }, ...versionsFile || null];

  fs.writeFileSync(path.join(process.cwd(), 'packages/demo/src/assets/versions.json'), JSON.stringify(newVersions, null, '  '))
}

writeVersions();
```

**Comment by oliverschuerch** [comment]
It should be possible, to add the `--alias` to define a custom url-slug which will be used in the deployment url.
We allready using this to create the preview urls and should be able to use it for `--prod` deployments as well.
See more informations here: https://docs.netlify.com/cli/get-started/#draft-deploys

Deployment url with random alphanumeric prefix: https://640ed3caee9aa13dbae703c9--swisspost-web-frontend.netlify.app/
Customized deployment url example: https://v6-0-0--swisspost-web-frontend.netlify.app/
