### ISSUE TITLE
Update stylelint-prettier

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1264]
There is a new version of stylelint-prettier and stylelint-config-sass-guidelines that includes a breaking change. Update the packages and fix the breaking changes. Renovate sent a PR that failed ().

```[tasklist]
### PRs that failed
- [ ] https://github.com/swisspost/design-system/pull/1186
- [ ] https://github.com/swisspost/design-system/pull/1269
```

**Comment by oliverschuerch** [comment]
@gfellerph is this still a thing?

**Comment by gfellerph** [comment]
@oliverschuerch, it's done, stylelint prettier is up to date.
