### ISSUE TITLE
Die neuen Icons werden mit Angular nicht richtig geladen.

### ISSUE THREAD

**Issue by burrimaxi** [swisspost/design-system#1295]
### Bei Angular besteht das Problem darin, dass der Wert der Eigenschaft name von <post-icon> nicht dynamisch zugewiesen werden kann.

Wenn die Eigenschaft name nach dem ersten Laden der Seite geändert oder hinzugefügt wird, tritt der folgende Fehler auf.

Hier ist die Fehlermeldung der Konsole:
![image](https://user-images.githubusercontent.com/128683550/227165125-37a81844-6da1-451e-b09d-f1559e45bee9.png)

Hier ist das Ergebnis in Elements:
![image](https://user-images.githubusercontent.com/128683550/227164420-89231845-1db7-40b9-bbf5-0e024f5f43b4.png)

**Comment by gfellerph** [comment]
Thanks for the report @burrimaxi, do you have a link where the issue can be reproduced?
