### ISSUE TITLE
Icons: Group and make searchable

### ISSUE THREAD

**Issue by pazoozooCH** [swisspost/design-system#1299]
Hi everybody

Everytime I have to search for a *Post Icon*, it takes me like 10 minutes because they are neither searchable nor ordered / grouped in a very helpful way on the [Demo Page](https://design-system.post.ch/#/post-samples/icons).

The fact that they are identified by numbers instead of descriptive text doesn't help too much either (I guess _pi-letter_ would be more meaningful than _pi-1001_).

First some questions:

- There seems to be _some_ logic behind the numbering, e.g. _pi-8xxx_ being social media / app icons. Is this documented somewhere?
- Is there already a page (internal to Post or external) where the icons are listed in a searchable / grouped way?

Would it be possible to extend the demo page to display the icons in groups and to add tags / keywords to them to make them searchable / filterable? I could also make a PR proposal for this, but I'm not sure if I'm the right person to do the actual grouping / tagging of the icons. But maybe that already exists somewhere?

Cheers Martin

**Comment by gfellerph** [comment]
Hey @pazoozooCH, thanks for reaching out. We're in the process of re-writing our documentation and you can find a preview of the new icon docs here https://next.design-system.post.ch/?path=/docs/foundations-icons--icons (there are performance issues at the moment, we're looking at it). This provides you with a simple text search as the icons are indeed tagged, but the number is still being used as name. This is not something that's easily changed at the moment. Grouping of icons is a possibility we're looking at together with the Design team. There is an undocumented logic behind the number ranges, but I'm not sure it will be useful for implementation at this point.

**Comment by pazoozooCH** [comment]
Hi @gfellerph 

Thanks for the feedback and the link. It took my browser a couple of refreshes and clicking around until it actually loaded / displayed the icons. I guess that's the performance issues you were refering to?

But that's already a huge improvement over the previous list! From what I've seen, the applied tags seem to be reasonably helpful.

As we have 800+ icons, grouping or categorizing them feels natural, but it's not as important as making them filterable.

I don't mind the number too much during development, but it makes it harder to read existing code, e.g. in a PR. You just don't have any clue what an icon might be unless you actually render it or look it up... So if there was an easy way of aliasing the numbers - but again, not the biggest priority I guess...

Cheers Martin
