### ISSUE TITLE
Intranet Header: Auto-Close on optionDropdownContent

### ISSUE THREAD

**Issue by pazoozooCH** [swisspost/design-system#1300]
Hi everybody

We're using the intranet header with a template ref that contains both `<a>` elements with `routerLink` and `<button>` elements with `(click)` handlers.

The problem is that if we do routing (regardless whether through link or action), the dropdown stays open. If the action displays a modal, it will eventually close when the modal is closed as it loses focus. But it should also close on a navigation link.

Do you have any hints on how to best do that? I guess I _could_ probably come up with a solution that puts the focus on some other random element, but that seems a bit hacky.

Would be nice if the documentation would include `optionDropdownContent` examples with `routerLink` as this is probably not an uncommon usecase.

**Comment by gfellerph** [comment]
Thanks for the report. We're looking into it.

**Comment by pazoozooCH** [comment]
Here's a simple code snippet of what I'm doing:
```
<div class="layout-container header-small bg-light">
  <sp-intranet-header
    logoUrl="/ui/home"
    [showIntranetSearch]="false"
    [optionDropdownContent]="profileMenu"
  >
  </sp-intranet-header>
</div>

<ng-template #profileMenu>
  <a class="dropdown-item" routerLink="/ui/home">To Home</a>
</ng-template>
```

When the _To Home_ link is clicked, navigation is performed, but the dropdown stays open - I would like it to close on click...

**Comment by pazoozooCH** [comment]
Will test it once it's available. Which version will have this fix included?

**Comment by gfellerph** [comment]
@pazoozooCH, it's going to be 4.0.4. You can track the release PR (https://github.com/swisspost/design-system/pull/1417) or subscribe to releases to be notified when it's merged. I think it's going to be released Thursday, 7. June.
