### ISSUE TITLE
Updated dependencies not listed in changelog for the internet-header

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1313]
The internet-header changelog does not list updated packages (https://github.com/swisspost/design-system/pull/1285):
![image](https://user-images.githubusercontent.com/1659006/228203485-4e5e1948-d4bf-4c30-83a1-c35d0b429db0.png)

The styles package should be part of the dependencies instead of the dev dependencies.

```[tasklist]
### Affected packages
- [x] Components
- [x] Internet Header
```

**Comment by oliverschuerch** [comment]
@gfellerph

I think this is not the only problem with missmatched dependencies/devDependencies.
For example:
- The packages `internet-header` and `components` have a dependency to `bootstrap`, which should already be available from within the styles package.
- The `components` package has also a `devDependency` to `@popperjs/core`, which (in my opinion) should be a `dependency`, if we really use it somewhere.
- The `styles` package has a dependency to `typescript`, which should be a `devDependency` instead.
- The packages `demo` and `documentation` have a devDependency to `prettier`, which should be a `dependency` instead.
