### ISSUE TITLE
Internet header: incorect contrast in dark mode

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1352]
In dark mode, some texts are not shown with the correct contrast in the internet header package: 

Language selection on mobile:
![Image](https://user-images.githubusercontent.com/33580481/233299318-e99bd805-2a5e-4ac0-baa6-919ab65f9461.png)

Breadcrumbs:
![Image](https://user-images.githubusercontent.com/33580481/233299490-95dd30de-deea-46be-a27e-e31d2e85079f.png)

Footer:
![Image](https://user-images.githubusercontent.com/33580481/233300101-c1ba76ba-0e0b-43e7-ba0b-45c9e3540cd8.png)

**Comment by gfellerph** [comment]
Closing as not needed.
