### ISSUE TITLE
Vertical stepper

### ISSUE THREAD

**Issue by degiorgig** [swisspost/design-system#1364]
currently in the design system there is only an horizontal stepper. 
For multisteps and also for mobile application is better to have it vertical, are you planning to build it?

**Comment by oliverschuerch** [comment]
Thank you for your question @leader80.
We have not planned a vertical stepper right now, but I will discuss the topic with the Team.

**Comment by oliverschuerch** [comment]
@rouvenpost Thank you!
I have refactored the track and trace vertical stepper form scratch, because it was not built very well.
But you're right, we could use this refactored version as a starting point for the new vertical stepper implementation.

**Comment by oliverschuerch** [comment]
Duplicate #954.

**Comment by gfellerph** [comment]
Closing in favor of #3363.
