### ISSUE TITLE
Remove visually hidden text out of the logo link in the internet-header component

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1366]
Isabelle Haas has reportet an issue to the new logo integration:

There are two text alternatives in the new header logo.
Screenreaders are reading both, the visually hidden text of the link and the alt attribute of the logo, which are quite similar.

Suggested solution: Remove visually hidden text in the link and leave only the alt attribute of the image.

Reproduction: https://next.design-system.post.ch/iframe.html?args=&id=components-internet-header-header--default&viewMode=story

**Comment by cococonscious** [comment]
Hi, can I work on this? Thanks

**Comment by cococonscious** [comment]
It seems that the issue has already been fixed, closing
