### ISSUE TITLE
Update the "Fetch icons" workflow

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1389]
- If an icon is removed, the change set should mark the change as major;
- If an icon is added, the change set should mark the change as minor;
- If an icon is updated, the change set should mark the change as a fix;
- The change set description is currently always plural, it must be singular if only one icon has changed.
- There are missing spaces in the changelog.

**Comment by oliverschuerch** [comment]
Ask @alizedebray for more details, before you start working on this issue.

**Comment by alizedebray** [comment]
Done with https://github.com/swisspost/design-system/pull/2453
