### ISSUE TITLE
KLP notification widget shown wrong for B2B account

### ISSUE THREAD

**Issue by m-dionisio** [swisspost/design-system#1391]
Hello,
when landing on https://int.post.ch/en/customer-center/customer-center with a B2B account, the initials in the notifications widget are not centered correctly. See attachment.
![widget](https://user-images.githubusercontent.com/132910776/236827794-c8586561-f893-4537-85aa-409508ff8edd.jpg)

**Comment by gfellerph** [comment]
Closing because issue can't be reproduced any more.
