### ISSUE TITLE
Demo: update migration guide

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1392]
Add package versions to the migration guide (i.e. in the "Migration from v4 to v5" section the "New package installation" command should be `npm install @swisspost/design-system-styles@5 @swisspost/design-system-intranet-header@3`).

The list of version is available here: https://github.com/swisspost/design-system/blob/bc3d6de779db00dd2a629662543a03f19ffd5304/packages/demo/src/assets/versions.json

**Comment by oliverschuerch** [comment]
We need to add this information in the v5 migration guide as well as in the v6 migration guide.
