### ISSUE TITLE
Styles: make v5 stable or inform users it is not

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1393]
Currently the v5 of the styles package as mismatched dependencies: 
- v6 was created because of a breaking change introduced by ng-bootstrap starting from [v13.0.0](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#1300-2022-07-28) were checkbox and radio buttons were removed,
- v5 should therefore use ng-bootstrap v12.x.x to not contain this breaking change,
- v12.x.x of ng-bootstrap require using Angular 13.0.0 and Bootsrap 5.0.0 according to the [dependency documentation](https://ng-bootstrap.github.io/#/getting-started#dependencies)

The v5 should therefore have its dependencies updated or show a message to say it is not stable and should not be used.

**Comment by alizedebray** [comment]
We will not change the dependencies. Check if it is possible to configure an npm warning to inform user that the v5 is not stable but v6 is now available.

**Comment by oliverschuerch** [comment]
@alizedebray is this ticket still needed, since we have compatiblity tables soon in the docs?
https://github.com/swisspost/design-system/pull/2159

**Comment by gfellerph** [comment]
I think this ticket here originally prompted work on https://github.com/swisspost/design-system/pull/1481 and the intention was to fix v5 but I don't know what the status of the old release workflow is anymore. Not sure if the tables alone fix the issue, it's certainly nothing that is very urgent.

The workflow for old versions though would still be very nice to have.

**Comment by gfellerph** [comment]
Closing as no longer relevant
