### ISSUE TITLE
Component: Content Switcher (Segmented Controll)

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1394]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=10129%3A53612&t=5mzQjs4il43FOfTt-1

**Comment by wueestd** [comment]
same question here @rouvenpost do you think we can change this pattern?

**Comment by wueestd** [comment]
any accessibility concerns here @Cian77 ?

**Comment by Cian77** [comment]
@rouvenpost: Hier muss noch der AX-Check gemacht werden.

**Comment by wueestd** [comment]
- [ ] check design (accessibility and visual) 
- [ ] fix height (8px grid)

**Comment by gfellerph** [comment]
Closing as duplicate of #2633
