### ISSUE TITLE
Optimize Tag

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1396]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11194%3A50777&t=5mzQjs4il43FOfTt-1

**Comment by rouvenpost** [comment]
@wueestd wird der Active State noch ergänzt oder brauchts den nicht?

**Comment by wueestd** [comment]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11194%3A50777&t=GUPIwHa9X6FjgfKx-1 Active state habe ich bewusst weggelassen und sonst würde ich glaube einfach den hover nehmen, was meinst du? @rouvenpost

**Comment by wueestd** [comment]
could you please check the new component @gfellerph

**Comment by gfellerph** [comment]
Looks good, a few inputs:
- Can there be a text only tag?
- Text on the green/success tag needs to be black according to the current WCAG 2.1 contrast algorithm. With WCAG3s APCA it will be white, but that's not released yet
- Is there a max-length for tags? I think it could make sense to build a more solid tag that does not break on multiple lines. We could set a character limit of e.g. 20 (in CSS: `max-width: 20ch; text-overflow: ellipsis`)

**Comment by wueestd** [comment]
- yes the can be text only, I added a toggle
- I changed the text on green to black
- we can not set a limit but we can write guidelines. not sure if setting a character limit is the right thing to do :)
- also I would get rid oft the small 20px height variant or do you see any need for this?

@kaloyanso could you do a quick review of the component: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12815%3A61841&mode=design&t=Z8WKSeFXKT9PNnrY-1

**Comment by wueestd** [comment]
defined a max lenght and added documentation. Have a look @gfellerph !

**Comment by gfellerph** [comment]
Looks good from my perspective! I added the component to the tracker board https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=43864320 and created a dev ticket https://github.com/swisspost/design-system/issues/2237
