### ISSUE TITLE
Internet header: add a11y labels to the config object

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1398]
To improve Internet Header's accessibility we need the following a11y labels to be added to the configuration object:
- title for the meta navigation link group (#1339)
<img src="https://user-images.githubusercontent.com/33580481/237640748-18a9d2f2-3725-4760-9196-3d287e5fd22f.png" height="32">

- title for the skip link group (#1339)
<img src="https://user-images.githubusercontent.com/33580481/237641368-62d830d7-5522-4c6e-a5f1-5bbc82ce8317.png" height="32">

-title for the breadcrumbs middle drop down menu (#1339 & #1358)
<img src="https://user-images.githubusercontent.com/33580481/237644276-d0698b5f-c307-42ec-9f74-b0eb21365c00.png" height="128">

- label for the active navigation link (e.g. "Aktiver Navigationspunkt") (#1341)
<img src="https://user-images.githubusercontent.com/33580481/237641601-8713ec5a-58a6-4043-95d7-83599efad412.png" height="32">

**Comment by oliverschuerch** [comment]
Did you inspect the current config? Most of the information should allready be there:

![Image](https://github.com/swisspost/design-system/assets/9716662/23641158-09fa-4854-a7a4-4caafcfca9a6)

**Comment by oliverschuerch** [comment]
@alizedebray The skiplinks are not wrapped with a `nav` element and the `ul` element will have an `aria-label` attribute as soon as the PR #1402 is merged, therefore we do not need to add an `aria-label`.
