### ISSUE TITLE
KLP widget sets focus to login button on page load

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1415]
In the `klp-login-widget` inside of the `internet-header`, there is a `setFocus` method, which sets the focus to the login button.
This happens as well, if another element on the page has the attribute `autofocus` set and takes the focus (depending on the moment, when the `setFocus` method is called) away from the `autofocus` element.

This error occurs only if the user is logged in.

**Comment by oliverschuerch** [comment]
I've identified the following lines as the ones, causing this error:

```javascript
// function renderAuthenticatedWidget
1091  selectFromShadowDom()
1092    .find('#' + id + ' .klp-widget__user')
1093    .focus();
```

The following lines are inside a jQuery click/touch event handler, which should not be triggered on page load.
Sadly the event gets triggered from within the `renderWidget` function (which is called on page load and many other times):

```javascript
function renderWidget() {
    if (typeof sessionData !== 'undefined') {
     // with this function call the widget will be created
     // and the on click/touch event handler gets binded on the .klp-widget-authenticated-session-link button
      renderAuthenticatedWidget();
    } else {
      renderAnonymousWidget();
    }
    document.dispatchEvent(new CustomEvent('wepploginwidget_widget_ready'));
    measureWidgetShowsUp();
    // this triggers the before binded event and therefore moves the focus away from any element with the autofocus attribute
    selectFromShadowDom().find('.klp-widget-authenticated-session-link').click();
}
```

We could simply remove the focus-setter or check if we can safely remove the last line in the renderWidget function.

**Comment by gfellerph** [comment]
I'd say we remove the line. Does not make sense in my eyes and the risk to break something is minimal.

**Comment by oliverschuerch** [comment]
There is a reason why the click is triggered on the `.klp-widget-authenticated-session-link` element, everytime the `renderWidget` function is called:
The function creates the widget html and writes it to the dom, but with the menu flyout visible. The click is performed, to close the widget, which simply adds a `display: none` inline style on the flyout.

I removed the click trigger and added a inline style on the flyout to hide it on init.
This should hopefully remove the focus shift on initial widget rendering.

We need to do a beta release for the internet-header and install it only on an affected project, to test its behaviour.
