### ISSUE TITLE
Layout: Split view

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1427]
A request for a split view component was submitted by an external contributor:

![image](https://github.com/swisspost/design-system/assets/1659006/15e263e1-7995-453e-b373-82b9daad3270)

```[tasklist]
### Tasks
- [ ] Discuss with Design Team about similar requests
- [ ] Decide if it is a valid component for integration
```

**Comment by rouvenpost** [comment]
Needs Design

**Comment by gfellerph** [comment]
Closing as won't do, low interest
