### ISSUE TITLE
Styles: Placeholder text of file input fields is misaligned on Safari

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1492]
![Image](https://github.com/swisspost/design-system/assets/33580481/367a94f2-664c-42f4-bb8f-4497037f12f2)

**Comment by imagoiq** [comment]
Here is my proposal : https://github.com/swisspost/design-system/pull/1614

On Safari, when we move the file selector button, the space dedicated to it stays whatever we'll try. This seems to be a known bug by the community (see https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/, https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/), but I didn't find anything on https://bugs.webkit.org.

The most used workaround (which was in our code before https://github.com/swisspost/design-system/pull/1323) is to create our own label with the after pseudo-element. However, applying a pseudo-element on a self-closing tag like input is not supported by Firefox.

So, the above proposal fixes both by targeting exclusively WebKit users.

2 other solutions:
1. Ignore native placeholder values and hide them while retrieving input value with JavaScript. This is often the solution, you'll find when looking for how to customize file input style on the web.
2. Change the design to have the button before the value as natively.

Maybe at some point, we'll have a "replacement" for this native input, as [it's listed in the Open-UI initiative.](https://open-ui.org/components/file/)

**Comment by imagoiq** [comment]
[fix(form-file): file-selector-button cutoff in Safari
](https://github.com/swisspost/design-system/pull/1614)
