### ISSUE TITLE
Optimize Dropdown

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1501]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12639%3A60344&t=Oc7lhYg2E5NGXV35-1

**Comment by gfellerph** [comment]
@wueestd, the Design looks good, but from a dev viewpoint we have multiple components here. One is a menu for navigation or toolbars, one is a select menu where you make choices for a form and we might even extract a base dropdown component that provides the functionality of displaying a panel below an element. Development needs more investigation.

**Comment by gfellerph** [comment]
approved, @wueestd

**Comment by wueestd** [comment]
When combining the component with other components (especially small buttons) I find it to be very oversized. what do you think @gfellerph & @rouvenpost ? https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12775%3A61376&mode=design&t=7oqrnfHBJ8pn1R7p-1

 should we make it a bit smaller (e.g. 14px font size and some smaller spacings) or should we maintaint two versions?

**Comment by gfellerph** [comment]
I think two versions would be good, then we have dedicated support for internal applications.

**Comment by rouvenpost** [comment]
Creating two Sizes for the Dropdown Menu.... including smaller Checkboxes and Radioboxes

**Comment by rouvenpost** [comment]
Ready for Review

**Comment by gfellerph** [comment]
@rouvenpost and @wueestd, the Design looks good. I'd like to discuss https://github.com/swisspost/design-system/discussions/1888 however because for development a dropdown where you can select options is something different than a dropdown with buttons/links that directly call an action. There are also different accessibility requirements for the two.

**Comment by gfellerph** [comment]
- [ ] @gfellerph create dev tickets for all necessary components

**Comment by gfellerph** [comment]
Dev tickets will be created after naming resolution for a bunch of new components in https://www.figma.com/file/hPSc0je4Pwa8pL0PLnfmrS/Component-Naming?type=whiteboard&node-id=0%3A1&t=0DkA2N6Wx8EbP0Z1-1
