### ISSUE TITLE
Demo: automate version selector

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1503]
The version selector on the demo application is configured from the [version.json](https://github.com/swisspost/design-system/blob/main/packages/demo/src/assets/versions.json) asset file.

Currently this file is maintained manually, which can lead to an empty selector if a new version is released without the version.json being updated (see #1483).

The goal of this ticket is to find a way to automate the version selector so that it stays up to date with each new release without manual intervention.

**Comment by gfellerph** [comment]
Efforts abandoned for now, manual documentation can be found here https://github.com/swisspost/design-system/wiki/How-to-do-a-major-release. Will revisit when major release workflow is more clear.
