### ISSUE TITLE
Component: Tooltips

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1510]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12772%3A61141&t=3YWu4pbxHkxbNAu6-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=579%3A9207&mode=design&t=sPZqfB953ntQ7LZs-1

**Code**
https://design-system.post.ch/#/ng-bootstrap-samples/popover
https://design-system.post.ch/#/ng-bootstrap-samples/tooltip

**Doc**
https://www.nngroup.com/articles/tooltip-guidelines/

Split into two components:
- Tooltip (hover)
- Popover (klick)

**Comment by wueestd** [comment]
check Color variants

**Comment by gfellerph** [comment]
@wueestd: points to discuss
- Do we want to introduce a new size (5.5px)?
- Dev: hide arrow/indicator in default implementation
- Resolve other comments in figma

**Comment by wueestd** [comment]
all comments resolved

**Comment by gfellerph** [comment]
@wueestd I created a component entry on the tracker board https://github.com/swisspost/design-system-planning/issues/202 and added a dev ticket #2240 

This issue can be closed.
