### ISSUE TITLE
Webpack build fails because of source maps

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1526]
I've tryed to install and import the @swisspost/internet-header package to a vuejs 3 project, which is setup with webpack and a source-map-loader plugin installed.
If I use the suggested import in the documentation (which loads the esm-es5 module):
```js
import { defineCustomElements } from '@swisspost/internet-header';
defineCustomElements();
```

I unfortunately get the following error:

![image](https://github.com/swisspost/design-system/assets/9716662/6f3abfee-105c-4e78-b474-98e649b67074)

With the `main` module (defined in the `package.json`) it works:
```js
import { defineCustomElements } from '@swisspost/internet-header/loader/index.cjs.js';
defineCustomElements();
```

**Comment by gfellerph** [comment]
Also investigate 

![Image](https://github.com/swisspost/design-system/assets/1659006/ffec71c0-d461-4a83-97fe-c5c4dbd28351)

**Comment by imagoiq** [comment]
Here is my analysis so far, so we have a base for discussion if needed.

First of all, I've found this [readme](https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/readme.md) particularly useful to better understand the meaning behind the output files.

## How to use a component according to the doc

Some places in the documentation report wrong paths to import (see https://stenciljs.com/docs/v3/distribution#distribution-options and https://github.com/ionic-team/stencil-site/issues/933).

Other parts are talking about those ways: 

From CDN:
```
<script type="module">      
	import { defineCustomElements } from 'https://cdn.jsdelivr.net/npm/@ionic/core/loader/index.es2017.mjs';  

	defineCustomElements();    
</script>
```
https://stenciljs.com/docs/v3/javascript

.mjs extension is not used anymore, but at this one exception, it's working. Example with the internet-header: https://glitch.com/edit/#!/amethyst-teal-buffer

From package:

```
import { defineCustomElements } from 'stencil-library/loader';
```

Working example with the internet-header: https://codesandbox.io/s/elated-rgb-jyny9t?file=/src/App.vue

## What is this loader folder, and when should it be used?
It was not clear from the start as from the following old PR and our own documentation, loader is presented as piece to make it work with bundler like Webpack: https://github.com/ionic-team/stencil/commit/99add6784ed5ca366d42de70733189ce5502c32f

But if we look at https://github.com/ionic-team/stencil/blob/main/src/compiler/output-targets/readme.md, it clearly defines that it contains the lazy-loaded build.

The other variant (socalled custom-element) without lazy-loading is actually described here in our doc: https://next.design-system.post.ch/?path=/story/internet-header-getting-started--page#jsdelivr

## Why stencil warns use to use dist index in main property of the package.json

So the validation can be controlled with the `validatePrimaryPackageOutputTarget`, more info: https://stenciljs.com/docs/output-targets#primary-package-output-target-validation
I couldn't find a lot of information about that, but I think it's link to the conclusion of my analysis in https://github.com/swisspost/design-system/issues/1721.

## Questions
* Do we use the "www" build actually?
* Is it possible to load the lazy-loaded version through only inline script src attribute (like in our jsdelivr example)?

From that, I can make a draft PR to update our doc, I think.
