### ISSUE TITLE
Header: test new logo animation

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1529]
[Create Internet-Header Logo Prototypes#186](https://github.com/swisspost/design-system-planning/issues/186)

**Comment by gfellerph** [comment]
- [ ] Update grey line behavior (there should not be a grey line to the left of the logo)

**Comment by wueestd** [comment]
Preview: https://preview-1552--swisspost-design-system-next.netlify.app/?path=/story/internet-header-components-header--default
