### ISSUE TITLE
Checkbox and Radio: Adjust Focus State

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1542]
the grey border at the moment is not accessible due to the missing contrast

https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7777%3A34266&t=b3kxhLmIteQxIkkq-1

https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7777%3A34196&t=b3kxhLmIteQxIkkq-1

**Comment by wueestd** [comment]
adjusted some colors: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations-Post?type=design&node-id=2215%3A13427&mode=design&t=Quk03By6o0pMYVBW-1

**Comment by gfellerph** [comment]
@Cian77 I'm closing this as duplicate of #2179 and #2187
