### ISSUE TITLE
Update to node 18

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1544]
There are some packages we currently use that are not compatible with node 18 (some kind of envelope routine error on build). These errors need further investigation and possibly dependency updates.

_Originally posted by @gfellerph in https://github.com/swisspost/design-system/pull/1534#pullrequestreview-1488231806_

**Comment by imagoiq** [comment]
When trying, the following error occurs `digital envelope routines::unsupported` 

We have 2 options (mentioned in: https://github.com/storybookjs/storybook/issues/21739)
1. Move to Storybook 7
2. Provide `NODE_OPTIONS="--openssl-legacy-provider"` with our commands

The first one is preferable.
