### ISSUE TITLE
V5 Testing: HCM (only Safari left)

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#156]
Test all components in Windows High Contrast Mode (alt + shift + print screen). Look for:

- [x] Is text clearly legible?
- [x] Are icons shown?
- [x] Are focus states indicated?
- [x] Are active elements (active links, checkboxes) indicated?
- [x] Are disabled elements indicated?

**Browsers**
- [x] Chrome latest on Windows
- [x] Firefox latest on Windows
- [x] Safar latest on Mac Os

**Comment by LarissaMS** [comment]
## Crossbrowser testing

## How to test

We need to test every component in every (relevant) browser and on every breakpoint.

1.  Open component in specified browser on browserstack.
2.  Test the grafical presentation; does something look broken, shaky or does not match the screendesign?
3.  Test all breakpoints; is something offscreen, not wrapping correctly or does not match the screendesign?
4.  Test the functionality; does something not work as expected?
5.  Create issues for every found bug.  
    Title: fix(compoment-name, browser): issue title  
    Content: Bug description and how to reproduce it  
    Labels: bug, web-styles  
    Project: Design System Development  
    Milestone: Version 5

## Testprotocol

### Bootstrap

| Component | General issues | ![chrome](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/chrome/chrome_16x16.png) | ![firefox](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/firefox/firefox_16x16.png) | ![safari](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/safari/safari_16x16.png) | Status | Comments |
| --- | --- | --- | --- | --- | --- | --- |
| [Alert/Notifications](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/alert) | #254, #255 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Badge](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/badge) |   |   |   |   | :construction: |   |
| [Background](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/background) | #258 [:triangular\_flag\_on\_post:](../issues?q=is:issue+is:closed+256) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Blockquotes](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/blockquotes) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Buttons](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/buttons) |   |   |   |   | :construction: |   |
| [Cards](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/card) | #259, #260 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Forms](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/forms) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Form controls](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-control) | #262 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Form checkbox](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-check) | #261 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [From select](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-select) | #262 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Form select multiple](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-multiple-select) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | #263 | :warning: |   |
| [Form radio button](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-radio) | #261 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Form range](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-range) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Form switch](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-switch) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | #265 | :warning: |   |
| [Form file](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-file) | #262 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Paragraph](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/paragraph) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Tables](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/tables) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Textarea](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-textarea) | #262 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Typography](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/typography) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |

### NgBootstrap

| Component | General issues | ![chrome](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/chrome/chrome_16x16.png) | ![firefox](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/firefox/firefox_16x16.png) | ![safari](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/safari/safari_16x16.png) | Status | Comments |
| --- | --- | --- | --- | --- | --- | --- |
| [Accordion](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/accordion) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Alert](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/alert) | #267 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Buttons](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/buttons) | #268, #271 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: | deprecated in ng-bootstrap 13 |
| [Carousel](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/carousel) | :heavy\_check\_mark: [:triangular\_flag\_on\_post:](../issues?q=is:issue+is:closed+269) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Collapse](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/collapse) | #270 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [DatePicker](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/datepicker) | #262 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Dropdown](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/dropdown) | #280 | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :warning: |   |
| [Modal](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/modal) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Pagination](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/pagination) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Popover](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/popover) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | ngBootstrap popover has no autoposition, if at specified position is to less space |
| [Progressbar](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/progressbar) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Rating](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/rating) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Tabs](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/tabs) |   |   |   |   | :construction: |   |
| [Timepicker](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/timepicker) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Tooltips](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/tooltip) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | ngBootstrap tooltip has no autoposition, if at specified position is to less space |
| [Typeahead](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/typehead) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |

### Post

| Component | General issues | ![chrome](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/chrome/chrome_16x16.png) | ![firefox](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/firefox/firefox_16x16.png) | ![safari](https://cdnjs.cloudflare.com/ajax/libs/browser-logos/72.0.0/safari/safari_16x16.png) | Status | Comments |
| --- | --- | --- | --- | --- | --- | --- |
| [Accordion](https://swisspost-web-frontend.netlify.app/#/post-samples/accordion) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Custom select](https://swisspost-web-frontend.netlify.app/#/post-samples/custom-select) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | #283 | :warning: |   |
| [Datatable](https://swisspost-web-frontend.netlify.app/#/post-samples/datatable) |   |   |   |   | :construction: |   |
| [Feedback](https://swisspost-web-frontend.netlify.app/#/post-samples/feedback) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Forms](https://swisspost-web-frontend.netlify.app/#/post-samples/forms) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Icons](https://swisspost-web-frontend.netlify.app/#/post-samples/icons) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Intranet Header](https://swisspost-web-frontend.netlify.app/#/post-samples/intranet-layout) |   |   |   |   | :construction: |   |
| [Notification Overlay](https://swisspost-web-frontend.netlify.app/#/post-samples/notification-overlay) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Post Cards](https://swisspost-web-frontend.netlify.app/#/post-samples/post-cards) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Sizing](https://swisspost-web-frontend.netlify.app/#/post-samples/sizing) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Spinner](https://swisspost-web-frontend.netlify.app/#/post-samples/spinner) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Stepper](https://swisspost-web-frontend.netlify.app/#/post-samples/stepper) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: |   |
| [Subnavigation](https://swisspost-web-frontend.netlify.app/#/post-samples/subnavigation) | :heavy\_check\_mark: | :heavy\_check\_mark: | :heavy\_check\_mark: | #284 | :warning: |   |
| [Topic Teaser](https://swisspost-web-frontend.netlify.app/#/post-samples/topic-teaser) | #282 | :heavy\_check\_mark: | #281 | #281 | :warning: |   |

## Legend

### Icons

| Icon | Meaning |
| --- | --- |
| :construction: | work in progress |
| :triangular\_flag\_on\_post: | link to closed issues |
| :grey\_question: | not yet tested |
| :warning: | there is one or more issues with this component |
| :heavy\_check\_mark: | all tests passed |

### Tested Browsers

| Browser | Platform | Version |
| --- | --- | --- |
| Chrome | Windows 10 | 103 |
| Firefox | Windows 10 | 103 |
| Edge | Windows 10 | 103 |
| Safari | Mac OS Monterey | 15.3 |
| Chrome@Android | Samsung Galaxy S22 | 12 |
| Safari@iOS | iPhone 13 | 15 |

**Comment by gfellerph** [comment]
- [ ] Test Safari High Contrast Mode as soon as the testing device is available
