### ISSUE TITLE
Docs: import changelog in storybook

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1560]
Storybook v7 now uses MDX2 and can no longer read the changelog.md
We have to find a way to render this page: https://next.design-system.post.ch/?path=/docs/misc-changelog--page

**Comment by oliverschuerch** [comment]
Try to change the creation of the changlog.md to changelog.mdx (v2) in the github workflow, so it can be used in the storybook v7 directly.
Or try to use an iframe.
