### ISSUE TITLE
V5 Testing: Cross Browser

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#157]
Test all components in different browsers on Browserstack.

- [x] Chrome latest on Windows
- [x] Firefox latest on Windows
- [x] Edge latest on Windows (not sure if necessary since same rendering engine as chrome)
- [x] Safari latest on MacOs
- [x] Safari latest on iOs
- [x] Chrome for Android

**Comment by oliverschuerch** [comment]
# Testprotocol

## How to test

We need to test every component in every (relevant) browser and on every breakpoint.

1. Open component in specified browser on browserstack.
2. Test the grafical presentation; does something look broken, shaky or does not match the screendesign?
3. Test all breakpoints; is something offscreen, not wrapping correctly or does not match the screendesign?
4. Test the functionality; does something not work as expected?
5. Create issues for every found bug.<br>Title: fix(compoment-name, browser): issue title

## Icon legend

| Icon | Meaning |
| :-: | :- |
| :grey_question: | not yet tested |
| :heavy_check_mark: | all tests passed |
| :heavy_exclamation_mark: | there are one or more issues with this component |

## Bootstrap

| Component | Issues | Chrome | Firefox | Edge | Safari (OS) | Safari (iOS) |
| - | - | :-: | :-: | :-: | :-: | :-: |
| [Alert/Notifications](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/alert) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Badge](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/badge) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Background](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/background) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Blockquotes](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/blockquotes) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Buttons](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/buttons) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Cards](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/card) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Forms](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/forms) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form controls](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-control) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form checkbox](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-checkhttps://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-select) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form select multiple](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-multiple-select) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form radio button](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-radio) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form range](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-range) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form switch](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-switch) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Form file](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-file) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Paragraph](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/paragraph) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Tables](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/tables) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Textarea](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/form-textarea) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Typography](https://swisspost-web-frontend.netlify.app/#/bootstrap-samples/typography) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |

## NgBootstrap

| Component | Issues | Chrome | Firefox | Edge | Safari (OS) | Safari (iOS) |
| - | - | :-: | :-: | :-: | :-: | :-: |
| [Accordion](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/accordion) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Alert](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/alert) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Buttons](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/buttons) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Carousel](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/carousel) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Collapse](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/collapse) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [DatePicker](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/datepicker) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Dropdown](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/dropdown) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Modal](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/modal) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Pagination](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/pagination) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Popover](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/popover) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Progressbar](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/progressbar) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Rating](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/rating) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Tabs](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/tabs) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Timepicker](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/timepicker) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Tooltips](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/tooltip) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Typeahead](https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/typehead) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |

## Post

| Component | Issues | Chrome | Firefox | Edge | Safari (OS) | Safari (iOS) |
| - | - | :-: | :-: | :-: | :-: | :-: |
| [Accordion](https://swisspost-web-frontend.netlify.app/#/post-samples/accordion) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Custom select](https://swisspost-web-frontend.netlify.app/#/post-samples/custom-select) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Datatable](https://swisspost-web-frontend.netlify.app/#/post-samples/datatable) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Feedback](https://swisspost-web-frontend.netlify.app/#/post-samples/feedback) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Forms](https://swisspost-web-frontend.netlify.app/#/post-samples/forms) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Icons](https://swisspost-web-frontend.netlify.app/#/post-samples/icons) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Intranet Header](https://swisspost-web-frontend.netlify.app/#/post-samples/intranet-layout) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Notification Overlay](https://swisspost-web-frontend.netlify.app/#/post-samples/notification-overlay) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Post Cards](https://swisspost-web-frontend.netlify.app/#/post-samples/post-cards) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Sizing](https://swisspost-web-frontend.netlify.app/#/post-samples/sizing) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Spinner](https://swisspost-web-frontend.netlify.app/#/post-samples/spinner) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Stepper](https://swisspost-web-frontend.netlify.app/#/post-samples/stepper) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Subnavigation](https://swisspost-web-frontend.netlify.app/#/post-samples/subnavigation) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |
| [Topic Teaser](https://swisspost-web-frontend.netlify.app/#/post-samples/topic-teaser) | - | :grey_question: | :grey_question: | :grey_question: | :grey_question: | :grey_question: |

**Comment by gfellerph** [comment]
Closing as done
