### ISSUE TITLE
Component: Cards (Product Cards / Product List)

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#1579]
Figma
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11859%3A38093&mode=design&t=dVBMpdDtmgryaufE-1
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=95%3A97&mode=design&t=dVBMpdDtmgryaufE-1

**Code**
https://next.design-system.post.ch/?path=/docs/components-card--docs
https://design-system.post.ch/#/bootstrap-samples/card

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/cards

**Comment by gfellerph** [comment]
Closing as won't implement
