### ISSUE TITLE
Component: Footer Small

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#1586]
Create Concept

**Comment by wueestd** [comment]
already exists: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=185%3A260&mode=design&t=mGeQ7btbwNVae33N-1

**Comment by gfellerph** [comment]
Created a dev task https://github.com/swisspost/design-system/issues/2656
