### ISSUE TITLE
Variant: Small floating label input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1604]
A new variant for the floating label input has been requested that has 48px height. 

Prototype: https://p9t283.axshare.com/?id=ud8t60&p=einstellungen_-_artikel

```[tasklist]
### Tasks
- [x] Create a proposal in figma
```

**Comment by wueestd** [comment]
created a branch in figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/branch/MVANE2KzNGq2et3q6T15PC/Components-Post?type=design&node-id=7779%3A34916&mode=design&t=YGbyNphH4VM1cJ3U-1

following componants have now a smaler variant:
- Text area
- text input
- select

**Comment by wueestd** [comment]
This is due to the posssibility to drag components along the height axis.

**Comment by wueestd** [comment]
@gfellerph could you look into this?

following componants have now a smaler variant:

- [ ] Text area
- [ ] text input
- [ ] select

created a branch in figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/branch/MVANE2KzNGq2et3q6T15PC/Components-Post?type=design&node-id=7779%3A34916&mode=design&t=YGbyNphH4VM1cJ3U-1

**Comment by wueestd** [comment]
Should I try to merge the figma branches? @rouvenpost  @gfellerph
