### ISSUE TITLE
Variant: Smaller switch

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1605]
A smaller switch variant has been requested that has a height of 24px.

Example: https://p9t283.axshare.com/?id=ud8t60&p=einstellungen_-_artikel

**Comment by wueestd** [comment]
check figma implementation

**Comment by wueestd** [comment]
ready for dev review: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7817%3A33913&mode=design&t=w7sPqTuO55Nf37G7-1

**Comment by gfellerph** [comment]
Looks great!
