### ISSUE TITLE
Update to Prettier 3

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1624]
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/1264
- [ ] https://github.com/swisspost/design-system/pull/1623
```

**Comment by imagoiq** [comment]
Blocked by Storybook as the transform properties is not async and this feature is not on the roadmap: https://github.com/storybookjs/storybook/discussions/24236#discussioncomment-7053590

For more information, please read the following PR: https://github.com/swisspost/design-system/pull/1623

**Comment by gfellerph** [comment]
No priority right now
