### ISSUE TITLE
Pattern request: Tel. Number Input Field

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1626]
Suggestion: https://www.figma.com/file/gOzjxKOZbkmQmp2zfdp602/Partnerportal?type=design&node-id=17912%3A74986&mode=design&t=QCoc3DaLKio2JZsa-1

Contact person: Katrin Bürger und Zignoli Claassen Desiree
possible solution: https://github.com/webcat12345/ngx-intl-tel-input

**Comment by rouvenpost** [comment]
USe this: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=185%3A13&mode=design&t=0P4Wrs6dJcpq7tmM-1

**Comment by wueestd** [comment]
@gfellerph did you ever have such a request and if yes, how did you solve it?

**Comment by gfellerph** [comment]
For now, my only input is, that any input component could be part of this "control group" pattern. Text, select, checkbox/radiobutton, (not a textarea), button (but single line only 😄). Re-assigning to @wueestd for concepting.
