### ISSUE TITLE
Tab: Visual border adjustment

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1654]
problem: the border of the active tab looks broken
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11253%3A51917&mode=design&t=GsxSZb9ZX24YsT0s-1

possible solution: 

![Image](https://github.com/swisspost/design-system/assets/20660048/8eb15c61-1f64-4a67-a44a-3d7847b1a234)

**Comment by gfellerph** [comment]
Won't do for v1
