### ISSUE TITLE
Component: Combo Input

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1668]
we have a pattern that combines different input controls dependent on each other: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=14581%3A67920&mode=design&t=6iJ3Is9lgHQB48oz-1

the idea is to have a component, with which I can put multiple selects and text inputs together:

![Image](https://github.com/swisspost/design-system/assets/20660048/dd9d1e40-92af-45d5-8615-894dac9c0a6f)
https://www.post.ch/de/briefe-versenden/briefe-schweiz

![Image](https://github.com/swisspost/design-system/assets/20660048/ee898e90-e69c-4583-ab8d-7e61ac761936)
https://places.post.ch/standortsuche?shortcut=de-standortsuche

with this component, the following exmaple should be provided: 
https://www.figma.com/file/gOzjxKOZbkmQmp2zfdp602/Partnerportal?type=design&node-id=17912%3A74986&mode=design&t=QCoc3DaLKio2JZsa-1

**Comment by gfellerph** [comment]
Closing as obsolete
