### ISSUE TITLE
create propertie guidelines

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1669]
In many components, we use different propertie names and values:

![Image](https://github.com/swisspost/design-system/assets/20660048/1f6f89d4-ccfb-4120-8aaa-1dbcf830d228)

![Image](https://github.com/swisspost/design-system/assets/20660048/cd9c0206-2333-4e9f-a16d-d228c7db3db9)

![Image](https://github.com/swisspost/design-system/assets/20660048/9123d084-2bcd-4861-8799-554cf3d8868d)

![Image](https://github.com/swisspost/design-system/assets/20660048/051a8f66-cb42-4072-8ed1-18331c0edf38)

The aim of this task is to document those properties for the consistency within designers and also between designers and devs.

**Comment by wueestd** [comment]
we discussed the properties here: https://www.figma.com/file/vaMVJ9REUj8EskXdH3beTj/Discussion-Board?type=whiteboard&node-id=117-470&t=KW0pIVlgyL9p0C5t-4

**Comment by wueestd** [comment]
descrpied a first draft here: https://www.figma.com/file/442uMtJtqZx4bATDtiQY9r/Onboarding?type=whiteboard&node-id=10-452&t=fuU8xI6y61YC8Fp0-4

**Comment by rouvenpost** [comment]
I would enhance the Breakpoints with Pixelsizes. For Example XL (>1920). Only XL can be open to interpretation and is not very helpful especially when you are new to the Designsystem.
