### ISSUE TITLE
Document how to handle language changes within Angular apps

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1676]
The default behavior of the internet header is to refirect to `?=lang=[lang_code]` when using the language switch. 

However, the header is not part of the Angular application and will therefore always redirect to the base URL.

We need to document the correct way to configure the header so that the current route is preserved when changing languages.

**Comment by gfellerph** [comment]
Closing as done (https://design-system.post.ch/?path=/docs/85d5a6b7-ac9b-4d8a-841c-72b552d0dc07--docs).
