### ISSUE TITLE
Use the same theme on all codeblock

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1677]
1. There seems to be and inconsistency between usage of dark mode on code snippet

- Example without dark mode: https://next.design-system.post.ch/?path=/docs/internet-header-getting-started--page
- Example with dark mode: https://next.design-system.post.ch/?path=/docs/getting-started-styles--page

I guess, it's easy to forget to add the `dark` attribute.

2. The dark mode is not dynamic and doesn't adapt 

This was already an issue with Storybook 6. It's usable as is, though.

3. Codeblock used within Markdown and converted (like the changelog) cannot bet set with dark theme.

4. With Storybook 7, this `dark` attribute that we use in the markdown flavor is not working anymore, and there won't be a fix for that, see https://github.com/storybookjs/storybook/pull/21626

I'm talking about this syntax:

\```scss dark
@use '@swisspost/design-system-styles/<bundle-name>.<extension>';
\```

The "new" way is to use the Source element like:

```
<Source
  code={`@use '@swisspost/design-system-styles/basics.scss';
@use '@swisspost/design-system-styles/components/alert.scss';`}
  language="css"
  dark={true}
/>
```

… but it's not really tasty to put code in attribute and it's still suffering from the first and second points.
Unfortunately, it seems there is no way to apply dark theme globally.

**Comment by oliverschuerch** [comment]
We could write code-snippets in a separate file, import the snippets into the mdx files and add it to the source blocks like so:
```mdx
// example.docs.mdx
import snippets from 'example.snippets';

<Source code={snippets.installation}/>
```

But I'm not sure this will work properly.

**Comment by imagoiq** [comment]
Request on storybook repository: https://github.com/storybookjs/storybook/discussions/23685

**Comment by imagoiq** [comment]
The fenced code snippets doesn't seem to work anymore with 7.4.0. The code snippets is not formatted, nor styled. It might be just a bug as nothing seems to be related here: https://github.com/storybookjs/storybook/releases/tag/v7.4.0

My proposal is to ditch them and use the Source markup.

We can solve the issue of setting dark on every Source markup by editing `preview.ts` and adding:

```
  docs: {
      source: {
        dark: true,
      },
  }
```

We can solve the prettier formatting issue by adding to every file a `prettier-ignore-attribute` comment, like that:

```mdx
{/* prettier-ignore-attribute (code) */}

<Source
  code={`
    @use '@swisspost/design-system-styles/index.scss';
  `}
  language="scss"
/>
```

The only thing that is left is the code snippet generated from markdown conversion like in the changelog, but in our case, we only have one code snippet like that.
