### ISSUE TITLE
Migrate the Internet-Header component stories

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1700]
The filterArgs util is not migrated yet, we need to copy & paste and update this as well.
packages/documentation/src/stories/utilities/filterArgs.ts -> packages/documentation/src/utils/filterArgs.ts

**Comment by gfellerph** [comment]
- [ ] Improve internet header docs with breadcrumbs and footer
- [ ] Re-enable breaking e2e tests for breadcrumbs and footer
