### ISSUE TITLE
Pattern Description Template in Figma

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#1717]
A Guide within Figma to explain the Usage.

**Comment by rouvenpost** [comment]
A first draft is ready in the accordion components section: 
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=14659%3A68344&mode=design&t=oFVapvjQZzkVIsXZ-1

**Comment by wueestd** [comment]
I have added some images to the Figma Button documentation and changed text to bullets: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=14830%3A84322&mode=design&t=PVxAfNFuDEyYjmMO-1

@rouvenpost what do you think about it? I would like to give Kaloyan a example

**Comment by rouvenpost** [comment]
@wueestd i made some minor adjustments... from my side it is okay.
