### ISSUE TITLE
Component: Accordeon

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#1718]
**Figma**:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=42%3A358&mode=design&t=QO3UJm1A4wNRIAvt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-accordion--docs

**Comments:**
- Review Accordions
- Rework Accordions
- Ad or update documentation

--------------------

The Focus state seem to be inconsistent. The Users might be confused. The Focus should be around the Accordeon. 
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=9989%3A50310&mode=design&t=0iMsrS70tBapsFeV-1

**Comment by rouvenpost** [comment]
Ready for Dev

**Comment by gfellerph** [comment]
@alizedebray can you check if this is already done?

**Comment by gfellerph** [comment]
Closing in favour of #3457
