### ISSUE TITLE
Stencil config: empty index files

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1721]
The internet header package has empty index files in the dist, e.g. `dist/esm/index.js` is empty safe for a link to sourcemaps.

```js


//# sourceMappingURL=index.js.map
```

The recommended package.json setup for main, module, etc. is linking to these files instead of files in the /loader folder. In order for these index files to work, they should actually export or contain the correct code.

For reference, the baloise Design System has a working setup: https://github.com/baloise/design-system/blob/main/packages/components/config/stencil.basic.config.ts (a bit more nested than our approach).

**Comment by oliverschuerch** [comment]
Fixed with #2149
