### ISSUE TITLE
Styles: update badge gap

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1739]
Implementation: https://preview-1736--swisspost-design-system-next-v7.netlify.app/?path=/docs/components-badge--docs
Design: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=10370%3A49289&mode=dev

Is:
<img width="143" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/fbab1848-9566-4034-aca6-064e76ffcb69">

Should:
![image](https://github.com/swisspost/design-system/assets/1659006/0ba26fbe-7669-486b-b01f-b70548fe1896)

Update gap between badge and text.

**Comment by imagoiq** [comment]
This issue references this comment: https://github.com/swisspost/design-system/pull/1736#discussion_r1284373244

It's
* Chrome specific
* Working when re-render the style (by toggling the display property in the devtool)
* Appears since storybook v7
