### ISSUE TITLE
Accordion: Add logo variant example

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1751]
There is a request for an accordion with logos in the title. Create examples that show how to do that with the existing accordion. Provide styles for images placed in the title content to ensure that wrong format images don't break the component.

Design: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=42%3A358&mode=design&t=XFZd0W1ixuZMDH8z-1

```[tasklist]
### Tasks
- [ ] Add a variant story to storybook v7 with logos/images in the accordion title
- [ ] Add defensive styles preventing large images from wrecking the component
```

**Comment by oliverschuerch** [comment]
@wueestd please answer our question.

**Comment by gfellerph** [comment]
@rouvenpost, @Cian77, could you add an example with a lot of text on the title (long Q&A question)?
