### ISSUE TITLE
Correctly configure prettier

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1776]
Currently, inline blocks in code snippets are not rendered correctly: 
![Image](https://github.com/swisspost/design-system/assets/33580481/12fca4f5-6af4-435b-b332-05b3114b57a8)

We need to configure prettier (in `preview.ts`) to correct the display.

**Comment by gfellerph** [comment]
- [ ] Pay special attention to the text area where floating labels won't work when the closing tag is on a new line

**Comment by gfellerph** [comment]
Closing because can't reproduce in current docs https://design-system.post.ch/?path=/docs/152b7268-cce0-43d7-b931-41a57370f9a0--docs
