### ISSUE TITLE
[Datepicker component] Set focus outline color on calendar button

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1807]
Datepicker component is missing a style for the calendar icon button (and inside the overlay) on focus and uses the default style from the browser.

On Firefox
![firefox_3CR9qYn3aj](https://github.com/swisspost/design-system/assets/12294151/2bb2f396-2e4f-4e61-aeb9-2c0863e4fb2b)

![firefox_jdxrAwQiVh](https://github.com/swisspost/design-system/assets/12294151/258c4f4a-7bb7-45d1-a78f-77314740e2f5)

On Chrome
![msedge_E7ZKjJgXnP](https://github.com/swisspost/design-system/assets/12294151/0c1fbb5f-a00b-4e7d-af71-bbe7d76a4638)

**Comment by davidritter-dotcom** [comment]
I could add the focus color for the calendar icon button and for the days inside but unfortunately I couldn't find where firefox adds its focus styles for the navigation buttons.

**Comment by imagoiq** [comment]
> I could add the focus color for the calendar icon button and for the days inside but unfortunately I couldn't find where firefox adds its focus styles for the navigation buttons.

It works with something like that: 

```
button.ngb-dp-arrow-btn:focus-visible {
  outline: forms.$input-focus-outline-thickness solid var(--post-contrast-color);
}
```
