### ISSUE TITLE
[Input component] Floating's label behavior is different when placeholder is not set or empty

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1811]
Without placeholder attribute

![image](https://github.com/swisspost/design-system/assets/12294151/01891c19-e05c-492c-9b86-9c5e801e21c3)

With empty placeholder attribute
![image](https://github.com/swisspost/design-system/assets/12294151/dc6a597e-d59f-44b1-b5cc-2a245c9ba586)

**Comment by gfellerph** [comment]
@imagoiq, this is a known limitation. The `:placeholder-shown` pseudo selector does not work if there is no placeholder specified. An empty placeholder also ensures that assistive technology does not read it twice (with the label). If you agree, you can close the ticket as won't do.
