### ISSUE TITLE
Internet Header logo animation does not work outside of an iFrame in Storybook

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1825]
I used `ArgTypes` instead of `Controls` here because currently [controls don't work on iframe demos](https://github.com/storybookjs/storybook/issues/11908), but an iframe is needed for the logo animation to work properly.

_Originally posted by @alizedebray in https://github.com/swisspost/design-system/pull/1822#discussion_r1297006984_
            

Find a solution for the header logo animation to work without an iframe or the controls to work with the iframe.

**Comment by gfellerph** [comment]
On hold until internet header stories are done ( @alizedebray please add PR number or issue)

**Comment by oliverschuerch** [comment]
Probably already fixed, check #1855

**Comment by gfellerph** [comment]
Closing as fixed
