### ISSUE TITLE
Bug(documentation): disabled select in dark mode  

### ISSUE THREAD

**Issue by b1aserlu** [swisspost/design-system#1826]
![image](https://github.com/swisspost/design-system/assets/141234680/5b00d1ad-db30-422e-977f-e5122a5a1909)

> Sometimes the disabled multiple version looks like in the picture. Not sure what we can do about that.

This is probably a bug in the dark mode (which we don't have to support right now).
Create a bug ticket where you write down the findings, and we're fine.

_Originally posted by @oliverschuerch in https://github.com/swisspost/design-system/issues/1817#issuecomment-1682158160_

**Comment by oliverschuerch** [comment]
@b1aserlu is this still a problem?
