### ISSUE TITLE
Breadcrumbs - add a config possibility to hide/remove "help"- and "contact" buttons.

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#1832]
To clarify the title, following image should help:
![dont show buttons within breadcrumb element](https://github.com/swisspost/design-system/assets/91196153/c2a6a29c-e08f-48db-be3d-f8b0c5e11030)

If they can be removed individually, or only "both or none at all", is up to you i guess? (to our requirement it would be hide "both" or "all", but of course we could hide both existing individually by config.)

I doubt that this issue conflicts with #1379, but maybe they can be done "in one go".

Thx and gratz for your practically impeccable components/design system!

**Comment by imagoiq** [comment]
@aedu-hostettler I'm not sure to understand. Why couldn't you "just" remove the elements from the config? Is it because you'll want those elements at some point, but not all the time? Do you need to toggle them? If I allow you to access those elements through CSS and ::part() would it be alright for you?

**Comment by imagoiq** [comment]
Thanks for your prompt reply. I was a bit confused as well, as I'm quite new to the project. Let me clarify what I know.

So actually, there are two configs that we can talk about. 

* The initial config is called when the web component loads. It's the "test-configuration.json" called in this example https://next.design-system.post.ch/iframe.html?id=internet-header-header-component--default&viewMode=story
It might be named differently on your project, I'm not sure. Anyway, it's where the buttons are defined.
* The custom-config prop, where you can define additional elements to the initial config.

My question was to know if you can actually change the initial config and remove those buttons directly there, which would make more sense. But I guess that you want to hide those buttons only in a specific context, like a certain page?

I'll have to discuss next week with @gfellerph as I'm not sure what is possible or not. One thing that is annoying today is that those buttons don't have any id so it's harder to hide them individually.

**Comment by imagoiq** [comment]
@aedu-hostettler Hi Adrian,
After some discussion, it appears that it's difficult to change the so-called "portal configuration". 
So I'm in the process to add a prop to be able to hide buttons (https://github.com/swisspost/design-system/pull/2027). For the moment, you'll be able to only hide all buttons or nothing. Thanks for your detailed comments.
