### ISSUE TITLE
Update text input styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1835]
Text input styles got an update. Size variants are now down to two.

**Design**: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/branch/MVANE2KzNGq2et3q6T15PC/Components-Post?node-id=7775%3A33876&mode=dev

```[tasklist]
### Tasks
- [x] Update styles for floating label and non-floating label inputs. The floating label has also a small variant now.
- [x] Update story, including the sizing section of the docs page.
```

**Comment by gfellerph** [comment]
Breaking change is now in a separate issue https://github.com/swisspost/design-system/issues/2225

**Comment by imagoiq** [comment]
Please update this line as well: https://github.com/swisspost/design-system/pull/2312/files#diff-56c2d893fe13b2907fbb6816d687553409157f45087326ee9c8104d00e842cc6R151
