### ISSUE TITLE
Add deprecation alerts for input sizes

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1847]
Alerts could be added on the demo app as well.

_Originally posted by @alizedebray in https://github.com/swisspost/design-system/pull/1837#pullrequestreview-1586860541_

**Comment by alizedebray** [comment]
The deprecation alerts should be added to both the demo and the documentation apps.

**Comment by gfellerph** [comment]
Go over https://github.com/swisspost/design-system/issues/1215 and update deprecated labels for the other deprecations as well if needed.
