### ISSUE TITLE
Small variant of controlls (checkbox and radio button)

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1861]
we decided the need for a smaller checkbox and radio buttons. due to the smaller variant of the dropdown list: https://github.com/swisspost/design-system/issues/1501

**Comment by rouvenpost** [comment]
Ready for Review

**Comment by gfellerph** [comment]
Design looks good, I created a ticket for implementation https://github.com/swisspost/design-system/issues/1916
