### ISSUE TITLE
Create checkbox- and radio-Cards web components

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1929]
In the PASE project we need to add other form-controls inside of those elements.
![image](https://github.com/swisspost/design-system/assets/9716662/59a64a51-f931-4176-bd92-e82ee1b771e9)
![image](https://github.com/swisspost/design-system/assets/9716662/f6dec3eb-169f-446d-aea3-e874296a607d)

Sadly every interaction with this elements gets blocked by the `::before` element on the surrounding label.

It would also be good to add examples in the storybook, how to add such content to the cards.

**Comment by gfellerph** [comment]
This requirement makes me wonder if we should add it as web-component for that use-case. Removing the `::before` hack reduces the click area of the card to the actual label which feels broken. With a web component, we could also get rid of the `:has` workaround requirement. The only downside is that it's a form element, which makes web component integration a little harder.

**Comment by gfellerph** [comment]
- [ ] Update figma component

**Comment by oliverschuerch** [comment]
We will add a web component for both checkbox-card and radio-card:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11857-38091&mode=design&t=UZpq9Q0mcE353GdW-0
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12335-38389&mode=design&t=UZpq9Q0mcE353GdW-0
