### ISSUE TITLE
Intranet Header: Small variant

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#1930]
There is a request from an internal application to have a "one line" intranet header variant where logo, title, navigation entries all lie on the same row.

Currently, logo and title occupy one row, navigation entries another. This, depending on the use case, costs a lot of space.

<img width="1510" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/9f4b8e53-221d-43e1-8fa0-1ca0189d7b18">

**Comment by oliverschuerch** [comment]
Refinement required!

**Comment by gfellerph** [comment]
A new custom header is in planning that will enable this behavior. ETA next year.
