### ISSUE TITLE
[Notification-overlay] Title classes get margin-top on modal with internet styles

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#1931]
When using `@use "@swisspost/design-system-styles/index.scss";` and code example from https://design-system.post.ch/#/post-samples/notification-overlay , we get unwanted margin-top with all titles:

![image](https://github.com/swisspost/design-system/assets/12294151/f0ece141-9414-4ebe-af96-6a9105c30e51)

**Comment by imagoiq** [comment]
So the issue seems present since the beginning, here is the culprit and PR: https://github.com/swisspost/design-system/blob/d69e86bce25d947913cc316476797b2f6d1283cb/packages/web-styles/src/layouts/portal/_type.scss#L53

This type for the portal style is only loaded on external apps (and so index.scss). Source: https://github.com/swisspost/design-system/blob/d69e86bce25d947913cc316476797b2f6d1283cb/packages/web-styles/src/post-portal.scss#L13

I guess this was never seen as the Notification overlays are not used on external apps? I'm not sure what is the right fix. I don't think those portal´styles should be part of the design system. @gfellerph @alizedebray @oliverschuerch what do you think?

**Comment by gfellerph** [comment]
@imagoiq I would prefer a temporary fix in the portal styles. With the next major version, typographic styles will get a complete overhaul and this theme will be refactored anyways. We're also looking at design tokens which will render these styles obsolete.
