### ISSUE TITLE
Fix sidebar/canvas toggling on small devices

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1935]
Storybook is fully responsive.
But since we changed to a docs only mode, the sidebar/canvas buttons (at the bottom of the page) are not working as expected on small devices.

Testcase:
1. open [storybook](https://next.design-system.post.ch/).
2. make your screen with smaller to see the mobile version of storybook with the bottom navigation.
![image](https://github.com/swisspost/design-system/assets/9716662/58e000c8-ed30-490d-af07-e4d458b83a21)
3. click on "Sidebar" to open the navigation.
![image](https://github.com/swisspost/design-system/assets/9716662/525180ca-d4c3-4b74-90a4-37433c8a6eea)
4. click on "Canvas" to close the navigation.
![image](https://github.com/swisspost/design-system/assets/9716662/caa781e2-107f-4e4b-b03b-e622b2afdfa0)

**Comment by imagoiq** [comment]
Will be probably fixed with Storybook 8: https://github.com/storybookjs/storybook/issues/24603
@oliverschuerch I think we can close this issue.
