### ISSUE TITLE
Update Snapshot tests

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#1943]
On the [last approved build in Percy](https://percy.io/3f971362/design-system/builds/30130861/changed/1667586142?browser=firefox&browser_ids=47%2C48%2C49&subcategories=approved&viewLayout=overlay&viewMode=new&width=1440&widths=320%2C375%2C400%2C600%2C780%2C1024%2C1280%2C1440), some snapshots were taken with an inappropriate screen size. For example, the badges snapshot shows cut out badges:

![Image](https://github.com/swisspost/design-system/assets/33580481/14dbafde-9b6a-4aaa-bb29-825849b5f497)

```[tasklist]
### Tasks
- [x] All snapshots should be revised to be in a screen size suitable for proper visual testing.
- [x] If possible, reduce the number of sizes used for the snapshots at all
```

**Comment by imagoiq** [comment]
I've checked all snapshots. For me, the only one to fix is the badge.
