### ISSUE TITLE
Component: Toast (Snackbar)

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1958]
Figma
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=156%3A232&mode=design&t=zdugunUveoM3pOfH-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=877%3A14387&mode=design&t=sPZqfB953ntQ7LZs-1

Code
https://next.design-system.post.ch/?path=/docs/components-alert--docs

https://design-system.post.ch/#/bootstrap-samples/alerts

Doc
https://www.experience-hub.ch/document/2803#/molecules-erweiterte-elemente/notifications

https://www.experience-hub.ch/document/2803#/ui-design-patterns/rueckmeldung-information-1

Similar Patterns
[Component: Alert (Banner)#1959](https://github.com/swisspost/design-system/issues/1959)
[Component: Messages / Notifications / Alert / Banner#1581](https://github.com/swisspost/design-system/issues/1581)

**Comment by wueestd** [comment]
- [ ] deprecated sheet
- [ ] clean up

**Comment by kaloyanso** [comment]
The Toast is ready and can be found here:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16818%3A1650&mode=design&t=cucOKZleLhUodEVq-1
