### ISSUE TITLE
Component: Alert (Banner)

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1959]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=156%3A232&mode=design&t=zdugunUveoM3pOfH-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=877%3A14387&mode=design&t=sPZqfB953ntQ7LZs-1

old

https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A16021&mode=design&t=n3YaFz7cRGzfAouH-1

https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A19948&mode=design&t=n3YaFz7cRGzfAouH-1

https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A20188&mode=design&t=n3YaFz7cRGzfAouH-1

**Code**
https://next.design-system.post.ch/?path=/docs/components-alert--docs

https://design-system.post.ch/#/bootstrap-samples/alerts

**Doc**
https://www.experience-hub.ch/document/2803#/molecules-erweiterte-elemente/notifications

https://www.experience-hub.ch/document/2803#/ui-design-patterns/rueckmeldung-information-1

**Similar Patterns**
[Component: Messages / Notifications / Alert / Banner#1581](https://github.com/swisspost/design-system/issues/1581)
[Component: Toast (Snackbar)#1958](https://github.com/swisspost/design-system/issues/1958)

**Comment by wueestd** [comment]
![Image](https://github.com/swisspost/design-system/assets/20660048/54deab50-429a-4d55-9ad9-842809ccf5b4)

**Comment by wueestd** [comment]
- [ ] deprecated sheet
- [ ] color variations
- [ ] clean up

**Comment by kaloyanso** [comment]
The Notificaiton Banner is ready, link here:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16818%3A3960&mode=design&t=cucOKZleLhUodEVq-1
