### ISSUE TITLE
Component: Search

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1960]
**FIgma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16739%3A53259&mode=design&t=i6IlqbsNcGrr8I6l-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A13583&mode=design&t=8fIo91pngO4uaDF5-1

**Dev**
https://next.design-system.post.ch/?path=/docs/internet-header-header-component--docs

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/search-filter

**Comment by wueestd** [comment]
@kaloyanso can you have a look at the setup please?

**Comment by wueestd** [comment]
could you review the component please @rouvenpost  :)

**Comment by rouvenpost** [comment]
@wueestd The component is approved from my side.

**Comment by wueestd** [comment]
@kaloyanso / @Cian77 the component is ready for review, thanks :)

**Comment by wueestd** [comment]
ready for dev review @gfellerph

**Comment by gfellerph** [comment]
To discuss:
- [ ] Is a disappearing placeholder icon (the magnifying glass) unique to the search or do other input fields have this feature?
- [ ] Is the clear content button unique to the search input or do other input fields have this feature?
- [ ] How exactly does the suggestion list work?
  - Does a click on the item start the search or update the value of the input box?
  - Is the icon variable?
  - How many items are displayed at max?
  - How does the list look like if it's empty?

- [ ] Consider adding the special case of track and trace results ![Image](https://github.com/swisspost/design-system/assets/1659006/ad5cd443-09eb-4288-b10e-1418b5395274)

I created the dev ticket https://github.com/swisspost/design-system/issues/2293 and added it to the component status tracker board https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=45433836.

**Comment by wueestd** [comment]
I have added the example in Figma, can we close this? @gfellerph

**Comment by gfellerph** [comment]
approved, @wueestd. I'll also create a dev ticket for the autocomplete/suggestionlist component

**Comment by wueestd** [comment]
published
