### ISSUE TITLE
Component: Progressbar

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1963]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=3230%3A74235&mode=design&t=i6IlqbsNcGrr8I6l-1

old
https://www.figma.com/file/KDAqx5qYIhMt5YnB7HJVSE/post_library_atoms?type=design&node-id=0%3A984&mode=design&t=h7jkHjB3i4bxOhVk-1
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A16331&mode=design&t=8fIo91pngO4uaDF5-1

**Code**
https://design-system.post.ch/#/ng-bootstrap-samples/progressbar

**Doc**
https://www.experience-hub.ch/document/2803#/ui-design-patterns/orientierung:65735
https://www.experience-hub.ch/document/2803#/molecules-erweiterte-elemente/loaders

**Comment by rouvenpost** [comment]
Ready for review.

**Comment by gfellerph** [comment]
Closing in favour of v2
