### ISSUE TITLE
Component: Gallery

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1964]
**Examples**

![Image](https://github.com/swisspost/design-system/assets/20660048/7796b374-a056-497e-b2f3-444b12346a7c)

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A23781&mode=design&t=8fIo91pngO4uaDF5-1

**Comment by gfellerph** [comment]
Closing as won't do in v1
