### ISSUE TITLE
Component: Autocomplete / Typeahead | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1965]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16691%3A55893&mode=design&t=UTRU4FvIZ6ZvFBGz-1

**Story book:**
No component

**Comments:**

- Reworked Design
- Added documentation

-------------

**Examples**

![Image](https://github.com/swisspost/design-system/assets/20660048/5a2e9a04-bd74-475b-97c6-5c791c54034e)

https://www.post.ch/de

**Dev**
https://design-system.post.ch/#/ng-bootstrap-samples/typeahead

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/menus:67855

**Comment by wueestd** [comment]
@kaloyanso can you have a look at the setup please?

**Comment by rouvenpost** [comment]
@wueestd look good. Only thing is the "fill to Search field" function. Not shure if the users understand this. Maybe use the Plus Icon?

**Comment by wueestd** [comment]
@Cian77 / @kaloyanso could any of you review the component and the documentation please?

**Comment by wueestd** [comment]
ready for dev review @gfellerph

**Comment by gfellerph** [comment]
- [ ] Discuss naming, it's a component intended for composition and "Autocomplete" is usually a complete component
- [ ] Resolve comments in Dos and Don'ts

**Comment by wueestd** [comment]
I have added some comments @gfellerph

**Comment by gfellerph** [comment]
@Cian77 needs a rework after the decision around border radius 0.
