### ISSUE TITLE
Component: Navigation Menu

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1966]
- [ ] Difference beteween navigation and subnavigation

subnavigation: https://design-system.post.ch/#/post-samples/subnavigation

**Figma** 
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=6467%3A29632&mode=design&t=v21xVVGydMFRQiHB-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A1&mode=design&t=KwoKUoB5Jttx8bky-1

**Comment by kaloyanso** [comment]
Hi @gfellerph,
Could you please review this component when you get the chance?

Here's the link to the space:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=6433%3A31396&mode=design&t=ICZcTGZZbwLlQ9Cs-1

We can also have a quick discussion about it, if it makes sense.
Thanks!
