### ISSUE TITLE
Component: Spinner

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1968]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16527%3A53294&mode=design&t=UhNqX9sEMKDoYiIW-1

https://www.figma.com/file/KDAqx5qYIhMt5YnB7HJVSE/post_library_atoms?type=design&node-id=0%3A989&mode=design&t=ddjqgJJN8zFcsroI-1

**Code**
https://design-system.post.ch/#/post-samples/spinner

**Doc**
https://www.experience-hub.ch/document/2803#/molecules-erweiterte-elemente/loaders

**Comment by kaloyanso** [comment]
The Spinner component is located here:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16527%3A53294&mode=design&t=Slj8iVVIDxffeqCC-1

**Comment by wueestd** [comment]
ready for dev review @gfellerph

**Comment by alizedebray** [comment]
To check: 
- [ ] sizes → currently we only have 3: xs (12px) used in buttons, sm (32px) and the default (56px) both used with an overlay
- [ ] thickness → difficult to say with the SVG but the current spinners seem to be bolder
- [ ]  speed → current spinner speed is 2s

**Comment by alizedebray** [comment]
We will increase the spead to 600ms and keep a 12px spinner for buttons.
Regarding the border width, we still have to check which size can fit the 12px spinner and then scale for all other sizes.

**Comment by kaloyanso** [comment]
Hi @alizedebray, I added a 12px size to the spinner collection. The border of it is now 2px, and it makes the smallest sizes more visible.

**Comment by rouvenpost** [comment]
Spinner is Ready for Dev.

**Comment by alizedebray** [comment]
Dev ticket created: #2445
