### ISSUE TITLE
Component: Quote

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1969]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=3390%3A18674&mode=design&t=UhNqX9sEMKDoYiIW-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=872%3A14363&mode=design&t=7PM2KakWhMGDZ1iO-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=1117%3A14716&mode=design&t=7PM2KakWhMGDZ1iO-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A20596&mode=design&t=XGSxE922I6rK1ZPd-1

**Code**
https://next.design-system.post.ch/?path=/docs/components-blockquote--docs

**Comment by gfellerph** [comment]
Closing as won't do in v1
