### ISSUE TITLE
Component: Filter

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1971]
Define different filter typs:
- filter chips
- filter bar 
- filter dialog
- ...

**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=121%3A1083&mode=design&t=i6IlqbsNcGrr8I6l-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=15%3A2655&mode=design&t=pzgyOljD1p9V76bV-1

old
Chip
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A13948&mode=design&t=8fIo91pngO4uaDF5-1

Bar 1
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A18577&mode=design&t=8fIo91pngO4uaDF5-1

Bar 2
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A11123&mode=design&t=8fIo91pngO4uaDF5-1

**Dev**
https://design-system.post.ch/#/post-samples/subnavigation

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/search-filter
https://www.experience-hub.ch/document/2803#/organisms-module/search-filter:67864

**Comment by gfellerph** [comment]
Closing as won't do
