### ISSUE TITLE
Component: Teaser

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1979]
- [ ] decide which teasers should be in the design system

**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16729%3A53258&mode=design&t=i6IlqbsNcGrr8I6l-1

POP
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=2%3A4960&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=2%3A902&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=1%3A2&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=85%3A2569&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=561%3A7172&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=562%3A8049&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=560%3A6467&mode=design&t=pzgyOljD1p9V76bV-1
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=303%3A5749&mode=design&t=pzgyOljD1p9V76bV-1

**Dev**
https://next.design-system.post.ch/?path=/docs/components-topic-teaser--docs

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/teaser

**Comment by gfellerph** [comment]
Closing as won't implement in v1
