### ISSUE TITLE
Component: Datepicker

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1982]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16545%3A53350&mode=design&t=UhNqX9sEMKDoYiIW-1

POP
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=2%3A1145&mode=design&t=7PM2KakWhMGDZ1iO-1

**Code**
https://design-system.post.ch/#/ng-bootstrap-samples/datepicker

**Doc**
https://www.experience-hub.ch/document/2803#/atoms-basis-elemente/form-inputs/datepicker-timepicker

**Comment by wueestd** [comment]
@kaloyanso handing this over to you since you are in contact with Ayline

**Comment by gfellerph** [comment]
Closing as done
