### ISSUE TITLE
Component: Hero

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1983]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=136%3A1312&mode=design&t=i6IlqbsNcGrr8I6l-1

POP
https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=2%3A6623&mode=design&t=pzgyOljD1p9V76bV-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A6747&mode=design&t=8fIo91pngO4uaDF5-1

**Comment by gfellerph** [comment]
Closing as won't do in v1
