### ISSUE TITLE
Bug: Design-system css adds duplicated close-button to ngx-toastr

### ISSUE THREAD

**Issue by mkeller1992** [swisspost/design-system#1989]
When I use ngx-toastr together with swisspost-design-system, it seems like the latter adds an additional exit-button via ::before tag (see also screenshot below):

![duplicated_close_button](https://github.com/swisspost/design-system/assets/27359653/5b3e5162-4ddd-4a25-800a-4cbaf3a59742)

**I'm using:**
- Angular 16.2.0
- ngx-toastr 17.0.2
- @swisspost/design-system-styles 6.4.0

In **app.module.ts** I defined the following import:

`
ToastrModule.forRoot({
	timeOut: 0,
	extendedTimeOut: 0,
	closeButton: true,
	preventDuplicates: true
}),
`

In **styles.scss** I added:
`
@import 'ngx-toastr/toastr';
`

![alerts](https://github.com/swisspost/design-system/assets/27359653/f0a0a0a7-0b65-4bd1-848b-aa0ebe6c5250)

**Comment by alizedebray** [comment]
Hello @mkeller1992,

Thank you for bringing this issue to our attention. A similar problem has been reported in ticket #1946, and our team is currently working on resolving it. To keep our issue tracking organized, I'll be closing your ticket as a duplicate.

Additionally, I noticed that your Toastr configuration is incomplete. To ensure that the toasts align with the Design System styles, please make sure to include the `toastClass` property:

```
ToastrModule.forRoot({
    toastClass: 'toast', // <= this property is missing in your configuration
    timeOut: 0,
    extendedTimeOut: 0,
    closeButton: true,
    preventDuplicates: true
})
```
If you have any further questions or need assistance, please feel free to contact us via our [Support channel](https://teams.microsoft.com/l/channel/19%3ae7fa68fb13eb40b4bf4604edea5f4b3e%40thread.tacv2/%25F0%259F%259A%2591%2520Support?groupId=123c7c9e-052a-40e6-98d3-6cc6d46bad0a&tenantId=3ae7c479-0cf1-47f4-8f84-929f364eff67).
