### ISSUE TITLE
User-Icon is not loading within intranet header

### ISSUE THREAD

**Issue by riscie** [swisspost/design-system#1995]
Hi swisspost design system team

With the newest version of swiss post design system, we currently have the issue, that the user image within the intranet header is not loading.

![image](https://github.com/swisspost/design-system/assets/5127581/28bb7a95-3251-4788-bdf2-9f384ce539a4)

It seems to be a CORS issue.
![image](https://github.com/swisspost/design-system/assets/5127581/88ae21e7-c760-42da-90f2-1a6e85118d48)
![image](https://github.com/swisspost/design-system/assets/5127581/e6ee7239-0d63-44a9-b6d9-84c4af2d9a6a)

When I manually open the link to the image in a new tab, the image is loaded.

Any feedback / help is appreciated.

**Comment by riscie** [comment]
Hi @alizedebray. Regarding your label. We have this problem with the **intra**net-header, not sure if it's also occurring with internet-header.

**Comment by riscie** [comment]
@alizedebray I took some time and skimmed the code.

To me, it looks like [this check ](https://github.com/swisspost/design-system/blob/64467728b624ce27edee9e53be4205a34a724ea6/packages/components-angular/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts#L329) is wrong. We are only checking for null, but the default value of the string is an empty-string. 

If I see this correctly, after fixing this if-check, the image should take the hardcoded base64 string from user.ts.

Let me know if you want me to create a PR, I am happy to help.

**Comment by mkeller1992** [comment]
We have the exact same problems in our apps actually. I hope this issue will be taken care of soon.

**Comment by riscie** [comment]
Any news on this? @alizedebray

**Comment by alizedebray** [comment]
@riscie Thanks for your inputs, I just merged the changes you suggested which should help with the default user image being displayed correctly. The fix should be release in the coming week.

However, you might still encounter CORS errors with actual user images. I created another ticket to track this issue: #2173.

**Comment by riscie** [comment]
Thank you @alizedebray 
I will try to make some tests with the new version this week.

**Comment by riscie** [comment]
It works with the default user image @alizedebray.
