### ISSUE TITLE
Grid: full width

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1997]
![Image](https://github.com/swisspost/design-system/assets/20660048/964e5bc9-1d80-4fec-8abf-fcaa4126429d)

**Comment by wueestd** [comment]
documented here: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations-Post?type=design&node-id=2203%3A2461&mode=design&t=uyrVFluMGxrAXUZv-1

**Comment by oliverschuerch** [comment]
@wueestd I added some coments in your Figma file. If you need me to do something else with this ticket, please tell me.
