### ISSUE TITLE
Component: Anchor Menu

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2002]
**Example**
https://www.post.ch/de/geschaeftsloesungen/digital-commerce

**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16691%3A55892&mode=design&t=v21xVVGydMFRQiHB-1

https://www.figma.com/file/Uwug646a2z3s5Qwa2CZ4vV/POP-Design-System?type=design&node-id=836%3A16416&mode=design&t=8tUB1a0VaZoIH4bC-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A17119&mode=design&t=KwoKUoB5Jttx8bky-1

**Doc**
https://www.experience-hub.ch/document/2803#/organisms-module/anchors

**Comment by gfellerph** [comment]
Closing as duplicate of navigation tree https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=30601-3391&t=5DH3s1jvkkO9QdgQ-0, #2277
