### ISSUE TITLE
Component: Megadropdown

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2003]
**Example**
https://www.post.ch/de

**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=1897%3A55625&mode=design&t=v21xVVGydMFRQiHB-1

old
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A1&mode=design&t=KwoKUoB5Jttx8bky-1

**Dev**
https://next.design-system.post.ch/?path=/docs/internet-header-header-component--docs

**Comment by gfellerph** [comment]
- [ ] Settle on the name. Flyout or megadropdown?
