### ISSUE TITLE
Fix internet header search input on Safari

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2006]
The placeholder of the internet header search input is not fully visible on Safari desktop: 

![Image](https://github.com/swisspost/design-system/assets/33580481/5b8a3b07-d71a-4a86-81fb-cc6efec862f7)

**Comment by gfellerph** [comment]
I can't reproduce this on v1.11, only on 1.8.2 (which is used by the post portal). @josemanosalvas can you update?

**Comment by imagoiq** [comment]
Fixed as post portal update with latest version of internet-header.
