### ISSUE TITLE
Variants: Define States for Validation

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2025]
In Figma we define Sucess and Error as State. But in Code it is actually defined as Validation.

**Desgin**
State:

- Default
- Hover
- Success
- Error
- Focus
- Disabled

**Dev**
State:
- Default
- Hover
- Focus
- Disabled

Validation:
- Default
- Sucess
- Error

![Image](https://github.com/swisspost/design-system/assets/20660048/9c4ea16f-c602-4049-84c1-f1412a06edd8)

This leads to the situation that a lot of states have no design: 

![Image](https://github.com/swisspost/design-system/assets/20660048/28d91aa8-263d-4065-9f98-1377a9656114)

Since we don't want to implement all this different variations in Fimga, we decided to create global guidelines:

- [ ] create guidelines for missing states

**Comment by gfellerph** [comment]
- [ ] @Cian77 check if this is consistent with docs in Wiki

**Comment by gfellerph** [comment]
no longer relevant
