### ISSUE TITLE
Table Component: add Mono variant

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2051]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=13296-61817&mode=design&t=IrOKEs6RNrRPXgLH-0

![image](https://github.com/swisspost/design-system/assets/12294151/2cb8de0c-67b3-4032-92e0-599d1136ff0c)

**Comment by gfellerph** [comment]
Assigning to Loïc because he's already done it in a project.
