### ISSUE TITLE
Set up sourcemaps for storybook

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2053]
When inspecting styles in storybook, all styles originate from the same, compiled CSS file which is not really helpful for debugging.

<img width="455" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/cce663fa-523e-4f56-9e0d-4505cf28e715">

Can we set up source mapping for storybook to see what sass file stuff is coming from?

**Comment by imagoiq** [comment]
Note sure if it's possible: 

https://github.com/storybookjs/storybook/issues/19464
https://github.com/storybookjs/storybook/issues/9901#issuecomment-1581813924

**Comment by imagoiq** [comment]
I've found this issue: https://github.com/vitejs/vite/issues/2830 (and this related documentation: https://vitejs.dev/config/shared-options.html#css-devsourcemap)
CSS sourcemap aren't built by default with Vite. At the moment, you can only build them in dev mode.
