### ISSUE TITLE
Be able to define form size variant in body for all components

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2075]
Eventually, I think it would be nice to just define `<body class="small/intranet">` and every component inherits font sizes and acts accordingly. It's not quite developer friendly to have to specify on every single element that you want small variants.

_Originally posted by @gfellerph in https://github.com/swisspost/design-system/pull/2067#discussion_r1358300619_

**Comment by gfellerph** [comment]
Discussion points:
- Should we use our outputs to differentiate or a class?
- Is there a use case to mix big and small component variants on the same page?
- Can we use mixins?

**Comment by gfellerph** [comment]
Closing as out of scope.
