### ISSUE TITLE
Alert doesn't show code for icon by default

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2088]
![image](https://github.com/swisspost/design-system/assets/12294151/f3b39f6c-b3fd-4c8b-9dd6-e5ca91044d6a)

An icon is displayed, but the source code doesn't include the icon. The Description of the "prop", "The icon to display in the alert. By default, the icon depends on the alert type.", suits web components, but not standard HTML as switching the type class will not change the icon.

**Comment by gfellerph** [comment]
Closing as fixed
