### ISSUE TITLE
Internet-header menu item focus is obscured

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2097]
![UUA2npJ90S](https://github.com/swisspost/design-system/assets/12294151/c7a2e1e0-bcb7-4e08-af18-6cfc2e847384)

Similarly to https://github.com/swisspost/design-system/issues/2007, the focus style is partially obscured.
It is compliant with [2.4.11 Focus Not Obscured AA](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum) but not [2.4.12 Focus Not Obscured AAA](https://www.w3.org/TR/WCAG22/#focus-not-obscured-enhanced).

**Comment by davidritter-dotcom** [comment]
Test it on live post portal site, since it is not reproducible in storybook.
