### ISSUE TITLE
Tooltip Web Component leaks CSS Custom properties

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2099]
The tooltip web component is leaking a lot of CSS custom properties that are not used. Also, we shouldn't declare CSS custom properties value directly inside the scoped CSS of the web components, but rather used those variables provided by the page.

![idea64_9SRWrMx5MM (Personnalisé) (1)](https://github.com/swisspost/design-system/assets/12294151/65659573-8842-4ce5-8a74-80a613c7b2e8)

**Comment by gfellerph** [comment]
Fixed by #2109

**Comment by gfellerph** [comment]
Discuss color inheritance
