### ISSUE TITLE
Alerts: fix switch between default and custom icon

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2105]
> there is a weird flash switching between icons on the two last elements of each color group. Can you have a look?

https://github.com/swisspost/design-system/assets/12294151/f3359b6d-eafc-48f2-9454-996c7a0971bf

_Originally posted by @imagoiq in https://github.com/swisspost/design-system/issues/2094#issuecomment-1770542649_

**Comment by gfellerph** [comment]
Possibly a timing issue, try to hide the bell if there is a post-icon in the alert.
