### ISSUE TITLE
Define critical dependencies as peerDependencies

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2108]
In order to prevent incompatible dependency combinations for projects using either caret dependencies (^1.x.x) or renovate, we need to specify `peerDependencies` for the styles package for:

- ng-bootstrap (and therefore Angular, implicit or explicit?)
- Bootstrap

This will ensure that a project does not upgrade to an unsupported version of Angular or tries to use the Design System Styles with an old version of Angular.

https://blog.domenic.me/peer-dependencies/

_Issues like these are a strong reason for becoming independent of those frameworks as much as possible._
```[tasklist]
### Tasks
- [ ] https://github.com/swisspost/design-system/issues/2232
```

**Comment by alizedebray** [comment]
Currently the styles package have a dependency to Angular 15: the schematics use several functions from @angular/core/schematics/utils that are no longer published as of @angular/core@16.

However @ng-bootstrap/ng-bootstrap@15 has @angular/core@16 as a peer dependency.
This means that if we add ng-bootstrap as a peer dependency of the styles we get the following error that we cannot fixed: 
![Image](https://github.com/swisspost/design-system/assets/33580481/a48cb190-23ad-4f9e-958e-e58fb5c7fc7e)

Before adding ng-bootstrap as a dependency of the styles package, we therefore need to find a way to move the schematics to @angular/core@16.

**Comment by gfellerph** [comment]
Temporary resolution: move migration code to a separate package (breaking the current functionality) to unblock this issue. With new supported frameworks, a new way of providing migration scripts needs to be found and this temporary move will give us some more time before we start working on v7.
