### ISSUE TITLE
Foundations: Update colors

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2111]
add the two defined focus colors:
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=17916%3A13264&mode=design&t=OH4YdtLWSh9tbZir-1

**Comment by wueestd** [comment]
also added some signal background colors: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations-Post?type=design&node-id=2215%3A13427&mode=design&t=OwYrBbKf15n8y3r4-1

**Comment by wueestd** [comment]
@gfellerph could you please review the colors? :)

**Comment by gfellerph** [comment]
Approved @wueestd, I created the ticket https://github.com/swisspost/design-system/issues/2127

**Comment by wueestd** [comment]
@rouvenpost for your information, I have added the focus colors and the signal background colors to the foundations
