### ISSUE TITLE
Components: grey state

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2113]
the following patterns must work on white or grey background:
- Accordeon (https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=42%3A358&mode=design&t=sY6kNWfAk4IzFeTP-1)
- List Elements (https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=61%3A371&mode=design&t=sY6kNWfAk4IzFeTP-1)
- Tabs (https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11253%3A51917&mode=design&t=sY6kNWfAk4IzFeTP-1)

**Comment by wueestd** [comment]
naming convention: in case of grey variant indicate with (grey) e.g. Accordeon (grey)


![Image](https://github.com/swisspost/design-system-planning/assets/20660048/0c670b6a-5af0-422a-8518-ed97079824ae)

**Comment by gfellerph** [comment]
Closing as done. Accordion is done, tabs is done, lists are in progress.
