### ISSUE TITLE
Invalid input number displays an icon even when the width is too small for content

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2119]
https://github.com/swisspost/design-system/assets/12294151/5aaac88b-dffe-4342-9c5e-f6760b7acbff

For the context (the error icon has been disabled temporarily):
![image](https://github.com/swisspost/design-system/assets/12294151/0aaf3cdf-4097-4bf4-9081-289bf4e705b6)

**Comment by gfellerph** [comment]
- This could be a input group, validation should be done at group level, but displaying the icon there requires custom code
- Discuss with UX
- Multiple requests because of big error icons

**Comment by imagoiq** [comment]
I'm wondering if this icon is really necessary. In practice, we should have a validation message (not like in this video). So we have an element indicating that's something is wrong for colour-blind people. Gov.uk seems to follow this way: 
https://design-system.service.gov.uk/components/error-summary/
https://design-system.service.gov.uk/components/text-input/#error-messages

**Comment by imagoiq** [comment]
Result of discussion in the "Design System Patterns Discussion" meeting of today: have a UX look at the use case, it's possible that the use case can be improved without changing the pattern.
