### ISSUE TITLE
Documentation: Clarify how to group buttons together?

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2120]
To be discussed on triage. Devs are expecting that buttons would be on the same line without a wrapping element with `d-flex` class. Worth an example?

![firefox_SS9ZjoG2tp](https://github.com/swisspost/design-system/assets/12294151/87a6095e-995e-4fc7-bd8c-88c6a25c81ff)

**Comment by gfellerph** [comment]
- Create an example in the button story on how to place buttons next to each other in a flex context, also show how to re-order them (https://design-system.post.ch/#/post-samples/forms)
