### ISSUE TITLE
Component: divide Popover

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2125]
**Popover**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18199%3A6302&mode=design&t=tKgyiB6TDkqu9sYU-1

**Comment by wueestd** [comment]
Ready for dev review :)

**Comment by gfellerph** [comment]
There is already a preview of this component available here: https://preview-2109--swisspost-design-system-next.netlify.app/?path=/docs/components-popover--docs

To discuss:
- Default positioning
- Dev: update paddings
- Resolve comments in figma

**Comment by wueestd** [comment]
comments resolved
