### ISSUE TITLE
E2e tests are failing

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2139]
The e2e tests are failing.

![image](https://github.com/swisspost/design-system/assets/9716662/02733937-513d-43a6-a3d2-e0da3c05ee71)

Run `pnpm e2e` from the root of the monorepo to reproduce.

I found some possible solutions here: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.

- Downgrading to node 16 could do the trick (not recommended).
- On the other side I tryed to set the following env in my powershell console `$env:NODE_OPTIONS = "--openssl-legacy-provider"` and the above error disabpeard.

**Comment by gfellerph** [comment]
@oliverschuerch, re-evaluate and check cypress download mirror.

**Comment by oliverschuerch** [comment]
Its working with the cypress download mirror!
