### ISSUE TITLE
Header: add settings link to B2B login widget

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2141]
The login widget shows a settings link for B2C users, but not for B2B.

B2C:
![image](https://github.com/swisspost/design-system/assets/1659006/87902d7a-fd2b-4b69-b31b-fd5f3436a439)

B2B:
![image](https://github.com/swisspost/design-system/assets/1659006/c0282ae5-502f-4cc2-b4b1-7c3f06057017)

This link is added here https://github.com/swisspost/design-system/blob/fba0a91d20f66ba6471233d43c42f579875d40ba/packages/internet-header/src/assets/js/klp-login-widget.js#L1205, but it's restricted to B2C customers. Add a similar link to the B2B menu.

The link should point to https://service[env].post.ch/kvm/app/ui/settings?lang=[lang]

**Comment by alizedebray** [comment]
> The link should point to [https://service[env].post.ch/kvm/app/ui/settings?lang=[lang]](https://service%5Benv%5D.post.ch/kvm/app/ui/settings?lang=%5Blang%5D)

This seems to be the same URL as for the B2C settings: https://github.com/swisspost/design-system/blob/fba0a91d20f66ba6471233d43c42f579875d40ba/packages/internet-header/src/assets/js/klp-login-widget.js#L1195
