### ISSUE TITLE
Docs: Titles should be deep-linkable

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2158]
It should be possible to deep link to specific titles/sections in the docs. That's usually achieved by putting ids on all titles and some functionality to copy the deeplink. See https://github.com/swisspost/design-system/blob/main/CONTRIBUTING.md#accessibility for an example.

Is there a setting or plugin in storybook to achieve this?

**Comment by oliverschuerch** [comment]
See the following links:
https://storybook.js.org/docs/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm
https://github.com/remarkjs/remark-gfm
