### ISSUE TITLE
Upgrade eslint config with flat config and es module

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2167]
Our current way to handle config in eslint is deprecated and should be upgraded: https://eslint.org/blog/2023/10/flat-config-rollout-plans/

```[tasklist]
### Tasks
- [ ] Replace config with new `eslint.config.js` and convert to es module
- [ ] Replace `___dirname` from node to es module alternative
```

**Comment by imagoiq** [comment]
Following [Guide for migration](https://eslint.org/docs/latest/use/configure/migration-guide#eslint-env-configuration-comments), I initialized the work with the branch: https://github.com/swisspost/design-system/tree/chore/2167-eslint-flat-config

But most of the eslint packages, that we use, do not support the new config yet:
* [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/7694)
* [stencil-eslint](https://github.com/stencil-community/stencil-eslint)
* [angular-eslint](https://github.com/angular-eslint/angular-eslint/issues/1280#issuecomment-1533531418)

**Comment by oliverschuerch** [comment]
We'll need to update to eslint v9, but not every dependency is ready to do this now.
