### ISSUE TITLE
CORS policy blocks user image in the intranet header

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2173]
The user images rendered in the intranet header are served by web.post.ch without an Access-Control-Allow-Origin header.
The intranet applications that use the header can also set Content-Security-Policy to allow accessing images from certain origins.

To avoid the user image being blocked by CORS policy, we have to investigate and document this two possibilities: 
- adding web.post.ch as a image-src in the  Content-Security-Policy
- contacting the web.post.ch team and ask them to add an Access-Control-Allow-Origin header to the images

**Comment by alizedebray** [comment]
The team responsible for the web.post.ch is now aware of the issue and a ticket has been opened for them to add an `Access-Control-Allow-Origin` header on the images.

**Comment by gfellerph** [comment]
External ticket was created. Closing this ticket.
