### ISSUE TITLE
Update exposed scss variables for grid docs

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2174]
We need to update the exposed scss variables in the grid docs, because the gutter-width is now a map and the value changes dependant to the breakpoint.

Check if other variables need to be updated as well.

Update the docs page so that all currently used variables are documentet like the others already are at the moment.

**Comment by gfellerph** [comment]
- [ ] Use a changeset to inform users about deprecated vars

**Comment by b1aserlu** [comment]
already done
