### ISSUE TITLE
Component: Buttons  | Positive & Negative

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2178]

**Comment by Cian77** [comment]
- Ad missing Styles
- Ad Font Styles from Foundations
- Finalize documentation

**Comment by Cian77** [comment]
Hi @rouvenpost to finalize the component, we need to add the label to the foundations with a strike-through for the disabled buttons. Then I think we will also need to talk about motion and also document, what the rules are.

**Comment by gfellerph** [comment]
To discuss:

- [ ] Focus background color on negative buttons
