### ISSUE TITLE
Component: Checkbox  | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2179]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7750%3A33879&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-checkbox--docs

**Comments**
- Design Update
- Font Update (Foundation)
- A11Y-Update
- Added Documentation

**Comment by Cian77** [comment]
Hallo @rouvenpost, please review the Checkbox, thanks.

**Comment by rouvenpost** [comment]
I added some clarification to the Documentation. It should be imediatly clear that there are two Sizes of the Checkbox: Default and Small.

**Comment by rouvenpost** [comment]
Design is approved.

**Comment by Cian77** [comment]
Hi Philipp, this component is ready for a review. Thanks for your feedback.

**Comment by gfellerph** [comment]
@Cian77 I created the dev ticket https://github.com/swisspost/design-system/issues/2525 and updated the component status tracker https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=14031687
