### ISSUE TITLE
Component: Dropdown | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2181]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=134%3A1328&mode=design&t=fiQFgnfbEVwd8vxW-1

Story Book:
TBD

**Comments:**
- Review component
- Rebuild component
- Ad documentation

**Comment by gfellerph** [comment]
Closing in favour of v2 #3453
