### ISSUE TITLE
Documentation: Rating

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2186]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12038%3A38032&mode=design&t=zJsCfjamR0qblDLe-1

**Story Book:**
TBD

**Comments:**
- built new component
- added documentation

**Comment by oliverschuerch** [comment]
Code implementation has already been done with #2411 
@rouvenpost or @Vandapanda please update the States in Figma.
