### ISSUE TITLE
Component: Radio Button | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2187]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7777%3A33876&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-radio-button--docs

Comments:
- Design Update
- Font Update (Foundation)
- A11Y-Update
- Added Documentation

**Comment by Cian77** [comment]
Hi @rouvenpost, the radio button component is also ready for review. I added the topics you mentioned in the checkbox. Thanks.

**Comment by rouvenpost** [comment]
Design is ready for Dev

**Comment by Cian77** [comment]
Hi Philipp, this component is also ready for a review.

**Comment by gfellerph** [comment]
@Cian77 I created the dev ticket https://github.com/swisspost/design-system/issues/2526 and updated the status tracker https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=14097696. Close this at your convenience.
