### ISSUE TITLE
Component: Radio Button Card | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2188]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=12335%3A38389&mode=design&t=Czazc5TyV7SLqlrt-1

**Story Book:**
https://preview-2260--swisspost-design-system-next.netlify.app/?path=/docs/components-forms-radio-button-card--docs
https://preview-2260--swisspost-design-system-next.netlify.app/?path=/docs/886fabcf-148b-4054-a2ec-4869668294fb--docs

**Comments:**
- Review Component
- Ad Documentation

**Comment by rouvenpost** [comment]
@Cian77 i prepared the Radio Cards. Can you have a look at it? With special emphasis on the Focus State? Not shure if it is correct.

**Comment by Cian77** [comment]
@rouvenpost I have had a look at the component and have following my comments:

- I think we should keep to the states as defined: I changed active to selected
- From usability perspective, we should decide how to switch between positive and negative, so it's always the same.
- By the Checkbox component we added a group, do we want to have this with this component?

**Comment by rouvenpost** [comment]
i added the Error Message to the Goup Component.

**Comment by rouvenpost** [comment]
Design is ready for Review

**Comment by oliverschuerch** [comment]
Looks ok to me.
Nice job!
