### ISSUE TITLE
Documenation: Table

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2189]
**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=134%3A2134&mode=design&t=KbQoNAUqKR9mayrQ-1

**Storybook**
https://next.design-system.post.ch/?path=/docs/components-table--docs

**Comment by oliverschuerch** [comment]
@Vandapanda please reasign the ticket to me as soon as you think you're done ;)

**Comment by gfellerph** [comment]
Closing as irrelevant
