### ISSUE TITLE
Component: Text Input | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2191]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7775%3A33876&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-input--docs

Comments:
- Updated the complete component as there were quite many issues
-  Added Focus State
- Updated new Disabled State
-  Added Documentation

**Comment by Cian77** [comment]
Ad Focus State and check on colours

**Comment by Cian77** [comment]
Hi Philipp & Rouven, the component is ready for review. By the Checkbox component, I also added the documentation for the small size. Should I do that in the same way in this component? Thanks for your Feedback.

**Comment by rouvenpost** [comment]
@Cian77 is okay from my side

**Comment by gfellerph** [comment]
To discuss (see comments in figma):
- [ ] Naming (Text input or Input)
- [ ] Label boldness

**Comment by gfellerph** [comment]
Looks good, added dev ticket https://github.com/swisspost/design-system/issues/2527
