### ISSUE TITLE
Component: Text Area | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2192]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7779%3A34916&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-textarea--docs

**Comments:**

- Connected Font Styles from Foundations
- Added Focus State
- Updated Disabled State A11Y
- Added Documentation

**Comment by Cian77** [comment]
- Ad Focus and check on colours
- Ad documentation

**Comment by Cian77** [comment]
Hey Philipp & Rouven, one more Component to be reviewed :)

**Comment by rouvenpost** [comment]
@Cian77 Pattern is ready for Dev

**Comment by gfellerph** [comment]
@Cian77 I updated the dev ticket https://github.com/swisspost/design-system/issues/1055. The design looks good to me.
