### ISSUE TITLE
Documentation: Switch | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2193]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7777%3A33877&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-switch--docs

Comments:
- Added new Disabled State
- Added Font Style
- Added Documentation

**Comment by Cian77** [comment]
Hi Rouven and Philipp, the switch is ready for review. Thanks for your Feedback :)

**Comment by rouvenpost** [comment]
@Cian77 Pattern is ready for Dev

**Comment by gfellerph** [comment]
@Cian77 I updated the already existing ticket https://github.com/swisspost/design-system/issues/853. The design looks good to me.
