### ISSUE TITLE
Component: Select | Positive

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2194]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7802%3A33963&mode=design&t=VnF7Nfba4zszs6Kt-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-forms-select--docs

**Comments:**

- Updated the complete component as there were quite many issues
- Added Focus State
- Updated new Disabled State
- Added Documentation

**Comment by Cian77** [comment]
- Ad Focus state and check colours
- Ad documentation

**Comment by Cian77** [comment]
Hi Rouven & Philipp, this component is also ready for a review.

**Comment by rouvenpost** [comment]
@Cian77 Pattern is ready for Dev
