### ISSUE TITLE
Create e2e tests for angular component PostAlert

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2216]
- [ ] Translate tests from packages/components/cypress/e2e/alert.cy.ts
- [ ] If the above file does not exist, we need to define and add tests there too

**Comment by gfellerph** [comment]
@oliverschuerch, it might not be worth to write the exact same test but rather test the angular wrapper. The web component functionality is already tested but we need to test how props are passed and events fired etc.

**Comment by gfellerph** [comment]
Closing as won't implement, basic tests are in place.
