### ISSUE TITLE
Drop the @angular/core@15 dependency from the styles schematics

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2232]
Currently, the style schematics use functions and classes imported from @angular/core@15: 
![Image](https://github.com/swisspost/design-system/assets/33580481/5e9746dd-5126-4f87-8c48-2cc69aa8532e)

This dependency to an old Angular version is far from ideal and prevents use for having ng-bootstrap as a peer dependency on the styles package as required in #2108 

This ticket aims to find a way to write the schematics without those old function and classes.

**Comment by gfellerph** [comment]
Closing as not needed anymore.
