### ISSUE TITLE
Input text: add an official way to add static or interactive icons appended inside the input

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2248]
For example a search icon is often added to filter forms:
![firefox_YVH0wtzGTE](https://github.com/swisspost/design-system/assets/12294151/e2c73ae5-a612-41a2-9695-6235a5c08b52)

TBD: [in the internet-header, it is used as a button](https://next.design-system.post.ch/?path=/docs/internet-header-header--docs). How to differentiate both? Should we allow icons to be append to input?

**Comment by gfellerph** [comment]
@imagoiq have a look at https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16739%3A53259&mode=design&t=uFqiwSCwgBx3yCuO-1. This will be the new search field.

Another approach would be adding the generic possibility to add pre- and postfixes to input fields (https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=10657%3A50263&mode=design&t=uFqiwSCwgBx3yCuO-1).

The datepicker is a similar use case.

- [ ] refine with the Design Team

**Comment by gfellerph** [comment]
Design is ready

**Comment by gfellerph** [comment]
- [ ] check for accessibility support and `<input type="search">`

**Comment by gfellerph** [comment]
Closing in favor of #3351
