### ISSUE TITLE
Buttons: conflict between `btn-block` and `btn-icon`, `btn-animated`

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2249]
In some project, users are adding classes such as `btn-block-md` on button to make them use the available width space. This is the recommended way from boostratp documentation: https://getbootstrap.com/docs/5.3/components/buttons/#block-buttons
But this also breaks the gap between the icon and the text as it adds a `display:block`

e.g. 

![firefox_rCUwhWx4HX](https://github.com/swisspost/design-system/assets/12294151/71f3bb02-1477-453a-9931-3ebf530e85e0)

**Comment by gfellerph** [comment]
- [ ] Check why these styles are available, since we're not exporting bootstrap styles for the button.
- [ ] Think about how to export the responsive classes with the Design System (there are projects importing both Bootstrap and the Design System)
