### ISSUE TITLE
Fix internet-header getting-started cdn examples

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2250]
The CDN examples contain wrong HTML and should be fixed.
https://next.design-system.post.ch/?path=/docs/internet-header-getting-started--docs

**Comment by gfellerph** [comment]
![Image](https://github.com/swisspost/design-system/assets/1659006/b15d2e4f-e72a-4ccf-b77c-b9552c46674d)

**Comment by gfellerph** [comment]
- [ ] #2255
