### ISSUE TITLE
Designers Survey 2023

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#2275]
https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=ecTnOvEM9EePhJKfNk7_Zw3gapEzOYpKmiJGFAsZ1mxUN002WTkySE4zNkRCRDZOUVJNMUtDSUEwVy4u

**Comment by rouvenpost** [comment]
Question 5: 

5.Do you use the Swiss Post Design System or the Common Web Frontend (CWF)?Antwort erforderlich. Einzelauswahl. 
• Yes
• No
• I don't know

My Proposal:
• SPDS
• CWF
• I do not use any of those

**Comment by wueestd** [comment]
Thanks, survey is out 👍
