### ISSUE TITLE
Component: Popover | Positive

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2302]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=18199%3A6302&mode=design&t=UTRU4FvIZ6ZvFBGz-1

**Story Book:**
https://next.design-system.post.ch/?path=/docs/components-popover--docs

**Comments:**

- Adjusted font size to 16px Title and Body
- Added the Link as this is used often
- Added min and max width
- Added Eelevation 3
- Updated the documentation

------------------------------------

After implementing the popover, some questions came up:

<img width="787" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/60037e31-6e33-4644-a2c3-61d61166ed65">

- [x] If there is only one line of text, the close icon is not centered
- [x] The 14px text looks too small compared to the rest of the text which is 16px (looks good in design, but not in context)
- [x] None of the examples in the design span the max width that a popover can have which is 1440px * 0.66 = 950px (2/3 of max container width), the examples seem to have a max width of 240px
- [x] In code, the popover will take 100% of the available width below 600px screen size

**Comment by Cian77** [comment]
Hi @gfellerph and @rouvenpost, please review the component.

**Comment by rouvenpost** [comment]
@Cian77 this looks good from my side

**Comment by gfellerph** [comment]
Created the dev ticket https://github.com/swisspost/design-system/issues/2622.

- [ ] Resolve comments in figma
