### ISSUE TITLE
Add accessibility to Pagination items

### ISSUE THREAD

**Issue by DanielRadovanovic** [swisspost/design-system#2331]
Hi,
I am part of a team that is developing applications for the swiss post. As we were integrating accessibility we encountered an issue with the pagination item that you provide:
![image](https://github.com/swisspost/design-system/assets/152501224/b65c60b5-2e91-4351-89f3-cf9baf6bb1a9)

In normal mode it looks legit but having users who need the high contrast mode, they are not able to see on which page they are currently at:
![image](https://github.com/swisspost/design-system/assets/152501224/baabedd5-0f88-4c99-baf4-4137657a65fa)

As you can see, it is not represented in any color... Also the left- and right-chevrons are not really visible.

It is for the following Post-Design Element:
https://swisspost-web-frontend.netlify.app/#/ng-bootstrap-samples/pagination

Here is an example for a possible approach and how we used to solve it in our part of the system:
![image](https://github.com/swisspost/design-system/assets/152501224/e0c4efea-fc42-4bff-be78-09399cddeb5f)

If there are any further questons, please feel free to reach out to me.

Many Thanks and kind regards

Daniel

**Comment by gfellerph** [comment]
Thanks for taking the time to submit the issue and also providing a fix, that's awesome. We'll have a look at it.
