### ISSUE TITLE
ngb-modal no longer scrolable

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2361]
Modals with long content is no longer scrollable: 

Now:
![Image](https://github.com/swisspost/design-system/assets/33580481/a1c9c17f-fd85-40b9-8d46-79be35213d1b)

Before:
![Image](https://github.com/swisspost/design-system/assets/33580481/c12ad9c7-35a8-4095-ac4f-cd8c3f9abd4a)

**Comment by gfellerph** [comment]
Implementation from ng-bootstrap, current state and design diverge. Decide which direction to go with this.

**Comment by oliverschuerch** [comment]
@Cian77 and @kaloyanso can you have a look on this and decide how we should implement the scrollbar in the modal.
If there are questions, please contact one of the @swisspost/design-system-maintainers.

**Comment by gfellerph** [comment]
Design is up to date https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16696%3A55910&mode=design&t=nvIt9DZwzRtuNOSk-1

**Comment by gfellerph** [comment]
Close as won't fix
