### ISSUE TITLE
e2e are not started when only documentation changes

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2364]
e2e test were not triggered on CI with https://github.com/swisspost/design-system/pull/2175
Pnpm did not trigger the internet-header tests because there were no change there and there is no dependency for the documentation on the internet-header packages. But in reality, there is a dependency between the two as the Cypress test are using the documentation to test the component.

We could add the documentation as a dependency in the package.json, but this creates a loop as the documentation is using the internet-header package to display the component.

So we should either:

* Move the e2e internet-header tests to a separate package
* Move the e2e internet-header tests inside the documentation package
* Change the e2e tests to not rely on the documentation. 
* Force e2e tests to run when documentation change

**Comment by imagoiq** [comment]
Let's think about it and make a decision on the next triage

**Comment by gfellerph** [comment]
Decided to go with option 3

**Comment by gfellerph** [comment]
Closing as won't fix.
