### ISSUE TITLE
Build Online Service Promo Post

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2370]
To be able to test components in the context of an Online Service, we need to build examples of existing Services.

**Current Problems in SPDS:**
- We cannot test components in a context of an Online Service
- We cannot identify requirements for Online Services or find requirements that are different between Websites and Services

**Current Problems identified in research:**
- Layout and responsive behaviour does not work
- Missing guidelines
- Missing components

**assumptions**
- My assumptions are, there are different needs, for Services and Editorial Content
- The Foundations need to be the same
- There will be shared components
- There will be specific components for Websites and Online Services

**Comment by gfellerph** [comment]
Closing as out of Design System scope
