### ISSUE TITLE
testing: experiment with cypress-axe

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2381]
axe core is an accessibility testing tool that can be used with cypress (https://www.npmjs.com/package/cypress-axe). It would be interesting to have an experimental setup and see how we can use it/how it behaves with our setup.

This could be a good candidate for the blueprint if it works well, there is also playwright integration.

```[tasklist]
### Tasks
- [x] Install & setup cypress-axe
```

**Comment by imagoiq** [comment]
Two things to add here:

-[ The list of rules used by axe-core](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md)
- [A blog article with few use cases](https://timdeschryver.dev/blog/setting-up-cypress-with-axe-for-accessibility#the-result):
  - Using a sitemap to test all pages of a website 
  - Testing with different screen resolutions
  - Testing with different color schemes
