### ISSUE TITLE
Header Logo covering content on postauto.ch

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2425]
A customer complained that the logo in the header of postauto.ch is so big that it covers the content.
However it disappered after refreshing the website a couple of time.

Macbook, Chrome 119

We are not able to reproduce it so far.
Could probably be a caching problem.

![MicrosoftTeams-image](https://github.com/swisspost/design-system/assets/9716662/11a1b2ba-980f-4ae9-a028-e1c57c7295bb)
![MicrosoftTeams-image (1)](https://github.com/swisspost/design-system/assets/9716662/b410d063-2d37-4484-8990-708375ad69ba)
![MicrosoftTeams-image (2)](https://github.com/swisspost/design-system/assets/9716662/27e48b6e-afa3-4e84-922d-f716c48de197)

**Comment by gfellerph** [comment]
I had a similar request. It's reproducible with older unsupported Safari Versions (14). I think it would be a good idea to just define a compatible base size so that the logo does not block anything. If we can't reproduce it in supported browsers, criticality is a little lower.

**Comment by gfellerph** [comment]
Won't fix until we have further information/more reports with better information.

**Comment by gfellerph** [comment]
> Der Anteil von Safari Versionen 14 und tiefer liegt nur bei 0,7% aller Sessions auf pa.ch, darum kann ich es absolut nachvollziehen wenn dies nicht mehr unterstützt wird. Jedoch sind dies trotzdem ca. 40 Sessions pro Tag welche ein übergrosses Logo sehen. Ich finde das übergrosse Logo schon ein heftiger Eingriff in die UX. Könnte man dies mal genauer mit dem Design System Team anschauen?
