### ISSUE TITLE
Fix icon component story `flip-h` and `flip-v` controls

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2427]
There are multiple `flip-h` and `flip-v` controls available in the story controls.

Two of them are coming from the web-component (they do not work in the story), two are self made controls (they work as expected).
There seems to be a problem with the way, they are implemented in the HTML.

![image](https://github.com/swisspost/design-system/assets/9716662/e2493705-37bb-4bad-b68f-6a333cbe7c2d)

**Comment by alizedebray** [comment]
Using the `SpreadArgsDirective` will probably fix the issue with the case.
