### ISSUE TITLE
Update spinner

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2445]
Update the spinner styles to match design: 
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16527-53294&mode=design&t=87EdEEuV6V0XjvFY-0

@rouvenpost created a dynamic spinner image that can be implemented.

Files: [SwissPostSpinner.zip](https://github.com/swisspost/design-system/files/13858875/SwissPostSpinner.zip)

Antialiasing on the apng and gif assets is really horrible, try to implement the svg variant.

![SwissPostSpinner-200px_apng](https://github.com/swisspost/design-system/assets/1659006/01b3f07c-2f5e-49c4-8bc1-eb34c8b607af)

**Comment by imagoiq** [comment]
Should solve https://github.com/swisspost/design-system/issues/226

What about https://github.com/swisspost/design-system/issues/2439 ?
