### ISSUE TITLE
Component: Search Input | Positive

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2494]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16739%3A53259&mode=design&t=UTRU4FvIZ6ZvFBGz-1

**Story book:**
To be added

**Comments:**

- Implemented Search Icon on the right side according to current design
- Updated the documentation

**Comment by gfellerph** [comment]
Closing in favour of v2
