### ISSUE TITLE
Write Layout/Gutters page for documentation

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2495]
These pages are still TODO:

https://next.design-system.post.ch/?path=/docs/foundations-layout-todos--docs
https://next.design-system.post.ch/?path=/docs/foundations-layout-gutters--docs

There is at least one direct reference from another page to the gutters.

```[tasklist]
### Tasks
- [ ] Decide if we want to split the grid and gutter pages or put it all together on one page
```

**Comment by gfellerph** [comment]
Resolution 25.01.2024: Improve the grid page with a visual example of a gutter with a control to change it.
