### ISSUE TITLE
Component: Pagniation

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2516]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=16523%3A53293&mode=design&t=UTRU4FvIZ6ZvFBGz-1

**Story book:**
https://next.design-system.post.ch/?path=/docs/components-pagination--docs

**Comments:**

- Check existing component
- Rework Component
- Update Documentation

**Comment by Vandapanda** [comment]
First proposal implemented, please let me know if you'd like changes

**Comment by oliverschuerch** [comment]
DEVs ticket has been created: #2801 
@rouvenpost and @Vandapanda please update states in Figma.
