### ISSUE TITLE
Foundations: Font Styles "Strikethrough" and Body Bold

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2520]
We need to add the following font styles in the foundations:

- Strike-through for Disabled Buttons  
- Label Bold for example Breadcrumbs

**Comment by rouvenpost** [comment]
I added the Disabled State for Fonmts to the Foundations. For Bold in the Breadcrumbs i used the Title 16px....

**Comment by gfellerph** [comment]
Closing as done
