### ISSUE TITLE
fix(alert/notifications): toast not closing automatically

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#255]
When mouse enters a dismissable toast and then mouse leaves it again (do not close it), the toast will not be closed automatically after X seconds. Every other dismissable toast will be closed automatically after X seconds.

Expected behaviour:
- [x] onmouseenter clear automatically closing timeout
- [x] onmouseleave apply a new automatically closing timeout

**Comment by gfellerph** [comment]
Might just be a setting in the demo that's wrong or needs to be added.
