### ISSUE TITLE
Check tooltip performances

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2565]
After replacing all the ngb-tooltip with the post-tooltip in their application, Beda project noticed that the rendering of the pages is very slow.

**Comment by gfellerph** [comment]
Tooltips rendered in a loop seem to be an issue due to how Angular is rendering DOM. If the tooltip definition can be taken outside, it's fine (tooltips can be re-used if they have the same text).

```html
<div *ngFor="let number of numbers">
    <post-tooltip id="test">message</post-tooltip>
    <button data-tooltip-target="test">button {{ number }}</button>
</div>
```
