### ISSUE TITLE
headingLevel property on post-accordion-item might confuse users

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2571]
The headingLevel property is not documented anywhere for the user (reported here: https://github.com/swisspost/design-system/issues/2569), but it can be as well perhaps misleading for the users when they use a slot.

For example, one might think that the heading level is used when they write: `<h6 slot="heading">My heading</h6>`, but the user needs to define as well the headingLevel to make it work.

**Comment by imagoiq** [comment]
From last Roundtable: ![Teams_tSrRuNuMXO](https://github.com/swisspost/design-system/assets/12294151/98f0dce3-c819-4908-832c-5f6d4a98c96d)

**Comment by gfellerph** [comment]
Closing as won't change (for now (@alizedebray ))
