### ISSUE TITLE
fix(cards): contrast too deep for text in card-img-overlay

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#259]
Depending on the selected background image, the contrast of the text in a `.card-img-overlay` container is too deep.

![image](https://user-images.githubusercontent.com/9716662/182841989-1879964c-265c-4629-9cae-5543f5a74231.png)

**Comment by gfellerph** [comment]
- [ ] Label this card as a no-go example, text on an image is really difficult to get right in every context. Current examples always have a colored background (heros, caroussel).
