### ISSUE TITLE
Component Button Group | Positive & Negative

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#2593]
Figma
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=70%3A407&mode=design&t=ZSoe0MTs3zuKmoiG-1

old
https://www.figma.com/file/KDAqx5qYIhMt5YnB7HJVSE/post_library_atoms?type=design&node-id=0%3A2&mode=design&t=h7jkHjB3i4bxOhVk-1
https://www.figma.com/file/raFzhcFmx7rBk3zgg46kXc/post_portal_opp_layout_v58?type=design&node-id=0%3A734&mode=design&t=8fIo91pngO4uaDF5-1

Dev
https://next.design-system.post.ch/?path=/docs/021d61aa-e039-4858-b4b9-b86a3e772811--docs

```[tasklist]
### Tasks
- [ ] Switch to vertical stacked buttons on mobile devices.
- [ ] Check if wrapping to a new line is still possible, where necessary.
```

**Comment by rouvenpost** [comment]
Input Philipp Gfeller:

Needs additional considerations for mobile (discussed with @Cian77 already a bit):

What happens with more than 3 buttons on 320px?
Switching to a vertical stack would be a possibility
Truncating text is not accessible
What happens with just two buttons in a 1920px fullscreen layout?
Could define a max width for a button

**Comment by rouvenpost** [comment]
Design Ready for Review

**Comment by rouvenpost** [comment]
I added max with to the Buttons where it makes sense. i also added examples.

**Comment by gfellerph** [comment]
Closing in favor of #3460
