### ISSUE TITLE
Component: Avatar

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2596]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=17162%3A7287&mode=design&t=Q7MUVh3G2mYSJ7OV-1

**Story Book:**

**Comments:**
Review component if everything is final

**Comment by rouvenpost** [comment]
@gfellerph how do we deal with the Long Names? Can the Truncation Input from Christian Zundel be ignored? Or do we have to remove the "Long Name" usage from the Documentation?
