### ISSUE TITLE
Component: Radio Button | Negative

### ISSUE THREAD

**Issue by Cian77** [swisspost/design-system#2601]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=7777%3A33876&mode=design&t=xVjboB9gCTmSBwof-1

**Story Book**
https://next.design-system.post.ch/?path=/docs/151242aa-a074-4a55-a81c-db597c83cdad--docs

**Comments:**
- Ad new Type: Negative

**Comment by rouvenpost** [comment]
Negative Variants have been added.

**Comment by gfellerph** [comment]
Closing as won't implement
