### ISSUE TITLE
H5 on xs Viewport differs from Figma

### ISSUE THREAD

**Issue by paavo** [swisspost/design-system#2609]
H5 on xs Viewport (<400px) is defined as 16px in [Figma](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=20734-25130&mode=dev).

But it will be set to 14px here:
https://github.com/swisspost/design-system/blob/4b3e7f924fbc8488fca970626a8b55bf84306c12/packages/styles/src/variables/_heading.scss#L33

_Figma (320px Viewport)_
![image](https://github.com/swisspost/design-system/assets/1118783/aa965c9c-9847-40d1-94e4-9c35d8676f90)

What is correct?
@gfellerph

**Comment by gfellerph** [comment]
Hey @paavo, thanks for opening an issue. I think it's a mistake - fix incoming.

**Comment by paavo** [comment]
> Hey @paavo, thanks for opening an issue. I think it's a mistake - fix incoming.

Thanks @gfellerph. 

What about H6 Font-Size? (not documented in figma)
https://github.com/swisspost/design-system/blob/cd85514b49b8c4f5e440b1a4548c75b2bcb23140/packages/styles/src/variables/_heading.scss#L39

**Comment by gfellerph** [comment]
That's 14px as well

**Comment by paavo** [comment]
> That's 14px as well

H6 on XS should be 16px or 14px? @gfellerph

**Comment by gfellerph** [comment]
@paavo h6 on XS is 14px since it's already 14px between 420 and 640.

**Comment by paavo** [comment]
> @paavo h6 on XS is 14px since it's already 14px between 420 and 640.

Got that.
So bodytext will be bigger than headline on Mobile?

**XS**
H6 `14px`
Bodytext `16px`

**Comment by rouvenpost** [comment]
Hello Paavo,
H6:
Title 14 px Bold
Subtitle 14px Light
Body 12px Regular
