### ISSUE TITLE
Update heading docs for class overrides

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2611]
On the [typography page](https://next.design-system.post.ch/?path=/docs/foundations-typography--docs#headings), the heading class overrides are documented in text form and there is a link to "more information" on the [Headings page](https://next.design-system.post.ch/?path=/docs/components-heading--docs). The headings page effectively has less information, especially about the usage of class overrides.

```[tasklist]
### Tasks
- [x] Add a control to override the visual appearance of a heading with the classes `.h1` - `.h6`
```

**Comment by b1aserlu** [comment]
closed with PR #2640. Somehow failed to link the PR to this Issue
