### ISSUE TITLE
HCM Light/Dark: Forms invalid and valid feedback + border colors should be kept

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2642]
Currently, only the check icon color is kept on input and select and there is no way to differentiate valid and invalid with a checkbox for example.
https://next.design-system.post.ch/?path=/docs/patterns-forms--docs#validation-messages

![Image](https://github.com/swisspost/design-system/assets/1659006/2ec364b8-0c04-4e7e-8147-5e5c071ca9f0)

**Comment by gfellerph** [comment]
@Cian77 do you have suggestions for styling errors and success messages in HCM?

**Comment by gfellerph** [comment]
@imagoiq set validation icon color to text color

**Comment by imagoiq** [comment]
> [@imagoiq](https://github.com/imagoiq) set validation icon color to text color

@gfellerph Can you please clarify, your sentence is ambiguous. Setting the validation icon color to white on dark background would not fix the issue as the background of the feedback is still highlighted on valid or invalid state.

**Comment by gfellerph** [comment]
There are not enough colors to distinguish between valid/invalid state in HCM (and the other available colors have a different meaning https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/ but I'm sure you know that already). I'd argue that the highlight color is useful for directing attention towards the field.

As we had a look at the screenshot, we noticed that the only other identifier, the icon, is barely visible. Therefore we decided that it would be best to make this identifier more visible by giving it the same color as text. What do you think?

**Comment by imagoiq** [comment]
> There are not enough colors to distinguish between valid/invalid state in HCM (and the other available colors have a different meaning https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/ but I'm sure you know that already). I'd argue that the highlight color is useful for directing attention towards the field.
> 
> As we had a look at the screenshot, we noticed that the only other identifier, the icon, is barely visible. Therefore we decided that it would be best to make this identifier more visible by giving it the same color as text. What do you think?

I went with "Mark" color instead of "Highlight" for the background color, because according to mdn "Hightlight" is for "Background of selected items" and then it's difficult to distinguish between selected input and the rest. https://github.com/swisspost/design-system/pull/2766
