### ISSUE TITLE
fix(form-file Safari): display error

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#266]
In Safari on macOS and on iOS, the input-field is displayed incorrectly.

![image](https://user-images.githubusercontent.com/9716662/183057342-21fbdbf6-495f-4abc-b768-a4caa696099e.png)

![image](https://user-images.githubusercontent.com/9716662/183058665-2163a2e2-3880-4c60-b68a-4361f4731429.png)

**Comment by gfellerph** [comment]
Quite complicated, as this text cannot be targeted by CSS directly. Changing padding on the input works, but does not prevent inconsistencies between Chrome/Safari.
