### ISSUE TITLE
Component Input Group

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2664]
Create a component similar to https://getbootstrap.com/docs/5.2/forms/input-group/
```[tasklist]
### Tasks
- [ ] Implementation seems complex without breaking changes, needs some research first to see what's possible without adding new markup
```

**Comment by gfellerph** [comment]
Design ready: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=21923-74274&mode=design&t=nvIt9DZwzRtuNOSk-4

**Comment by gfellerph** [comment]
Closing in favour of v2 #3351
