### ISSUE TITLE
A11y – Check color-contrast on post-tabs with dark background

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2684]
Reported by cypress-axe: 
![Cypress_3Nn8pl3IFf](https://github.com/swisspost/design-system/assets/12294151/6098f7ed-7be5-41c6-ae88-33af32f8cc76)

```[tasklist]
### Tasks
- [ ] Fix issues with color contrast
- [ ] Enable 'color-contrast' rules again (by removing the option) on the e2e test
```

**Comment by gfellerph** [comment]
@swisspost/design-system-designers refine design on dark background https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=26389-11288&mode=design&t=nvIt9DZwzRtuNOSk-4
