### ISSUE TITLE
A11y – Check color-contrast on table with dark background

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2691]
Reported by cypress-axe: 
![Cypress_JECpUyLHro](https://github.com/swisspost/design-system/assets/12294151/af22b483-c29e-4380-811a-f3d74eb753b9)

```[tasklist]
### Tasks
- [ ] Fix issues with color contrast
- [ ] Enable 'color-contrast' rules again (by removing the option) on the e2e test
```

**Comment by oliverschuerch** [comment]
Check again after 2718 has been merged!
If fixed afterwards, only enable the color-contrast rule again.

**Comment by gfellerph** [comment]
Closing as won't due, waiting for token implementation.
