### ISSUE TITLE
Research: improve rating screen reader support

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2699]
Currently, the rating component is constructed as a input type range. For screenreaders, there is no distinction between a rating and a range. 

```[tasklist]
### Tasks
- [ ] Research best practices
- [ ] Create implementation ticket
```

**Comment by oliverschuerch** [comment]
Aria-Label has been implemented with a default value of "rating".
Please check again and if this is not enough, we can triage this ticket next week.

**Comment by gfellerph** [comment]
Closing as not relevant anymore
