### ISSUE TITLE
Update `card-control` disabled styles on dark backgrounds

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2715]
For know, I was only able to implement the wanted styles by adding a custom `rgba()` color definition for this.
As soon as the newly defined design-system alpha colors are implemented, we need to update the SCSS definition in `post-card-control.scss`.
```[tasklist]
### Dependant on
- [ ] https://github.com/swisspost/design-system/issues/2716
```

**Comment by gfellerph** [comment]
@oliverschuerch can this be closed?
