### ISSUE TITLE
Button Group incorrect on dark backgrounds

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2720]
The color of the active button is incorrect on dark backgrounds: 

![Image](https://github.com/swisspost/design-system/assets/33580481/b436dccb-7524-4309-b7ed-a763f853a892)

**Comment by oliverschuerch** [comment]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=51-59&mode=design&t=IYvLqgFWoBWJjcJM-0
