### ISSUE TITLE
Should we add an animated button pointing left?

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2723]
From a request:

> We have noticed that our `Back` Button has an arrow pointing right.
> It is the Bootstrap Animated Button from the Design System: https://design-system.post.ch/#/bootstrap-samples/buttons.
> Is there a way to have the arrow pointing left, so that our back buttons visually show what is happening when clicking?
> ![image](https://github.com/swisspost/design-system/assets/1659006/f64a35ad-7a68-4b95-9c55-dbf7a641c6fb)

**Comment by oliverschuerch** [comment]
We need to ask UX Designers first, if we really want to have this in the design system.
@rouvenpost can you please have a look and decide if this should be implemented?
If there are questions, reach out to one of the DEVs team.

**Comment by Vandapanda** [comment]
Implemented in Figma

**Comment by rouvenpost** [comment]
Pointing left Variants are added.
