### ISSUE TITLE
Open a specific post-tabs from URL anchor

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2726]
As a design-system developer, I would like to be able to open a specific tab from a URL anchor so that I can link the web-component variant of the [alert component](https://next.design-system.post.ch/?path=/docs/105e67d8-31e9-4d0b-87ff-685aba31fd4c--docs) directly.

Blocked by: https://github.com/swisspost/design-system/issues/2685

```[tasklist]
### Tasks
- [ ] Add the possibility to scroll to a post-tab by adding a URL anchor (url#anchor)
- [ ] Add the possibility to open a specific post-tab by adding a URL search parameter (url?tab-id=panel)
```

**Comment by gfellerph** [comment]
This is functionality that can be implemented on project side. Adding an id to the tabs will enable the scroll functionality  using the active-panel setting enables opening a specific tab.
