### ISSUE TITLE
Fix stencil build warnings

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2782]
![Image](https://github.com/swisspost/design-system/assets/33580481/e6ede7ff-f592-46b0-a861-58db9cbaf724)

**Comment by imagoiq** [comment]
Related PR for the loader warning in internet-header: https://github.com/swisspost/design-system/pull/2152
I think it was not possible to fix it at the end.

**Comment by oliverschuerch** [comment]
We should carefully read the following page and see what we really need to do: https://stenciljs.com/docs/publishing
