### ISSUE TITLE
Table: Create possibilities for complexer Tables

### ISSUE THREAD

**Issue by Vandapanda** [swisspost/design-system#2785]
Create variants according to https://primeng.org/table

[Figma](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=21235%3A57556&mode=design&t=g2Bs8idEX3FzJg3A-1)

**Comment by Vandapanda** [comment]
Decided for AG Grid. Looking into Design Tokens

**Comment by Vandapanda** [comment]
Built a post version with tokens but isn't relly worked on anymore as V1 and different priorities

**Comment by gfellerph** [comment]
Closing in favor of #2949
