### ISSUE TITLE
Set `samesite=none` to cookies of Google Tag Manager

### ISSUE THREAD

**Issue by imagoiq** [swisspost/design-system#2804]
It appears as a warning in Firefox devtools:

![firefox_weSEjKCZ3b](https://github.com/swisspost/design-system/assets/12294151/2cdf30bd-76d9-49d8-a1c0-439e109eb33f)

https://stackoverflow.com/a/60882686

**Comment by oliverschuerch** [comment]
Could not reproduce.
We're using Google Tag Manager (GTM) instead of Google Tag (GTAG).
