### ISSUE TITLE
Add keywords for icons without any

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2830]
Some of our icons have no keywords specified, and are therefore hard to find:
![image](https://github.com/swisspost/design-system/assets/9716662/ed24ef9c-74c6-4864-b71b-9716461491eb)

For reproduction or testing:
`pnpm --filter @swisspost/design-system-icons fetchSVGs`
`pnpm icons:start`

**Comment by rouvenpost** [comment]
I checked all the Icons on Censhare. I added translations in the localised Tags to trigger changes. I hope the Keyword now beeing delivered.

Numbers of checked Icons:
3057
3059
3055
3060
3061
3063
3065
3134
8009
8001
8010
8004
8002
8005
8011
8008
8006
2143
2166

**Comment by rouvenpost** [comment]
@oliverschuerch can you check if the Keyword now are correctly shipped?

**Comment by oliverschuerch** [comment]
The above have keywords now.
Thanks for fixing!

However, there are 5 new icons without keywords:
![Image](https://github.com/user-attachments/assets/a7e53303-bb67-4377-8e1e-7e97bb13c998)

**Comment by rouvenpost** [comment]
I checked the above mentioned Icons. They have Keywords:

3073:
Piktogramme "Die Post" ab 2017, Telefon, Telefonhörer, Téléphone, Combiné, Telephone, telephone receiver

3058:
Piktogramme "Die Post" ab 2017, tirare, tirare, tirare

2241:
Wunschdatum, Date souhaitée, Data desiderata, Desired date

2295:
Batterien, Autobatterie, Batteries, batterie de voiture, Batterie, batteria per auto, Batteries, car battery

2474:
Ergebnisse E-Voting, Résultats du vote électronique, Risultati del voto elettronico, Results of e-voting

If the problem persists please reach out to Michael Eberle to Check if Chenshare API works correctly....

**Comment by oliverschuerch** [comment]
In the near future, designers will be able to visit the icons health page in our docs, after adding/changing icons and see if everything is allright.
