### ISSUE TITLE
Add `border-radius` to the `.form-check` element

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2876]
We've decided that the focus-ring around interactive elements should never add a border-radius to an element and instead the element needs to provide rounded-corners by itself and the focus-ring will follow this default form.

To align with the [Figma Design](https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=17960-14667&mode=design&t=ntp13MiNrWn9jJ9j-0), we need to add `border-radius` to the `.form-check` element, so the focus-ring will show up with rounded-corners.

Dependant on #2855.

**Comment by gfellerph** [comment]
If a border radius is needed, use the content slot of the mixin to declare the border radius. Will be added in #2855
