### ISSUE TITLE
Automigrations: going forward

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2907]
How do we want to tackle automigration in the future when we not only support Angular, but all kinds of setups?

**Comment by gfellerph** [comment]
@gfellerph an elaborate find and replace solution would be the best way forward
@oliverschuerch finding files would be the hardest part
@imagoiq don't know if it's possible to support all use cases, drop the idea of automigration? People are blaming issues on the automigrations. Going through eslint could be an idea, it would show you issues that need to be fixed. How are other frameworks handling this? 
@gfellerph eslint can also autofix some issues
@oliverschuerch I think we need more research, @alizedebray should be part of the discussion as well
@gfellerph create issue to try to use eslint for a very easy fix

**Comment by oliverschuerch** [comment]
Using a tool like https://github.com/dependents/node-dependency-tree could be an option.

**Comment by gfellerph** [comment]
Investigating eslint, otherwise going for search and replace.

**Comment by imagoiq** [comment]
Hi Philipp and the design system team,

Just had a thought about this issue. I stumble upon this a few weeks ago : https://macwright.com/2025/01/30/ast-grep-to-ban-bad-nesting.html

[ast-grep ](https://ast-grep.github.io/)might be the tool that you are looking for.

Cheers

Loïc
