### ISSUE TITLE
Improve chip HCM styles

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2919]
The chip HCM styles should be:

![Image](https://github.com/swisspost/design-system/assets/33580481/d1a69508-cb63-4062-aad7-c42b57d36ede)

Where, with Chrome, white is CanvasText, cyan is Highlight, blue is SelectedItem, and green is GrayText.

With Firefox the SelectedItem color is cyan too:

![Image](https://github.com/swisspost/design-system/assets/33580481/34895afb-cccd-47a5-85fd-a9b067099455)

Check if it is possible to create mixins from these styles.

**Comment by gfellerph** [comment]
@alizedebray update the ticket description so that this is about creating a mixin for HCM styles and we'll create tickets for implementation of the mixin for other components.

**Comment by gfellerph** [comment]
Closing as won't do for v1, keep in mind for v2
