### ISSUE TITLE
Fix the snapshot tests on Chrome

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2931]
The icons are not showing in the button's snapshot tests on Chrome: 

![Image](https://github.com/swisspost/design-system/assets/33580481/977d5eba-3a95-4635-80b4-456cb9503012)

Neither on the cards:

![Image](https://github.com/swisspost/design-system/assets/33580481/ee4f0e6a-398b-456f-b306-aad5225595da)

**Comment by oliverschuerch** [comment]
Snapshot pages are working correct locally. Adding timeouts up to 20 seconds before taking the snapshot, did not solve the problem.
I'm really out of ideas on this one...

**Comment by oliverschuerch** [comment]
I was not able to find a solution for the problem till now. And we decided to realease anyway, because the problems are only present on percy snapshot tests.

**Comment by gfellerph** [comment]
Closing as won't fix.
