### ISSUE TITLE
Fix checkbox and radio sizes

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#2934]
The large checkboxes and radios are now too small, they should be 22px with 2px border and are now 18px:

![Image](https://github.com/swisspost/design-system/assets/33580481/02f79e18-babc-4244-a7c9-ce44016fbdb6)

![Image](https://github.com/swisspost/design-system/assets/33580481/8e8de94c-b172-4688-8dd3-008e4e9be438)

**Comment by oliverschuerch** [comment]
It has been shown that there is no problem. The styles correspond to the Figma design.
We simply misinterpreted the Figma design at first.
