### ISSUE TITLE
Editable Chips

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#2954]

**Comment by rouvenpost** [comment]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=28584%3A171760&mode=design&t=Q299GtfI4fWp7kPH-1

**Comment by rouvenpost** [comment]
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?m=auto&node-id=28584%3A171760&t=Q0AoRnogLaD1jeoo-1

**Comment by rouvenpost** [comment]
The component is moved and renamed Combo Box: https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?m=auto&node-id=30556%3A4223&t=o2Lc4q81WX8ABCXP-1

**Comment by gfellerph** [comment]
Closing in favour of v2
