### ISSUE TITLE
Fix border-color on Textarea and Input when valid and focused

### ISSUE THREAD

**Issue by davidritter-dotcom** [swisspost/design-system#2972]
![image](https://github.com/swisspost/design-system/assets/141235163/c9617688-2dbe-4848-b40c-8f3332c7ab63)

**Comment by gfellerph** [comment]
@swisspost/design-system-designers valid focused states should be defined in figma.

**Comment by gfellerph** [comment]
Pattern discussion 02.05.: Focus border should be shown on validated form controls (focus style takes precedence over the validation style).

**Comment by gfellerph** [comment]
Closing as done
