### ISSUE TITLE
Docs fix the `storybook-manager-events.js`, which is used for `google tag manager`.

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2975]
We need to fix the `storybook-manager-events.js`, which is used for `google tag manager`.
![image](https://github.com/swisspost/design-system/assets/9716662/6cac7ff5-44ae-421f-9776-ec27407b35fd)

_Originally posted by @oliverschuerch in https://github.com/swisspost/design-system/pull/2797#pullrequestreview-1938595843_

**Comment by oliverschuerch** [comment]
Caused by #2797
