### ISSUE TITLE
Link List

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#2979]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=19760%3A1867&mode=design&t=rph5jWSBshxqY2ne-1

**Comment by rouvenpost** [comment]
Pattern Ready for review

**Comment by oliverschuerch** [comment]
```[tasklist]
### Tasks
- [ ] Remove the border-radius in focused state.
```

**Comment by rouvenpost** [comment]
Border Radius is removed.
