### ISSUE TITLE
Update invalid icon

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3044]
In the pattern discussion from 02.05.2024 we discussed the validation icon for invalid error messages. We decided to put the icon within the error message and change it from the exclamation mark to the exclamation mark within a triangle. This helps visibility on small font sizes and bad screens.

**Old icon:**
<img width="329" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/4c537048-c13a-43ad-bd48-7705e81bfc0a">

**New icon:**
<img width="564" alt="image" src="https://github.com/swisspost/design-system/assets/1659006/f401dfb1-7457-48fe-b70b-5bb3248e96e3">

```[tasklist]
### Replace icon for
- [ ] Replace icon in error icon
- [ ] https://github.com/swisspost/design-system/issues/3149
- [ ] https://github.com/swisspost/design-system/issues/3150
```

**Comment by gfellerph** [comment]
Ready for dev

**Comment by alizedebray** [comment]
Form validation is kept as is for now.
