### ISSUE TITLE
fix(datepicker firefox): frame not closed completely around placeholder

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/design-system#306]
Frames around datepicker placeholder are not closed completely.

![image](https://user-images.githubusercontent.com/81462538/184130620-28239c24-c9ff-4f4c-b17f-b0c1ad1ed23f.png)
![image](https://user-images.githubusercontent.com/81462538/184132433-7c5edf4f-9d8f-4cc4-a452-138e74cd189e.png)

**Comment by gfellerph** [comment]
@LarissaMS can you re-validate this issue? I was not able to reproduce it.
