### ISSUE TITLE
can not build client ressources anymore: bootstrap-container definitions maybe need "!default" apendation fix, since design-system-styles v 6.4.2

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#3143]
Hy Post-Design-System-Team!

I’m struggling with updating the design-system-styles component above version 6.4.1. (6.4.1. still works, but 6.4.2 or up to current 7.1.0 does not work anymore.)
It has to do with a change/override at the container component of bootstrap.

Context of our setup:
We use following components successfully:
```
    "@swisspost/design-system-components": "7.0.0",
    "@swisspost/design-system-icons": "7.0.0",
    "@swisspost/design-system-styles": "6.4.1",
    "@swisspost/internet-header": "1.9.1",
```

If we want to update the “internet-header”, (and thus by new dependencies/versioning all other packages), it has a new internal dependency to “design-system-styles” 7.1.0.
To make the design-system-styles 7.1.0 running, we also had to add manually the dependency
    "@stencil/core": "4.18.3",
Because it wasn’t available/resolvable within the design-system-styles package itself. (at least, that was, what our webpack-builder was noting)

We also add our own bootstrap package in addition to your design-system-packages. (We use your styles, but also have our own overridden definitions, based, on the original bootstrap (5.3.3.) definitions.)

The following error makes it impossible for us to build our definitions anymore. The “container” change after design-system-styles 6.4.1 makes it impossible to override the container definitions again.
```

[./node_modules/@stencil/core/internal/app-data/index.js](./node_modules/@stencil/core/internal/app-data/index.js) 2.51 KiB   
[./node_modules/@stencil/core/internal/client/](./node_modules/@stencil/core/internal/client/) lazy ^\.\/.*\.entry\.js.*
$ include...(truncated) 160 bytes Module build From line 30, column 13 of node_modules\bootstrap\scss\_containers.scss:    
╷30 │             @extend %responsive-container-#{$breakpoint};   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
╵You may not @extend selectors across media queries.
```

I was wondering, if you could define your container related overrides with a !default apendation, so they could be overridden again at a later compiling-stage, e.g. by the original bootstrap or our own definitions.

Example for form-switch definitions, we had to override with !default definitions, so the original bootstrap behaviour was still working. But this way, on special circumstances, we could still override the default behaviour later:

```
$form-switch-width: 2em !default;
$form-switch-height: 1em !default;
$form-switch-padding-start: $form-switch-width + .5em !default;
$form-switch-border-radius: $form-switch-width !default;
$form-switch-transition: background-position .15s ease-in-out !default;
$form-switch-unchecked-bg-position: left center !default;
$form-switch-checked-bg-position: right center !default;
```

Is it somehow possible to use !default definitions on the container definitions/breakpoint definitions/overrides, so we can still override them again, if needed?

Not sure, if this would be a solution, but it would be nice, if we could still override your definitions with our own bootstrap-based definitions, otherwise, we would have to change so much on our several web-portals, if we only want to use your design-system, without using our own bootstrap-based controls. (we need native bootstrap functionality for other things too.)

Greetings

Adrian

**Comment by gfellerph** [comment]
Hey @aedu-hostettler, thanks for submitting this issue. Out of interest, what are you overriding the container styles with? What are your requiremenets for containers? We'll have a look at the request and update as soon as possible.

**Comment by oliverschuerch** [comment]
@aedu-hostettler can you once try to update our packages to `7.4.2` and the internet-header to `1.14.3`?
Do you have the same issue then?
