### ISSUE TITLE
Intranet-Input: Diacritics on capital letters are not completely visible on certain screen sizes

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3152]
In the following example (from your doc page), you can see (if you look very closely), that the circumflex on the capital "O" (i.e. "Ô") is not completely visible. This way it looks more like a "Ö".
 
![image 11](https://github.com/swisspost/design-system/assets/1659006/173f293c-cab0-4b97-b3ed-150827d8fb06)
https://design-system.post.ch/?path=/docs/2df77c32-5e33-402e-bd2e-54d54271ce19--docs
 
When I zoom in or out, or when I change the screen size, the circumflex becomes completely visible again in most cases. Still, in certain cases, this becomes confusing. 
 
I'm pretty sure, this behaviour also occurs with other [diacritics](https://en.wikipedia.org/wiki/Diacritic), like acute, grave, and others, but there is less visible and not as confusing.

**Comment by gfellerph** [comment]
Discussion: Line height is probably the issue.

**Comment by oliverschuerch** [comment]
This has been fixed already by #2857.
