### ISSUE TITLE
Form controls should have rounded corners, when focused

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3165]
![image](https://github.com/swisspost/design-system/assets/9716662/b8047040-dd98-4046-a946-e537bf847c7e)

Do this for:

- input
- select
- textarea

**Comment by gfellerph** [comment]
I don't think `border-radius` should change based on the focus state (there was previous discussion about this). In the case of the input fields, we came to the conclusion to leave the focus outline square, matching the `border-radius` of whatever element it's being used on. We could update the design for consistency, but that has low prio IMO.

**Comment by gfellerph** [comment]
Closing as fixed
