### ISSUE TITLE
Update disabled form fields

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3236]
Disabled input value should be cross out (or the labels when input is empty): 
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7775-33876&m=dev

However, disable select value is not crossed out: 
https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?node-id=7802-33963&m=dev

Decide on one or the other and implement this choice in the styles.

**Comment by gfellerph** [comment]
Asked @rouvenpost about that https://www.figma.com/design/xZ0IW0MJO0vnFicmrHiKaY?node-id=3805-22655&m=dev#869237465

**Comment by gfellerph** [comment]
Closing as duplicate of #3216
