### ISSUE TITLE
`::slotted` does not support all pseudo-elements

### ISSUE THREAD

**Issue by josemanosalvas** [swisspost/design-system#3304]
https://github.com/swisspost/design-system/blob/e9f49027cb78eed3a2e2d53389133d8f8f89140e/packages/styles/src/components/alert.scss#L80

As can be seen [here](https://stackoverflow.com/a/59532796), `::slotted` takes a [basic selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#basic_selectors).
The pseudo-selector throws an error when trying to minify with lightningcss. [Example](https://lightningcss.dev/playground/#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.alert-action%20%3E%20.alert-buttons%20%3E%20%3A%3Aslotted(.btn)%3Afirst-child%20%7B%5Cn%20%20margin-inline-start%3A%200%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Here are some codepen where the behavior of `::slotted` with pseudo-selectors can be verified:
- https://codepen.io/jmanosalvas/pen/yLdOzQO
- https://jsfiddle.net/WebComponents/108ey7b2/

Relevant discussions: 
- https://github.com/WICG/webcomponents/issues/655
- https://stackoverflow.com/a/61631668

**Comment by gfellerph** [comment]
@josemanosalvas thanks for the issue, we'll look into it.
