### ISSUE TITLE
fix(general chrome/firefox): different color scheme

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/design-system#335]
Chrome and Firefox have different color schemes (Chrome = yellow, Firefox = blue).

Chrome:
![image](https://user-images.githubusercontent.com/81462538/184630039-6a41cd0d-8342-424e-b632-a740a95b0e5d.png)

Firefox:
![image](https://user-images.githubusercontent.com/81462538/184630077-51dff25a-ef03-4906-b94d-56a9c390a405.png)

**Comment by gfellerph** [comment]
- [ ] Investigate cause. If there is a quick fix, apply - otherwise move to Web Styles Next
