### ISSUE TITLE
Use the post-logo in the internet-header

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3365]
For the `swisspost-internet-header` component to remain standalone when using the post-logo component, it should:

```[tasklist]
### Tasks
- [ ] check if the post-logo exists in the CustomElementRegistry with `customElements.get('post-logo')`
- [ ] define the post-logo through its `defineCustomElement` function if it does not exist
```

> [!WARNING]
> **Make sure the changes do not have a significant impact on the internet-header output**
> Stencil tends to distribute all web components it can find!

**Comment by gfellerph** [comment]
On hold because the new portal will not use <swisspost-internet-header> and not have this conflict issue. It's something that we need to have a look at later when we're re-building the <swisspost-internet-header> with components from the components package.

**Comment by gfellerph** [comment]
Closing as not relevant any more. New internet header will be reworked from the ground up.
