### ISSUE TITLE
Remove disabled button in the accessibility documentation

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3367]
I you fill in the "Good example" form in the [accessibility documentation](https://design-system.post.ch/?path=/docs/46da78e8-e83b-4ca1-aaf6-bbc662efef14--docs#form-good-example) and submit it, then the button is disabled while loading.

This button should actually be enabled, and the event prevented. 
```[tasklist]
### Tasks
- [x] Explain two ways of handling multiple submissions: abort current request and send new one or suppress new submissions during loading
```

**Comment by gfellerph** [comment]
Discussion: not disabling is better, when button is disabled, it looses focus.
