### ISSUE TITLE
fix(tabs chrome/firefox): incomplete frame around tab-title

### ISSUE THREAD

**Issue by LarissaMS** [swisspost/design-system#339]
When tabbing through page the frame around the first tab-title is not complete in Chrome and Firefox.

Chrome (first tab):
![image](https://user-images.githubusercontent.com/81462538/184647537-b4038025-e347-4e29-88e3-1022c69862ed.png)

Chrome (second tab):
![image](https://user-images.githubusercontent.com/81462538/184647559-5aa14ad5-3483-4149-aa00-4283b3f258b5.png)

Firefox (first tab):
![image](https://user-images.githubusercontent.com/81462538/184647584-d5d7d048-ae9c-4d4e-9891-a645fb59f40c.png)

Firefox (second tab):
![image](https://user-images.githubusercontent.com/81462538/184647611-6c78e372-4a3c-4840-9ea6-a45522b50cbf.png)

**Comment by oliverschuerch** [comment]
This bug has allerady been fixed within issue #212.
