### ISSUE TITLE
How to extract values from Figma: Workflow optimization for Devs

### ISSUE THREAD

**Issue by Vandapanda** [swisspost/design-system#3400]
Short talk about how our Devs can best extract all the needed values from Figma. Also giving a brief overview about Tokens Studios Inspect feature that might help with that. 
![image](https://github.com/user-attachments/assets/d20f4541-c376-4664-9d09-2045cb0bf879)

**Comment by Vandapanda** [comment]
Possible topic to add here: Do we need (at least one) Tokens Studio pro acces for the devs?

**Comment by gfellerph** [comment]
Token studio has an inspect mode
Dev mode lists tokens as well
Pro mode is not needed for inspect mode in token studio
Dev mode can be switched to properties mode
Oli: For the moment, it's not enough for developing, not sure if there's a token for everything (line height?)
Can't use scss token maps for an overview
When having reading rights, dev mode is available, token studio not

Action: Organise Token Studio Session and set up Token Studio for everybody

**Comment by gfellerph** [comment]
Closing as done, will be documented in #3448
