### ISSUE TITLE
Investigate utility classes from tokens

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3413]
We need to create new utility classes using the token system. 
To do so we can potentially reuse Bootstrap utility API. 

Some utilities are breakpoint dependent, they should be declared for all breakpoint available in the grid: 
https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=26-51

**Comment by gfellerph** [comment]
@alizedebray and @oliverschuerch, are tokens ready for this?

**Comment by alizedebray** [comment]
New utility API was developed here: https://github.com/swisspost/design-system/blob/f619ff953be82d8d7918dfd8d99fdd304e3c1ac1/packages/styles/src/utilities/_variables.scss#L4
