### ISSUE TITLE
Use bootstrap to style the documentation preview

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3455]
After merging #3441, the stories will be rendered inside the shadow DOM of a `story-container` web component. This component will apply the appropriate design system styles based on the toolbar selection (e.g. post-internal, post-external, etc.).

However, the documentation preview—which contains these stories—currently also imports the post-external styles.

The design system styles include several CSS custom properties that can potentially “pierce” the shadow DOM of the `story-container`. As a result, the post-external styles from the documentation preview might unintentionally affect the story styles.

To prevent this issue, it would be better to use only Bootstrap styles for the preview. That way the design system styles are exclusively applied within the `story-container` component, providing an accurate representation of the selected styles.

**Comment by gfellerph** [comment]
We basically disabled the storybook way of styling the interface. Instead of using bootstrap (with the danger of conflicts for class names), I would propose to enable and customize the storybook styling again.
