### ISSUE TITLE
Remove release/v5 related stuff

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3483]
We do not support v5 anymore, therefore the branch can be removed.

```[tasklist]
### Tasks
- [ ] Remove branch `release/v5`
- [ ] Remove v5 related entry from file `documentation/public/assets/version.json`
```

**Comment by gfellerph** [comment]
@oliverschuerch I would not remove the already published v5 documentation. To me, that is something that will live as long as the Design System. For one, it's important that the docs are available to people stuck on this version for whatever reason, even if we're not supporting it any more. Second, it will be nice to go back in time in 5 years and see how the system evolved. Third, it's a good idea to keep site names on netlify occupied for security reasons therefore we can't delete the site anyway.

**Comment by gfellerph** [comment]
@oliverschuerch can we close this?

**Comment by gfellerph** [comment]
Closing as won't do
