### ISSUE TITLE
Handle SCSS deprecation warnings 

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3485]
There are a lot of deprecation warnings around, when you start the docs. Try to get rid of them.

![image](https://github.com/user-attachments/assets/682138a0-6ef3-4db2-bbd9-3a1113b5d136)

```[tasklist]
### Tasks
- [ ] Invest time to investigate and find out how quickly these issues can be resolved
- [ ] After fixing the issues, remove the `silenceDeprecations` properties in both packages (styles and documentation)
```

To see them do the following steps:
1. open up styles/gulpfile.js
2. remove all `silenceDeprecations: ['mixed-decls']` occurrences
3. run `pnpm styles:build`

To do the same in the documentatoin do the follwing steps:
1. open up documentation/vite.config.js
2. remove all `silenceDeprecations: ['mixed-decls']` occurrences
3. run `pnpm docs:start`

**Comment by bashirkarimi** [comment]
The `mixed-decls` warnings are in files where a mixing is used before declarations and that mixing has nested rules.
The proposed solution, _Move the declaration above the nested rule. To opt into the new behavior, wrap the declaration in `& {}_`, needs manual fixing and some of the mixings have new declarations and needs more work. This fix may break the design.

The number of warnings are a lot, but instances of mixings having nested rules are less.

**Comment by alionazherdetska** [comment]
Possible solution: https://app.daily.dev/posts/automating-sass-refactoring-resolving-mixed-declaration-deprecation-warnings-yyappqafg

**Comment by oliverschuerch** [comment]
Duplicates #3344

**Comment by oliverschuerch** [comment]
Updates have been done in issue #3344
