### ISSUE TITLE
Animation tokens

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3494]
Should animations (time to change from a state to another) be tokenized?

**Comment by gfellerph** [comment]
Resolution: 
- Re-use animations from v1 where applicable
- Look out for a motion library to hard code animations in code first for components that did not have motion in v1 or are new
- Once we have time, create a motion concept and implement it at a later stage

**Comment by oliverschuerch** [comment]
Closing this, until design comes up with a motion design
