### ISSUE TITLE
[component]: Chips Active but Disabled State

### ISSUE THREAD

**Issue by rouvenpost** [swisspost/design-system#3538]
### Description

I’m not quite sure whether the state “Active but Disabled” really makes sense.

Question to ChatGTGP: Does it make sense to have a «Active but Disabled State » Compponents in a Design System?

ChatGPTYes, it can make sense to have an "Active but Disabled" state in components within a design system, depending on the context and requirements of your application. This state typically implies that a component or UI element is visually styled to appear active (e.g., it has a highlighted appearance) but functionally disabled (e.g., it does not respond to user interactions).Here are some scenarios where an "Active but Disabled" state might be useful:
Contextual Feedback: In certain workflows, you might want to provide visual feedback that a component is available for interaction in some contexts, but it’s disabled due to current conditions. For example, a button might be disabled because it can only be clicked after a user completes a certain action or meets specific criteria.
Loading or Processing States: A component might appear active (e.g., highlighted or visually distinct) during a loading or processing phase but still be non-interactive. This can signal to users that the component is being worked on or that an action is in progress.
Future Availability: If a component is meant to be interactive at a later stage (e.g., a tab that will become active after a step in a process), visually indicating that it will become interactive can help manage user expectations.
Educational or Informational Purposes: In some educational or onboarding experiences, you might want to show components in a visually active state to indicate their purpose or importance, even if they are temporarily non-interactive.Designing "Active but Disabled" States
When designing this state, consider the following:
Visual Distinction: Ensure the component is clearly distinguishable from fully interactive elements. This might involve using different colors, opacity, or visual cues to indicate its disabled status.
User Experience: Make sure it’s clear why the component is disabled and what actions users need to take to enable it. Providing tooltips or messages can be helpful.
Consistency: Ensure that the design of the "Active but Disabled" state is consistent with your design system’s overall principles and patterns to avoid confusion.Overall, while it’s not a common pattern, having an "Active but Disabled" state can be beneficial in specific scenarios, provided it’s implemented thoughtfully and aligns with your design system's goals.

Question for Devs: pick up the edge case or not. Is it clear to SPDS users or does it raise more questions?

**Comment by gfellerph** [comment]
**Resolution**: Document that active disabled chips should not be shown altogether.
