### ISSUE TITLE
[bug]: Design-system icons make whole angular app crash

### ISSUE THREAD

**Issue by juliandanis** [swisspost/design-system#3553]
**Describe the bug**
When I use the design-system icon component in my angular app the icons don't get displayed and the site runs out of memory: 
![image](https://github.com/user-attachments/assets/5439a505-4d0a-4f6c-b665-080d365a9424)

**To Reproduce**

1. Contact me via Teams or Mail (julian.danis@post.ch) since you otherwise can't run the app.

**Expected behavior**
The icons get displayed and the app runs normal and doesn't crash.

**Screenshots**
See in bug description

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 11

**Additional context**
-

**Comment by schaertim** [comment]
Project specific problem which was resolved.
