### ISSUE TITLE
Rename _cwf.scss

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#356]
This file contains all the functions, mixins, variables and placeholders available in the design-system-styles. Developers are expected to use this file when working with Design System variables etc. 

- [ ] Find a good name for this file
- [ ] Rename the file and all the internal imports (tests, ...)

**Comment by gfellerph** [comment]
@oliverschuerch, @alizedebray possible names for the file that exports functions, variables, mixins and placeholders:

@use '@swisspost/design-system-styles/tools';
@use '@swisspost/design-system-styles/functionality';
@use '@swisspost/design-system-styles/utils';
@use '@swisspost/design-system-styles/utility';
@use '@swisspost/design-system-styles/stuff';

**Comment by oliverschuerch** [comment]
@use '@swisspost/design-system-styles/core';

**Comment by gfellerph** [comment]
@use '@swisspost/design-system-styles'; (Default internet styles)
@use '@swisspost/design-system-styles/intranet'; (Default intranet styles)
@use '@swisspost/design-system-styles/core' as post; (Variables, mixins, functions and placeholders)

1. Default import is as simple as possible
2. Intranet styles are clearly named as such
3. Core functionality is a clear name, but for consistency with other prefixes, the core module can be namespaced as post. The usage would then be `background-color: post.$yellow;`
