### ISSUE TITLE
Fix broken styles after removing global styles

### ISSUE THREAD

**Issue by bashirkarimi** [swisspost/design-system#3571]
After removing the [global styles](https://github.com/orgs/swisspost/projects/3/views/17?pane=issue&itemId=79585491), the following components have broken styles:
- [ ] Blockquote
- [ ] Collapsible 
- [ ] Table 
- [ ] Forms 
- [ ] Buttons
- [ ] Storybook
- [ ] Modal

**Comment by gfellerph** [comment]
Closing as not needed anymore.
