### ISSUE TITLE
Playground for styling v2 components

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#3574]
When implementing the styles for v2 components the documentation reacts to changes in the styles package and rebuilds the components. This as well as the refresh of the docs page takes 15+ seconds in total. This is a bit annoying to work with. Having a playground separate of the storybook docs which would also react to style changes and could be used while implementing v2 styles would be a big quality of life improvement in my opinion.

**Comment by gfellerph** [comment]
**Resolution**: Create dev setup for styles package to develop components faster
