### ISSUE TITLE
Disabled styles: is strikethrough really necessary?

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3577]
A lot of feedback was coming in about the new v1 disabled styles that feature a strikethrough. Originally, the disabled style was changed for better accessibility, introducing a dashed border and also a strikethrough. The main critique is:
- Text is harder to read
- Does not look good

Is the strikethrough necessary or can we go without it?

**Comment by gfellerph** [comment]
**Resolution**: Strikethrough can go in v1.

**Comment by rouvenpost** [comment]
I removed the Striketrough
