### ISSUE TITLE
[bug]: Intranet Header blueprint default config

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3595]
**Describe the bug**

The navigation does not render correctly with the current blueprint default setup:

![image](https://github.com/user-attachments/assets/db198e0f-f5b3-4bf0-976a-51c273bd2023)

**To Reproduce**
Create an intranet project with the blueprint

**Additional context**
https://teams.microsoft.com/l/message/19:e7fa68fb13eb40b4bf4604edea5f4b3e@thread.tacv2/1727450527448?tenantId=3ae7c479-0cf1-47f4-8f84-929f364eff67&groupId=123c7c9e-052a-40e6-98d3-6cc6d46bad0a&parentMessageId=1727450527448&teamName=Design%20System&channelName=%F0%9F%9A%91%20Support&createdTime=1727450527448

**Comment by gfellerph** [comment]
There seems to be a unnecessary `<ul>` element in the blueprint. Removing this solves the issue since the ul is already present in the header.

**Comment by schaertim** [comment]
I tried to reproduce the problem but it was already fixed in a previous commit. Checked with Joao that everything works as expected and the ticket can be closed.
