### ISSUE TITLE
Tokens function linting error

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3597]
When overriding the `tokens.$default-map` I get the following error: 
![Image](https://github.com/user-attachments/assets/98726730-1c65-45b7-9193-27e21ca38363)

**Comment by oliverschuerch** [comment]
I found these two resources, which should show, we are using valid SCSS syntax, but our editors, somehow mark it as error:

- https://sass-lang.com/documentation/at-rules/use/#reassigning-variables
- https://github.com/microsoft/vscode-css-languageservice/issues/278

I don't know if there is an actual fix for it...

**Comment by oliverschuerch** [comment]
@alizedebray can we close this for now, because there is no solution to this false positive right now?

**Comment by alizedebray** [comment]
@oliverschuerch sure, if there is no solution for now we will just have to wait.
