### ISSUE TITLE
Checkbox and radio-button layout question

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#3615]
![image](https://github.com/user-attachments/assets/3170475d-9ed7-4994-95ea-504678e778e2)
![image](https://github.com/user-attachments/assets/4a2d1321-bae0-4775-8e97-fc048c835e24)

```[tasklist]
### Tasks
- [ ] Add an inline variant for radiobuttons and checkboxes
- [ ] Add visual regression tests
- [ ] Design review
```

**Comment by gfellerph** [comment]
Resolution: Add horizontal variant

**Comment by rouvenpost** [comment]
I added the Horizontal Version:
https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=426-2188&t=73qjdgOvYWpCx6KR-1

**Comment by schaertim** [comment]
@rouvenpost could you also add a horizontal version for the checkboxes?

**Comment by rouvenpost** [comment]
Horizontal Checkboxes are created: https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=4908-23951&t=VREgbAjbHL7WiFgr-1

**Comment by gfellerph** [comment]
Closing in favour of #3273 and #3274
