### ISSUE TITLE
Does stencil work without importing `h`?

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3617]
Sonar reports some issues about imports of `h` (the stencil render function). Does the build work without importing it? https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&types=CODE_SMELL&sinceLeakPeriod=true&id=swisspost_common-web-frontend

**Comment by alizedebray** [comment]
![Image](https://github.com/user-attachments/assets/2fedcca6-6270-4578-8590-1ff5f4ec631a)

**Comment by gfellerph** [comment]
Resolution: remove warnings on sonar
