### ISSUE TITLE
Changeset messages

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3621]
We probably need to clarify a little more what should be written in the changeset messages and what shouldn't. 

- Should we say something about tokens or is this technical information that should be omitted?
- Should we use "add" or "updated" when a component was tokenized?

**Comment by gfellerph** [comment]
https://github.com/swisspost/design-system/blob/main/CONTRIBUTING.md

**Comment by gfellerph** [comment]
Closing as discussed.
