### ISSUE TITLE
[bug]: post-collapsible console errors

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#3725]
**Describe the bug**
The current `post-collapsible` component produces some console errors in our docs.
First of all there is a wrong CSS selector syntax in the `updateTriggers` method in the `post-collapsible.tsx`.
```tsx
`post-collapsible-trigger[for=${this.host.id}]`
// sould be
`post-collapsible-trigger[for="${this.host.id}"]`,
```
After fixing this temporary, there showed up another error:
![image](https://github.com/user-attachments/assets/6a28872b-4004-469d-a195-c3cac15e6cb3)

**To Reproduce**
1. Navigate to https://design-system.post.ch/?path=/docs/6a91848c-16ec-4a23-bc45-51c797b5b2c3--docs
2. Open DEV tools console

**Expected behavior**
The component should not throw any errors in the console.

**Comment by pazoozooCH** [comment]
I guess you'll do this anyway, but we would also need this backported to version 7.x as we are not on 8.x yet...

**Comment by pazoozooCH** [comment]
We now plan to upgrade to Angular 18, design-system 8.x, so backporting is no longer an issue for us...
