### ISSUE TITLE
[bug]: post-icon base path doesn't respect base tag

### ISSUE THREAD

**Issue by rysep2** [swisspost/design-system#3787]
The post-icon component ignores the base tag. So it's looking for the icons under /assets/post-icons instead of /kvm/app/ui/assets/post-icons in this example:
```
    <base href="/kvm/app/ui/">
    <meta name="design-system-settings" data-post-icon-base="./assets/post-icons" />
```
We use different routes locally (/) and on prod (/kvm/app/ui) that's why this is relevant to us. Currently we'd have to implement a workaround like having two index.html files for local and prod or alternatively replace the meta tag in the build script. These solutions should work but are a little bit hacky.

To fix this the post-icon component would have to take the base tag into account in this part of the code: https://github.com/swisspost/design-system/blob/224f190cb66805914d05a7ebdbb7892cbbde4c1e/packages/components/src/components/post-icon/post-icon.tsx#L129-L138

I could create a PR if you agree that this is not expected behaviour.

**Comment by gfellerph** [comment]
@rysep2 a PR would be awesome, I don't think we thought about taking the base path into account.
