### ISSUE TITLE
Fix code smell on switch component

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3876]
The switch documentation shows the following code smell: The attribute "aria-checked" is required by the role "switch".
https://sonarcloud.io/project/issues?pullRequest=3824&open=AZLoFPPzX_zWtYv13-zo&id=swisspost_common-web-frontend

**Comment by oliverschuerch** [comment]
Check if it could be a false positive.

**Comment by alizedebray** [comment]
False positive: 

> If the switch element is an HTML input[type="checkbox"], it uses the HTML checked attribute instead of the aria-checked property.
https://www.w3.org/WAI/ARIA/apg/patterns/switch/
