### ISSUE TITLE
Is blockquote a component or an element?

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#3886]
I am just wondering if the blockquote is a component or an element since the `.blockquote` class should only be used on `<blockquote>` elements.... 
I am adding this as a topic for the devs roundtable.

_Originally posted by @alizedebray in https://github.com/swisspost/design-system/pull/3882#discussion_r1829386587_
       
### Tasks

```[tasklist]
### 💻 Tasks
- [x] Rename tokens from 'quote' to 'blockquote'
```

**Comment by gfellerph** [comment]
**Resolution**: 
- Style quotes based on language in elements and document under foundation/typography
- Rename component to testimonial

**Comment by myrta2302** [comment]
New Resolution: It remains Blockquote
