### ISSUE TITLE
Rework fieldset styling

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#3898]
For the radio-button groups and the checkbox-groups to look like the figma design, the styling of the fieldset has to be adapted. A ticket to add spacing between the legend and the first fieldset item already exists: [#3847](https://github.com/swisspost/design-system/issues/3847). In addition a padding on the fieldset should be introduced to adhere to the design.

**Comment by gfellerph** [comment]
@schaertim please update ticket description with more infos.

**Comment by schaertim** [comment]
Proposed tokens:
  _post-legend-font-weight,
  post-legend-line-height,
  post-legend-large-font-size,
  post-legent-margin-end,
  post-legend-large-padding-block-start,
  post-legend-large-padding-block-end,
  post-legend-large-margin-block-end,
  post-legend-large-border-bottom,
  post-legend-large-border-color,
  post-legend-large-border-style,
  post-legend-large-border-width_

**Comment by Vandapanda** [comment]
@schaertim please make sure the token are also changed in the components it was used as this produces breaks

**Comment by schaertim** [comment]
@sandra-post ready for Design Review :)
Preview Link: https://preview-4092--swisspost-design-system-next.netlify.app/?path=/docs/61faccd2-de2c-48f0-9a06-c051a56580ef--docs
