### ISSUE TITLE
Bundle index/intranet when should which be used?

### ISSUE THREAD

**Issue by Gabko14** [swisspost/design-system#3914]
Hello Design System Team

I have a question regarding the bundles. Our application is internet facing, but it was developed with the intranet bundle (idk why). The responsiveness does not matter as it is made specifically for desktop users.

When we switch to the index bundle, it changes a couple of things and would take some effort to make everything pretty again. The design doesn't really improve in my opinion, and I personally do not think that this is necessary.

How important is it to use the index package in our case, is it worth the effort, and can an exception be made?

Thank you very much
Best Regards

**Comment by gfellerph** [comment]
Hey @Gabko14, thanks for reaching out. Switching to the index bundle has a couple of effects (compare the source of https://github.com/swisspost/design-system/blob/release/v8/packages/styles/src/index.scss against https://github.com/swisspost/design-system/blob/release/v8/packages/styles/src/intranet.scss).

The index bundle loads some styles for rich text elements that will be larger (the portal styles part), but does not include styles for the intranet header. The components however, are loaded in both bundles the same way so in this regard, the bundles don't differ that much. Therefore I think you should be fine with the intranet bundle for now. In upcoming versions however (we're working on v9 at the moment), the difference will be bigger and the components will not look the same for internal applications as for external ones with the main difference being the size of elements. I would recommend you to go with the easiest solution for the moment and then plan some more time to upgrade to v9 once it's released (probably around summer 2025).

**Comment by Gabko14** [comment]
Thank you for your helpful suggestion!

**Comment by gfellerph** [comment]
I'm closing this as done. Please feel free to re-open if you have follow-up questions or create a new ticket if something else comes up.
