### ISSUE TITLE
Form control size

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#397]
![image](https://user-images.githubusercontent.com/1659006/186078471-5c58953b-2eec-444d-8edc-9330e72888d4.png)

Form control lg and form control with floating label don't have the same height. The height of both should be 72px (set with rem).

Figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=121%3A1083

**Comment by oliverschuerch** [comment]
@gfellerph The given link does not provide the above shown example.
Can you please clearify?
