### ISSUE TITLE
Component: Basic List

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#398]
Add support for simple lists as seen on https://www.post.ch/de/empfangen/empfang-steuern

![image](https://user-images.githubusercontent.com/1659006/186111253-0e44c226-0814-4ff8-95b5-4d0d53ec7ca8.png)
![image](https://user-images.githubusercontent.com/1659006/186111289-c705ef7e-ec6e-4859-9e2c-9cc5ab1f385e.png)

**Figma**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=19518%3A5339&mode=design&t=WG8hb62cKWE4ErqU-1

**Dev**
https://next.design-system.post.ch/?path=/docs/utilities-list--docs

**Comment by gfellerph** [comment]
@wueestd maybe a duplicate

**Comment by wueestd** [comment]
changed it to a basic list

**Comment by Cian77** [comment]
@wueestd ready to be tested, thank you 👍

**Comment by wueestd** [comment]
@Cian77 awesome job, I added some comments. choos what ever seems to be relevant for you :)

**Comment by Cian77** [comment]
@wueestd I have added your recommendations. Concerning documentation. I think we should not over do it, as a UX Designer should know certain basics.

**Comment by gfellerph** [comment]
I added a dev ticket https://github.com/swisspost/design-system/issues/2342 and updated the Component gallery entry for lists https://github.com/orgs/swisspost/projects/4/views/1?pane=issue&itemId=14331616

**Comment by gfellerph** [comment]
Ready for implementation

**Comment by gfellerph** [comment]
Closing as done
