### ISSUE TITLE
Frequent updates to the pnpm-lock.yaml

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4004]
Almost every pull request updates the lockfile. Why is that? Are we all running the same version of pnpm?

**Comment by oliverschuerch** [comment]
Oli 9.6.0

**Comment by leagrdv** [comment]
Lea 9.6.0

**Comment by alionazherdetska** [comment]
Alona 9.6.0

**Comment by alizedebray** [comment]
Windows 10 Enterprise
pnpm 9.6.0
node 20.17.0

**Comment by gfellerph** [comment]
Closing as answered
