### ISSUE TITLE
Fix switch alignment using new token

### ISSUE THREAD

**Issue by schaertim** [swisspost/design-system#4039]
Right now there is a token missing which would be needed to center the switch vertically and thus we are not able to have it stick to the start if the label takes up multiple lines and still be centered. To resolve this at least a new token has to be created and/or the design has to be reworked.

- [x] Speak to Alessio
- [x] Fix alignment using new token
- [x] Design review for switch

**Comment by Vandapanda** [comment]
Not yet fixed in design but implemented a token named post.switch.icon.padding.container that uses the same padding as Checkbox and Radio button. Let me know if it needs another value.

**Comment by Vandapanda** [comment]
Fixed in Desktop design
