### ISSUE TITLE
Pixel-based sizing classes

### ISSUE THREAD

**Issue by myrta2302** [swisspost/design-system#4054]
The $post sizing utility classes (e.g. huge, giant, micro, etc) have been deprecated. This ticket https://github.com/swisspost/design-system/issues/3433  removes all these classes and keeps only the percentage classes (25%, 50% etc) as per the relevant bootstrap doc (https://getbootstrap.com/docs/5.3/utilities/sizing/).

1. Are we going to create new pixel-based classes?
2. Will we use tokens for this?

**Comment by gfellerph** [comment]
Discussion resolution in triage: No tokens necessary for this utility.

**Comment by myrta2302** [comment]
Pixel based size utility classes are already implemented in other ticket. 
So this is now only about documenting the migrations from named sizes to pixel based in the migration docs.
