### ISSUE TITLE
Validation feedback with hint & single radio/check 

### ISSUE THREAD

**Issue by myrta2302** [swisspost/design-system#4064]
Components that incorpoprate 'hint':
-  The spacing between feedback message and hint is not clearly defined. 
-  Hint and feedback message font sizes (post-device-10 /post-device-9)  do not adapt the same at different breakpoints. Is this on purpose?

Components that incoroporate one radio/check:
- What should be the spacing between component and feedback message for the case of e.g. a single checkbox. https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=4876-28268&node-type=instance&m=dev

Relevant PR preview ->  https://preview-3824--swisspost-design-system-next.netlify.app/?path=/docs/1aa900d9-aa65-4ae0-b8cd-e6cca6cc3472--docs

**Comment by gfellerph** [comment]
Resolution:
Hint text and error message can be displayed at the same time.

Design:
Set up behavior and provide an example.
