### ISSUE TITLE
[bug]: hardcoded avatar url in swisspost-intranet-header component is outdated, broken or requires authentication

### ISSUE THREAD

**Issue by manuel-rw** [swisspost/design-system#4089]
**Describe the bug**
A harcoded link in the intranet-header component seems to be outdated or broken.

**To Reproduce**

1. Use the intranet header component https://github.com/swisspost/design-system/blob/63fd1ce9438b5546565e9726df46efcea18ed7cf/packages/intranet-header-workspace/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts#L23-L28 . Pass an example username (internal) to the component.
2. Open your browser and load the page
3. (Optional): Check network analyzer for failed request

**Expected behavior**
An image is supposed to load. The link will return a user avatar image if the provided user ID is correct.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e9cc83de-a704-4d9a-944b-82efbcf051ac)
![Image](https://github.com/user-attachments/assets/50e305fc-9423-44f3-9ed1-000ad673bef9)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge Version 131.0.2903.63 (Official build) (64-bit)
- Version 131.0.2903.63

The hardcoded URL is located here: https://github.com/swisspost/design-system/blob/63fd1ce9438b5546565e9726df46efcea18ed7cf/packages/intranet-header-workspace/projects/intranet-header/src/lib/swisspost-intranet-header.component.ts#L336-L340 .
As an alternative, the component could accept an additional optional property where a custom URL can be passed for the avatar URL - which may make updating faster and simpler instead of rushing a new release of the design system.

**Comment by oliverschuerch** [comment]
The new URL to use is: https://postchag.sharepoint.com/_layouts/15/userphoto.aspx?size=S&username=oliver.schuerch@post.ch

**Comment by manuel-rw** [comment]
Hi @oliverschuerch , any updates on when this will be merged? IMO this seems rather urgent and should be easy to push a standalone fix, no?
