### ISSUE TITLE
Update the style imports

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4129]
The style import component is outdated, instead of this: 
```scss
@use '@swisspost/design-system-styles/index.scss';
```
We should show this: 
```scss
@use '@swisspost/design-system-styles/[theme]-[channel].scss';
```
where `theme` and `channel` are automatically set using the currently selected theme and channel (stored in the local storage).

**Comment by gfellerph** [comment]
Closing as duplicate of https://github.com/swisspost/design-system/issues/4026
