### ISSUE TITLE
[bug]: component v2: Switch vertical alignment not centered

### ISSUE THREAD

**Issue by sandra-post** [swisspost/design-system#4161]
**Describe the bug**
The switch control and the label are not vertically aligned center, i.e. the switch control is aligned top and therefore not in line with the label. 

**To Reproduce**

1. Go to Storybook --> [Form Switch](https://next.design-system.post.ch/?path=/docs/7fb639f8-86f6-4937-999c-4ee15f81643b--docs)

**Expected behavior**
The switch control should be aligned vertically centered so its also aligned with the label.

**Screenshots**
Figma Design:
![Image](https://github.com/user-attachments/assets/1ff6c6fd-35ce-4693-9e69-32c22c6eb18d)
![Image](https://github.com/user-attachments/assets/9a831ad1-b20d-4158-981d-39e5950730a0)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge
- Version: 131

**Additional context**
- Original GitHub issue: https://github.com/swisspost/design-system/issues/3275
- Figma Design: https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=21-178

**Comment by schaertim** [comment]
This is the same issue described in [#4039](https://github.com/swisspost/design-system/issues/4039) and was just solved in [#4140](https://github.com/swisspost/design-system/pull/4140).
