### ISSUE TITLE
[bug]: Missing border on main navigation mobile

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4267]
**Describe the bug**
A separation border is missing in the main navigation on mobile.

**To Reproduce**
<img width="650" alt="Image" src="https://github.com/user-attachments/assets/6e61d2a1-6a2f-489b-b0e7-66de4bb1b783" />

**Expected behavior**
There should be the same border between local header (white) and the main navigation (slightly grey) as there is on desktop.

<img width="469" alt="Image" src="https://github.com/user-attachments/assets/8b69d52f-92b5-4f55-9404-532648f34699" />

**Comment by alizedebray** [comment]
There is no border in the design: https://www.figma.com/design/JIT5AdGYqv6bDRpfBPV8XR/Foundations-%26-Components-Next-Level?node-id=6505-34282&t=rKuLwShVyhHmK9UR-4
