### ISSUE TITLE
Button Group - Horizontal Auto Width to filling surrounding Element

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#4289]
**Is your feature request related to a problem? Please describe it.**
The Buttons horizontal width adapt to the buttons individual labels/texts.

**Describe the solution you'd like**
Would be nice, if the whole button-group element could do an auto-width, filling the container-width it resides in, and independent of containing label/text, the buttons would all have an equal width.

**Describe alternatives you've considered**
We added w-25, w-50 classes, if in the group are 2 or 4 buttons, but this is no general solution, if a button-group contains 3 or 5 etc. buttons.

**Additional context**
current:
![Image](https://github.com/user-attachments/assets/01b701ab-eae0-4985-a629-d6c5ae4b2df0)

desired:
![Image](https://github.com/user-attachments/assets/cd1a196f-c9b5-457e-9ae0-b5a4544ff906)

**Comment by gfellerph** [comment]
@swisspost/design-system create and document an example with utilities that enables the desired behaviour.

**Comment by alizedebray** [comment]
Expected result can be achieved using the `.d-flex` on the container and `.flex-grow-1` on the buttons:
```html
<div class="btn-group d-flex" role="group" aria-label="Button group example">
  <button type="button" class="btn btn-md btn-secondary flex-grow-1">Left</button>
  <button type="button" class="btn btn-md btn-secondary flex-grow-1">Middle</button>
  <button type="button" class="btn btn-md btn-secondary flex-grow-1">Right</button>
</div>
```
