### ISSUE TITLE
[bug]: Popovers add shadow on optional arrow

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#4291]
**Describe the bug**
 For visibility purposes please add a shadow on the optional arrow shown on a visible popover.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d84d580d-5fc5-4f78-a5de-b17a78359e8f)

**Comment by gfellerph** [comment]
Closing as duplicate of #4290 because the underlying component responsible for rendering the arrow is the same for popover and tooltip.
