### ISSUE TITLE
[bug]: Toast - does not close when clicking/keyboard-enter the closing-X button on the right

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#4292]
**Describe the bug**
does not close when clicking/keyboard-enter the closing-X button on the right.

And also add **type="button"** to the example code on storybook-documentation, otherwise **forms are submitted on clicking the x button.**

**Screenshots**
![Image](https://github.com/user-attachments/assets/4635d5cf-6a96-4224-a329-e705e085cf2c)

```[tasklist]
### Tasks
- [ ] Add `type=button` to example code in storybook
```

**Comment by gfellerph** [comment]
@swisspost/design-system add `type=button` in the docs.

**Comment by gfellerph** [comment]
Similar to #4280, hiding the element on close click should be implemented for the moment. We'll use this ticket to update the documentation.
