### ISSUE TITLE
[bug]: Focus moves to hidden links in closed accordion items in Footer

### ISSUE THREAD

**Issue by alionazherdetska** [swisspost/design-system#4296]
**Description:**
When navigating through the accordion items in the footer using the tab, the focus incorrectly moves sequentially through all links inside closed accordion items before reaching the next accordion header. This behavior causes confusion and violates accessibility expectations.

**Steps to Reproduce:**

1. Open the Composible Footer page.
2. Ensure all accordion items are closed.
3. Use the tab to navigate through the accordion items.
4. Observe that the focus moves through the links inside the closed accordion items before it reaches the next accordion header.

**Comment by gfellerph** [comment]
Check if this applies to all accordions.

**Comment by myrta2302** [comment]
Bug present in any simple accordion, with items containing focusable elements.
