### ISSUE TITLE
[bug]: Mobile main navigation list items on focus has rounded borders

### ISSUE THREAD

**Issue by leagrdv** [swisspost/design-system#4302]
**Describe the bug**
On mobile, the main navigatoin list items have rounded borders when focused.

**Expected behavior**

**Screenshots**
![Image](https://github.com/user-attachments/assets/2e98f5a9-a90f-4a3d-aef4-979d50007eaf)
![Image](https://github.com/user-attachments/assets/048cbef4-b66a-4d9c-91b0-ab3a02b5ab64)

**Comment by gfellerph** [comment]
Closing as won't do
