### ISSUE TITLE
Monorepo Setup

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#473]
According to this post, our monorepo is built incorrectly:
https://javascript.plainenglish.io/monorepo-setup-with-npm-and-typescript-90b329ba7275
Have a look on this docs to:
https://docs.npmjs.com/cli/v7/using-npm/workspaces
https://monorepo.tools/#monorepo-features

Check if we need to fix this!

**Comment by gfellerph** [comment]
We're using pnpm to manage our monorepo. The implementation differs a bit from npm workspaces so I'd not consider this a bug.

https://pnpm.io/workspaces
