### ISSUE TITLE
Migrations: Find a way to manually trigger the migration

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#487]
Angular migration Schematics are usually coupled to a specific package and are triggered when the package gets updated via `ng update`. For our use-case, it will be handy to be able to manually install the migrations package and manually trigger the migration to run. Is there a command for that?

**Comment by oliverschuerch** [comment]
One possibility could be:
`ng update --migrate-only`
source: https://angular.io/cli/update

It's possible we need to insert the `--from` and the `--to` flag to:
`ng update --from=13 --to=14 --migrate-only`

But I'm not a 100% sure if I understand the requirement right now.

**Comment by oliverschuerch** [comment]
`ng update @swisspost/design-system-styles --migrate-only`

**Comment by oliverschuerch** [comment]
@gfellerph please read my previous post and tell me how we will deal with the findings ;)

**Comment by gfellerph** [comment]
Like this:

```json
"ng-update": {
    "migrations": "@swisspost/design-system-migrations/migrations.json"
  }
```

**Comment by oliverschuerch** [comment]
Working Solution without changing the repo structure (tested by @gfellerph)

1. Insert the `ng-update` property into the package.json of @swisspost/design-system-styles
This specifies, where the angular migrations file is located.
```json
{
  "name": "@swisspost/design-system-styles",
  "version": "5.0.0-beta.1",
  "description": "Design System Styles for the Swiss Post web platform.",
  "author": "Swiss Post <oss@post.ch>",
  ...
  "ng-update": {
    "migrations": "@swisspost/design-system-migrations/migrations.json"
  }
}
```
2. Open console in the project root.
3. Run `pnpm bootstrap` to install/copy new styles-package into the demo-package.
4. Run `cd packages/demo`. 
5. Use the following command to run the migrations:
`npx ng update @swisspost/design-system-styles --from=4 --to=5 --migrate-only`
