### ISSUE TITLE
Pnpm install requires peer dependencies

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#532]
![image](https://user-images.githubusercontent.com/1659006/193574809-51081d5d-4977-4e79-9fd8-6ed012738436.png)

When doing a `pnpm install`, a lot of peer dependencies are being requested, mostly by storybook. However, the solution works without installing them. To better reflect the situation, it may be beneficial to make use of the `pnpm.peerDependencies.ignoreMissing` rule:
https://pnpm.io/package_json#pnpmpeerdependencyrulesignoremissing

**Comment by oliverschuerch** [comment]
In a pnpm monorepo, these rules must be added to the root package.json file to work propperly.
