### ISSUE TITLE
Bugfix: misaligned floating labels with validation or hint

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#559]
When used with a form control that has validation and/or hinting, floating labels move down instead of staying in the center of the input.

![Image](https://user-images.githubusercontent.com/33580481/194303661-a2591309-693b-4d28-b285-ce7269041d98.png)

![Image](https://user-images.githubusercontent.com/33580481/194303741-8ce7c915-6d53-4d4d-8aff-3f06e434a196.png)

![Image](https://user-images.githubusercontent.com/33580481/194303890-d0e1680c-4347-4c39-ace7-ed3e10b1ccfb.png)

- [x] fix alignment of floating labels on form controls that have validation and/or hinting
- [x] make sure the solution work with all the following entry types: 
       - input
       - select
       - file selector
       - text area

**Comment by oliverschuerch** [comment]
I saw this error some days before, but forgot to create an Issue.
Thanks @alizedebray, great work!
