### ISSUE TITLE
Styles: Min-height for textarea

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#609]
Textareas don't have a sensible min-height set. Even the example uses inline styles to set one (https://design-system.post.ch/#/bootstrap-samples/form-textarea).

A default height textarea shows a scrollbar:
![image](https://user-images.githubusercontent.com/1659006/196872448-f2a5294e-5eff-4357-bd32-c8ddd5695f8c.png)

@swisspost/design, should we set the default height to at least 3 rows?
![image](https://user-images.githubusercontent.com/1659006/196873205-dde20912-561f-40a6-b3a8-db9237bf4394.png)

**Comment by moniesan** [comment]
....and if the user enters more than the 3 lines a scrollbar is shown and, in addition, the user can expand the area via the 2 stripes in the triangle?
Is the triangle (-> expanding) really useful and needed if a scrollbar is shown, too? Wouldn't this function destroy the layout/ responsiveness? 
--> so I would prefer min. 3 lines and if more is entered a scrolbar is shown
BTW: What is with the help of counting down a given amount of characters? Or is it another component?

**Comment by gfellerph** [comment]
A scrollbar is still shown when the user enters more than 3 lines, the triangle is shown anyways, but the field can only be enlarged beyond 3 lines and not shrunk.

The character count-down is something unrelated to the issue at hand, but something that has not been documented very well even if there were some requests in that direction.

**Comment by wueestd** [comment]
I would also suggest to visually indicate the difference from a text area to a text field by having a different default height. If two or three rows by default is hard to say. Probably depending on the use case.

**Comment by Cian77** [comment]
I think it would be a good idea to see a difference between the two components. For now, I have added three rows. https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7779%3A34916&t=MlAQKFohcAcPGd2e-0

**Comment by gfellerph** [comment]
Perfect, thx.
