### ISSUE TITLE
Add automatic migration for Checkbox classes

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#636]
![image](https://user-images.githubusercontent.com/9716662/197565056-b73c34af-9a1a-4bf5-990d-0993f0607a54.png)

This applies for the following Elements:
- Form Checkbox
- Form Radio

**Comment by oliverschuerch** [comment]
This migrations are allready integrated.

**Comment by gfellerph** [comment]
Closing because it's already done.
