### ISSUE TITLE
Migrations: migrate (s)css automatically

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#725]
In Version 5, some CSS classes and SCSS variables have changed.
It is therefore necessary to write migration schematics so that these classes and variables are updated automatically.

**Comment by gfellerph** [comment]
Still relevant, but not a priority.

**Comment by oliverschuerch** [comment]
@alizedebray if you could create a tasklist which defines in detail what to do or how to find out what to do, that would be great!

**Comment by gfellerph** [comment]
In the future, we will need to think about how we can provide migrations to non-angular projects. Not sure if this is a good place to start, but just as an info.

**Comment by gfellerph** [comment]
Closing as no longer relevant (after 2 years)
