### ISSUE TITLE
Optimize Radio Button

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#800]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7777%3A33876&t=zTAKJLbklgpXEsSf-1

**Comment by wueestd** [comment]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7777%3A33876&t=zTAKJLbklgpXEsSf-1

**Comment by gfellerph** [comment]
Invalid radio buttons have a different design:

Implementation:
![image](https://user-images.githubusercontent.com/1659006/203545183-0aba5f20-f747-4c70-833c-6084bc6c3765.png)

Design:
![image](https://user-images.githubusercontent.com/1659006/203545240-5e4fb5e9-be36-4907-9943-848e87ad299d.png)

**Comment by wueestd** [comment]
@gfellerph do you need any input from my side? circle is 10x10px 😉

**Comment by gfellerph** [comment]
> @gfellerph do you need any input from my side? circle is 10x10px 😉

no, think it's ok. We just need to do it https://github.com/swisspost/design-system/issues/852

**Comment by gfellerph** [comment]
Closing as done, follow up tickets are created.
