### ISSUE TITLE
Optimize text area

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#803]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7779%3A34916&t=zTAKJLbklgpXEsSf-1

**Comment by wueestd** [comment]
UX Tasks

- [ ] 3 Lines default
- [ ] validation state

**Comment by Cian77** [comment]
- [x] 3 lines
- [x] validation state

**Comment by wueestd** [comment]
ready for second review @gfellerph https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7779%3A34916&t=zTAKJLbklgpXEsSf-1

**Comment by wueestd** [comment]
what's the difference between focus and active? is it the same?

**Comment by gfellerph** [comment]
[Active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active): user is pressing something with their finger, mouse or else.
[Focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus): The cursor is inside the field. In this state, the fields value can be edited.

_Added for completeness_
