### ISSUE TITLE
Optimize Select

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#804]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7802%3A33963&t=zTAKJLbklgpXEsSf-1

**Comment by wueestd** [comment]
ready for frontend review

**Comment by Cian77** [comment]
- [x]  Add Validate state

**Comment by wueestd** [comment]
Ready for second review @gfellerph https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7802%3A33963&t=zTAKJLbklgpXEsSf-1

**Comment by gfellerph** [comment]
@wueestd Figma looks great, just a question: what are the empty viewports for, next to the component? I updated the status in the component tracker.

**Comment by wueestd** [comment]
@gfellerph we found out that states for a floating label field are different, depending on the fact if they are filled or not. therfore we changed the variant sctructure to a matrix:
|          | empty | filled |
|----------|-------|--------|
| Default  |       |        |
| Hover    |       |        |
| Selected |       |        |
| Error    |       |        |
| ...      |       |        |

Does that help?

**Comment by wueestd** [comment]
@gfellerph should we close this task?

**Comment by gfellerph** [comment]
Closing as done. Status is updated and dev tasks are created.
