### ISSUE TITLE
Styles: Align text input styles with figma

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#807]
Align the implementation of the text input with figma (https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7830%3A34310&t=cV2KtiERUC03yvvs-4).

**This is a breaking change.**

- [ ] Show placeholder on floating label inputs (wait till label is floated, then remove color transparency and on blur, hide the placeholder fast before the label is animated)
- [ ] Reduce number of size variants to two (72px and 48px)
- [ ] Rename the component to Text Input
- [ ] Update storybook and demo app

**Comment by imagoiq** [comment]
@gfellerph it looks like an old issue which is covered by: https://github.com/swisspost/design-system/issues/1835 and https://github.com/swisspost/design-system/issues/2225

**Comment by gfellerph** [comment]
Closing as duplicate of #1835, #2225 and #2527
