### ISSUE TITLE
Storybook: Add basics.css to the manager head

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#808]
In order to be able to use styles and variables from the basics.css, we could add that to the manager-head.html (https://github.com/swisspost/design-system/pull/799#discussion_r1030885547).

**Comment by oliverschuerch** [comment]
As far as #886 is merged, there is a `manager.scss` in the `.storybook` folder, where we can load/use `basics.scss`, for whatever you want to do ;)

**Comment by gfellerph** [comment]
@oliverschuerch I think we can close this, agree?
