### ISSUE TITLE
Font Curves: Optimize

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#849]
**Figma:**
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=20702%3A14987&mode=design&t=SiIozCQkJVhqkBSu-1
----------------

Update and Optimize Curves:
https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations?node-id=3%3A955&t=6qJsoz9r71BHjnn4-1

Curves use values (15, 17, ...) that are not used elsewhere. Curves are important for automatic responsive type in the implementation and used extensively

Curves lack a description for when to use which curve
Can we map responsive heading size progression to a curve?

Fonts are named atm (big, biggerBig, huge). In future mor like (size16, size18, size20, ...)? 
Namings of curves and fonts should have the same system (e.g. names or sizes / sizerange).

**Comment by gfellerph** [comment]
No longer needed with tokens
