### ISSUE TITLE
ngx-datatable: Update styling

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#85]
Demo: http://swimlane.github.io/ngx-datatable/ 
Github: https://github.com/swimlane/ngx-datatable 
Design: https://www.experience-hub.ch/document/2803#/organisms-module/tables

**To do:** 

- [ ] Selectable rows (with checkboxes)
- [ ] Cell edition 
- [ ] Hover and active states
- [ ] Responsive behavior
- [ ] Active/selected cells and rows
- [ ] Loading indicator with virtual paging

**Comment by oliverschuerch** [comment]
@gfellerph we need to discuss this again, before I'll do any change to this component.

**Comment by gfellerph** [comment]
Moved out of scope for v5.0. Will be implemented for a later feature (minor) release.

**Comment by gfellerph** [comment]
ngx-datatable does not seem to be actively maintained. We're looking for supporting another datatable library. Closing this ticket because of this.
