### ISSUE TITLE
Styles: Select vertical alignment is slightly off

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#851]
- [ ] Vertical alignment is slightly off in the demo app
  ![image](https://user-images.githubusercontent.com/1659006/205652357-31e7a3c9-f9ce-4781-9ed9-9411c7ac9b43.png)
- [x] Arrow size is off: Figma 15x8.5px, Demo App 14x?px. The design uses a 32x32 icon with white space (export it from figma for the right dimensions)

_Originally posted by @gfellerph in https://github.com/swisspost/design-system/issues/804#issuecomment-1337409801_

**Comment by gfellerph** [comment]
- [ ] Check if this is still the case

**Comment by b1aserlu** [comment]
Select is not the only component that needs its vertical allignment adjusted. This in fact concerns all the form input components.
I created this #2163 ticket to solve this
