### ISSUE TITLE
Styles: radio button design update

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#852]
Selected dot size and circle are different. Implement the design specs from https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=7777%3A33876&t=zTAKJLbklgpXEsSf-1.

  Design dot: 10x10, circle: 22x22 (line height of the label)
  ![image](https://user-images.githubusercontent.com/1659006/203547376-87d465d3-31d4-4fd4-a012-93ee8970776c.png)

  Implementation dot: (?x?), circle: 24x24
  ![image](https://user-images.githubusercontent.com/1659006/203545507-d080adbb-f556-4a50-a7cf-39434649865e.png)

_Originally posted by @gfellerph in https://github.com/swisspost/design-system/issues/800#issuecomment-1324970213_

**Comment by yannikstuker** [comment]
By adjusting the radius from the source of the svg `data:image/svg+xml,<svg version='1.1' xmlns='http://www.w3.org/2000/svg' viewBox='-3 -3 6 6'><circle opacity='1' fill='%23000000' r='3'></circle></svg>`, the size of the dot is adjustable. The correct factor to resize the dot to fit the pixel as specified needs to be calculated

**Comment by gfellerph** [comment]
On hold until Design Review is done
