### ISSUE TITLE
Height of checkbox with aria-label only

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#856]
If a checkbox has only an `aria-label` and no real `label` tag, the height is not set and validation feedbacks and other content is rendered over the checkbox.

![image](https://user-images.githubusercontent.com/9716662/206194487-57a98c6c-bd13-4ad2-bc80-aa9c60715877.png)

**Comment by gfellerph** [comment]
Seems to be fixed https://next.design-system.post.ch/?path=/story/components-checkbox--default&args=hiddenLabel:true;validation:is-valid. Can you verify @oliverschuerch?

**Comment by gfellerph** [comment]
Closing as fixed
