### ISSUE TITLE
Style: default legend styles are too big

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#877]
Reproduction: https://next.design-system.post.ch/?path=/docs/components-radio-button--default#inline
Figma: https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components?node-id=8188%3A34882&t=AeSfm7gOEdQY9LHh-4

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1659006/207113526-bbd34738-633f-43b1-92cc-20fd2f6940f7.png">

The default styles coming from bootstrap (reboot) for the fieldset legend elements to label radio- or checkbox groups is too large. It should be `$font-size-18`.

Set this in the file https://github.com/swisspost/design-system/blob/main/packages/styles/src/components/type.scss

**Comment by geekrumper** [comment]
is fixed in #1512
