### ISSUE TITLE
Styles: placeholders folder clean up

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#888]
https://github.com/swisspost/design-system/tree/main/packages/styles/src/placeholders

- The placeholders folder contains the badge.scss which is not marked as a partial sass file with the underscore prefix
- Not all of the placehoder files are imported in the index, check if any placeholder file is unused and delete it

**Comment by b1aserlu** [comment]
created a new issue #2202  to remove some placeholders that were deprecated in a changeset as discussed with @gfellerph.
