### ISSUE TITLE
Add documentation page for scss :export

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#905]
Maybe this could be useful for our developers as well ;)
For more informations, see: [#901](https://github.com/swisspost/design-system/pull/901/files/ec3bc686ab1c93d2d2d191348a775b67966c1228#diff-ee5f1b024a1464cd089fbb5b22275b6b486348adcc76e68502ad7ffd11e9aaaa)

**Comment by gfellerph** [comment]
@oliverschuerch is this a duplicate of #586?

**Comment by gfellerph** [comment]
Closing it as duplicate
