### ISSUE TITLE
Button - add "show Icon on mouse-hover/focus from keyboard tabbing" css classes

### ISSUE THREAD

**Issue by aedu-hostettler** [swisspost/design-system#922]
Hallo (zusammen)

Der primary Button "Preis berechnen" auf der Seite

https://www.post.ch/de/briefe-versenden/briefe-schweiz

hat  on "hover" ein animiertes "chevron-end/right".

Wäre es möglich diesen Effekt ins Design-System aufzunehmen? 

Naming ist halt wiedermal schwer wenn es schweizweiter Verwendung recht gemacht werden soll. :)

Z.B. mit btn-hover-chevron-end oder btn-hover-chevron-start (wobei hover eben auch focus oder sonst ein event sein könnte)
oder genereller ohne "chevron-x" in Kombination mit allen pi- icon classes.
So dass man mit -start oder -end die position links oder rechts von text angeben kann, und mit der pi-klasse das anzuzeigende Icon bei dem entsprechenden event?

Oder vielleicht wäre es einfacher nur css klassen welche z.b. "button-process-navigation-next", "button-process-navigation-previous" heissen könnten? (oder ohne "process") button-navigation-next. 

Also für meine konkreten Bedürfnisse würden aktuell chevron-start und chevron-end reichen, aber evt. wollt ihr das gerade so flexibel wie möglich implementieren?

Bei Rückfragen oder Unklarheiten/Ergänzungswünschen meiner Beschreibungen bitte Mail an adrian.hostettler@glauxsoft.com

lg, Adrian

**Comment by gfellerph** [comment]
Hey Adrian

I think we already got you covered. Take a look at https://design-system.post.ch/#/bootstrap-samples/buttons:

```html
<button class="btn btn-primary btn-animated"><span>Primary</span></button>
```

The animated button allows for just a chevron right and not any icon or any direction. If you need more flexibility, we can discuss about your use case.

**Comment by aedu-hostettler** [comment]
Hy Philipp

Thx for your fast answer. 

When i read the description about the "btn-animated" css class prior to posting this question, i thought, that it would be exactly this arrow animation, but because i can't see the animation in any browser on mouseover, i thought, it was maybe a little button background color change animation instead. :)

When i try to take a screenshot, my mouse-cursor vanishes from the screenshot, but i tried to hover over the button from your example url (i checked in the source code, that the "btn-animated" css class was present), but no chevron-right appears in any browser i tried (not gonna add the versions, because they are current, and i dont think it depends on the exact versions of the browsers.): FF, Edge (Chromium), Opera, Chrome.

Maybe the previous available functionality broke, during the process of updating/fixing something else?

In the following picture, the arrow and "m" would show, the "mouse-position" on hover, and that right besides the buttontext it would stay empty.

ps: i'm using following npm package version "@swisspost/design-system-styles": "5.1.3". (maybe it worked in previous versions?)

cheers, Adrian

![no chevron right on mouse hover](https://user-images.githubusercontent.com/91196153/210555360-6f6f3de1-732d-48f6-a58c-a592e48083ce.PNG)

**Comment by gfellerph** [comment]
Can you please check if you have enabled animations on your operating system? We disabled the animation for users that prefer reduced motion because the text is slightly moving to the left as well and this may cause motion sickness or other issues.

![image](https://user-images.githubusercontent.com/1659006/210600513-cf019aab-5e17-44e0-b16f-417da572b9c9.png)

**Comment by aedu-hostettler** [comment]
Uh, that was it. Probably got disabled when Screenreaders were installed on the system. (Got NVDA and JAWS installed)

Sorry for the timewaste, and thx for your time. ;)

**Comment by gfellerph** [comment]
No worries, glad I could help.
