### ISSUE TITLE
Storybook: Lead font size is being reset by rfs.scss

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#928]
![image](https://user-images.githubusercontent.com/1659006/210380365-4e1fa7b0-ae2d-452c-b83b-f05cd5988ac6.png)

This shows the lead text smaller than the body text while it should be bigger or the same size.

**Comment by oliverschuerch** [comment]
I can not find any Figma definition page!

**Comment by oliverschuerch** [comment]
Found specs here: https://www.experience-hub.ch/document/2803#/layouts-seiten-templates/content
