### ISSUE TITLE
Create grid docs page

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#948]
Our grid is built on the bootstrap grid.
However, there are significant differences that are not documented anywhere and only become apparent in the code.
These differences need to be documented.

Consider the following files and their dependencies:
- styles/src/components/grid.scss
- styles/src/layouts/portal/_variables.scss

- [ ] update link on text utility page, which links to this page

**Comment by oliverschuerch** [comment]
duplicates #1048

**Comment by gfellerph** [comment]
Closed as duplicate
