### ISSUE TITLE
Setup: Merge config, formatter and linting settings

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#966]
Each package has it's own linting, formatting and tsconfig rules. These could be combined in the root, inherited and overwritten where necessary by packages. This would allow for more consistency and easier setup for new packages and dev environments.

**Comment by oliverschuerch** [comment]
@gfellerph I think @imagoiq did it already, so we could close this ticket, right?

**Comment by gfellerph** [comment]
@oliverschuerch, certainly a part of it. We might even be able to remove the prettierrc files in the packages if there is a global one that is exactly the same.

**Comment by gfellerph** [comment]
Closing as no longer relevant
