### ISSUE TITLE
Group Form Elements

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#976]
Make propositions:
Create new mainnavigation group on the level of `Foundation`, `Components`, ...
Create new group folder under the mainnavigation point `Components`.

**Comment by gfellerph** [comment]
The issue is a little outdated, but we could make a proposal to group components in the "Components" navigation entry. Bootstrap 5.3 could be an example https://getbootstrap.com/docs/5.3/getting-started/introduction/.

**Comment by b1aserlu** [comment]
closed for #2318
